### ISSUE TITLE
Unrecognized front-matter format

### ISSUE THREAD

**Issue by zolamk** [netlify/netlify-cms#1470] opened 2018-06-27 11:22 UTC
**- Do you want to request a *feature* or report a *bug*?**
*bug*

**- What is the current behavior?**
when using the `field` option of a `list` widget

- it doesn't display the repeated widget properly
- and there is the below error in console 
    
    columnNumber: 96902
    fileName: "https://unpkg.com/netlify-cms@1.9.2/dist/cms.js"
    lineNumber: 35
    message: "Unrecognized front-matter format."
    stack: "a<@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:35:96902\ne.exports@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:35:69344\ne.exports/<@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:167:24316\nvalue/<@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:12:96819\nvalue@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:12:93093\nvalue/<@https://saleina.netlify.com/admin/cms.js:12:93472\na@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:783:88910\nP/<@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:783:89055\nu@https://unpkg.com/netlify-cms@1.9.2/dist/cms.js:783:87079\n"

**- If the current behavior is a bug, please provide the steps to reproduce.**

- add a collection with a `list` widget and `field` option
- and add a new instance of that collection

![screen shot 2018-06-27 at 14 08 56-fullpage](https://user-images.githubusercontent.com/14203663/41970470-ad9359b6-7a13-11e8-80a0-48ee09f270a6.png)

**- What is the expected behavior?**
it should display the repeated widget properly

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.2
Browser version: Firefox 60.0.1

**- Please link or paste your `config.yml` below if applicable.**
backend:
      name: "git-gateway"

    media_folder: "static/uploads/"
    public_folder: ""

    collections:
      - name: "data"
        label: "Data"
        files:
          - label: "Contacts"
            name: "contacts"
            file: "data/contacts.yml"
            fields:
              - {label: "Address", name: "address", widget: "string"}
              - {label: "Phone Number", name: "phone_numbers", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
          - label: "Settings"
            name: "settings"
            file: "data/settings.yml"
            fields:
              - {label: "Site Title", name: "title", widget: "string"}

      - name: "blog"
        label: "Blog"
        folder: "content/blog"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Featured Image", name: "thumbnail", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "product"
        label: "Product"
        folder: "content/product"
        create: true
        slug: "{{slug}}"
        fields:
          - {label: "Draft", name: "draft", widget: "boolean", default: false}
          - {label: "In Stock", name: "in_stock", widget: "boolean", default: true}
          - {label: "SKU", name: "sku", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Category", name: "category", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list"}
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
          - {label: "Price", name: "price", widget: "number", valueType: "float", default: 0.0}
          - {label: "Used", name: "used", widget: "boolean", default: false}
          - {label: "Description", name: "body", widget: "markdown"}

**Comment by erquhart** [comment] 2018-06-28 16:55
Duplicate of #1195, being addressed in #1395. Please have a look at those and add any information you think is missing.

**Closed by erquhart** 2018-06-28 16:55 UTC
