### ISSUE TITLE
Question: Why does Netlify CMS need access to private repos with Github backend?

### ISSUE THREAD

**Issue by alexearnshaw** [netlify/netlify-cms#2575] opened 2019-08-22 14:30 UTC
We are using Github backend and have created an authentication provider app on our Github organization repo as per the documentation https://www.netlifycms.org/docs/authentication-backends/#github-backend and https://www.netlify.com/docs/authentication-providers/#using-an-authentication-provider

One of our potential users has raised an issue regarding the level of access that this app requests for Netlify CMS
![axway-open-docs-access](https://user-images.githubusercontent.com/29064556/63523166-84760400-c4f1-11e9-8ebd-adcbaa275f70.png)

Can anyone please explain why these access levels are needed and particularly why access is needed to **private** repos?

**Comment by papandreou** [comment] 2019-08-22 14:57
Duplicate of https://github.com/netlify/netlify-cms/issues/1423

**Closed** 2019-08-22 15:44 UTC
