### ISSUE TITLE
All entries in the CMS disappeared. 

### ISSUE THREAD

**Issue by hkrank** [netlify/netlify-cms#2896] opened 2019-11-19 10:14 UTC
**Describe the bug**
Shown message if Im logged into the CMS.
 `Failed to load entry: TypeError: Cannot read property 'split' of null`

**To Reproduce**
All my entries disappeared. No content shown in the CMS.

**Screenshots**
<img width="801" alt="Bildschirmfoto 2019-11-19 um 10 29 16" src="https://user-images.githubusercontent.com/1030255/69134256-7d8e6b80-0ab7-11ea-99fa-fdb9f07bb21c.png">

<img width="1031" alt="Bildschirmfoto 2019-11-19 um 10 12 58" src="https://user-images.githubusercontent.com/1030255/69134039-34d6b280-0ab7-11ea-9668-6d87db517659.png">

<img width="1371" alt="Bildschirmfoto 2019-11-19 um 10 13 25" src="https://user-images.githubusercontent.com/1030255/69134140-559f0800-0ab7-11ea-8137-e7cc3ead5df8.png">

**Applicable Versions:**

 - Netlify CMS version: 2.3.3
 - Git provider: GitLab
 - OS: Catalina
 - Browser version  Chrome 78.0.3904.87

 - Node.JS version:  8

**CMS configuration**

backend:
```
name: git-gateway
branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog

```
**Additional context**
I have two Apps running with Netlify CMS all of them are the same now. No CMS entries anymore. Both are connected via GitLab. 
Both of them have different setups and all work great round about 10 days ago.  My clients where able to make changes. The error pops up since a couple of days. 
I remember that we had the same issue this year regarding the assets folder. I hope the team can solve this like last time. Thank you.

**Comment by erezrokah** [comment] 2019-11-19 10:16
This is a duplicate of #2881
See here https://www.netlifystatus.com/incidents/2r4ndv92qvs9

**Closed** 2019-11-19 10:18 UTC

**Comment by hkrank** [comment] 2019-11-19 10:20
Thanks for quick reply.

**Comment by erezrokah** [comment] 2019-11-19 12:05
This has been resolved https://www.netlifystatus.com/incidents/2r4ndv92qvs9?u=lrdhk0vbrbm7

**Comment by ChenMorSays** [comment] 2020-03-18 12:21
I'm having the same problem @erezrokah , any ideas how I may resolve it?

**Comment by erezrokah** [comment] 2020-03-18 13:38
Hi @ChenMorSays, I think you might be experiencing a different issue, as this one was related to a Netlify incident that had been resolved (same goes for your comment here https://github.com/netlify/netlify-cms/issues/1078#issuecomment-600605958). 
You could trying asking in out slack #help channel: https://netlifycms.slack.com/join/shared_invite/enQtODE1NTcxODA5Mjg1LTRjYWExM2MyZDJmODA3YmVkMjI2YmQwZDg2ZDUyYTMyM2Y3Zjc1ZTJhNDBkYmMwNjA2ZTkwODY4YjZjNGNlNTE

Or post a new issue following the issue template.
