### ISSUE TITLE
collection listing fails with 404 error when more than 14 items

### ISSUE THREAD

**Issue by yoavniran** [netlify/netlify-cms#2621] opened 2019-08-29 09:30 UTC
**Describe the bug**
In the admin of my site's "blog" collection I no longer can see all of the posts.
It shows the first 14 items but then i see an error notification.

in the dev console i get this:

![screenshot-20190829_120200](https://user-images.githubusercontent.com/1102278/63926661-dddfb500-ca54-11e9-963d-282c10f52b17.jpg)

This error didnt occur before I had more than 14 posts and doesnt happen in another collection (set up very similarly) which doesnt have 14 posts yet.

The URL it fails on is: https://my-domain.com/.netlify/git/gitlab/repository/files/src%2Fpages%2Fblog%2Ftags/raw?ref=master&ts=1567069264058

**To Reproduce**

My collection folder is set up like so:

- /src/pages/blog  **where the problem happens**
               index.md
               post1.md
               post2.md
               ...
              post15.md
               - /tags
                      index.md

-/src/pages/products    **no problem**
                index.md
                post1.md
                post2.md
                ...
                post7.md
               - /tags
                      index.md

As I can see from this closed issue: #2032 
There seems to be a problem with subfolders under a collection
That issue wasnt solved by the way

**Expected behavior**
 a collection shouldnt try to load files that arent part of the collection. definitely not from a sub folder and definitely shouldnt break because there's a subfolder present.

**Screenshots**

![screenshot-20190829_122713_LI](https://user-images.githubusercontent.com/1102278/63928686-aa068e80-ca58-11e9-991d-7773fb0e315a.jpg)

**Applicable Versions:**

 - Netlify CMS version: 2.9.7
 - gatsby: 2.13.72
 - gatsby-plugin-netlify-cms: 4.1.12

 - Git provider: gitlab

**CMS configuration**
This my collections config:

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    filter: {field: "templateKey", value: "blog-post"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "[{{year}}/{{month}}/{{day}}] {{title}}"
    preview_path: "blog/{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path_date_field: "date"
    delete: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "מונטסורי בייבי"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: image}
      - {label: "Body", name: "body", widget: "rtlmarkdown"}
      - {label: "Tags", name: "tags", widget: "list"}     
      - {label: "PostId", name: "postId", widget: "postId"}

**Comment by tomrutgers** [comment] 2019-08-29 10:32
Unfortunately, subfolders are not yet supported: https://github.com/netlify/netlify-cms/issues/513
The CMS doesn't know yet what to do with subfolders present in your collection folders. I completely agree with the expected behavior but we're not quite there yet.

**Comment by yoavniran** [comment] 2019-08-29 11:27
thanks @tomrutgers 
thats a tough one because it means i either need to make an awkward folder structure change or use Gatsby API to generate those pages on the fly (which ill probably do) but it means i lose the ability to allow my users to add content to it...

how hard would it be to make it at least ignore the subfolder for now? 
i think its reported as type "tree" no? so it can be skipped over?

I wouldnt mind PRing if you could point me to the right place in the code

**Comment by tomrutgers** [comment] 2019-08-29 11:33
Thoughts @erquhart?

**Comment by barthc** [comment] 2019-08-30 21:04
@yoavniran the CMS would try to filter and list only files in the current folder ignoring subfolders.  I think there is a particular spot where that filter is omitted, I assume you are running a local copy of the CMS. I would need you to replace this line https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-backend-gitlab/src/API.js#L206 with this:
`return { entries: entries.filter(({ type }) => type === 'blob').reverse(), cursor: this.reverseCursor(newCursor) };`

I did not test the changes, but pretty sure it will solve your issue, give it a try.

**Comment by kylekirkby** [comment] 2019-09-02 09:11
Hi all,

I'm getting a similar issue. I've got a `_pages` folder that contains all our site's pages as markdown files. Sometimes I'll get all pages shown in the collection and other times half of them will 404. Do you think this is something to do with GitHub? The pages sometimes load after a few attempts but seem really temperamental.

I can see that the file's details are available at https://api.github.com/repos/linaro/connect/contents/_pages/about.md?ts=1567415240345&ref=develop

But maybe the wrong URL is being used?

NetlifyCMS Versions:

- netlify-cms-core 2.12.1
- netlify-cms 2.9.6

Our Site: [https://staging.connect.linaro.org](https://staging.connect.linaro.org)
Our NetlifyCMS config: [config file](https://github.com/Linaro/Connect/blob/develop/admin/config.yml)

Pages not displaying on staging.connect.linaro.org:
![staging-pages-not-loading](https://user-images.githubusercontent.com/4564433/64102640-45a14300-cd68-11e9-951a-3837b7b36613.png)

Pages displaying on localhost:
![localhost-pages-loading](https://user-images.githubusercontent.com/4564433/64102754-80a37680-cd68-11e9-87e1-47a3b3322d7c.png)

Thoughts guys? @erquhart 

I'm going to fork and attempt to debug myself but seems very strange :D 

All the best,

Kyle

**Comment by kylekirkby** [comment] 2019-09-02 10:07
So after hacking around with the netlifycms source - I realized that the above can be solved by opening in an incognito browser window. I'm no longer getting the missing files/cannot open DB issue. Is this the intended behaviour? Possibly an issue with how the localforage.js library works. Clearing the browser cache in chrome also didn't seem to work; the only solution that worked was to open a new private window... Hope this saves some people some time.

**Comment by barthc** [comment] 2019-09-09 12:32
This issue can be reproduced by having enough entries(more than 20)  to trigger pagination on a folder that has sub-folder(s). Changes suggested above is still the fix, PR #2668 would close this.

**Comment by erquhart** [comment] 2019-09-10 15:30
Good catch @barthc, didn't realize we were bypassing the subdirectory filter.

**Closed** 2019-09-10 15:31 UTC
