### ISSUE TITLE
Plugins & Custom Widget Repo

### ISSUE THREAD

**Issue by LaneLourcey** [netlify/netlify-cms#936] opened 2017-12-19 11:29 UTC
I'm just making my way through the docs but I thought I saw something about plugins, and I know there are custom widgets. Is there any place these are posted or can be shared?

**Comment by tech4him1** [comment] 2017-12-19 17:55
Duplicate of https://github.com/netlify/netlify-cms/issues/919

**Closed by tech4him1** 2017-12-19 17:55 UTC

**Comment by erquhart** [comment] 2017-12-24 13:34
@LaneLourcey thanks for pointing this out - we're discussing potential solutions in #919 as Caleb mentioned, but we don't have anything working just yet. Soon!
