### ISSUE TITLE
Page template dropdown

### ISSUE THREAD

**Issue by FR073N** [netlify/netlify-cms#4664] opened 2020-12-01 07:52 UTC
Like gitlab or github, when having a markdown field for content, having the possibility to populate the content with a template would be a really cool feature.

**Describe the solution you'd like**
In the config file we would link the markdown field to a folder or a file : 

```
 { 
          name: body, 
          label: Body, 
          widget: markdown, 
          hint: 'The page content...' 
          templates:    <- Or anything like that
            files: myfile/folder
        }
```

In the editor, we would have an interface like gitlab : 

<img width="1180" alt="Capture d’écran 2020-12-01 à 08 46 08" src="https://user-images.githubusercontent.com/3114582/100711573-c1e26600-33b1-11eb-8f69-551c218552e8.png">

When selecting a template, it copy paste the content to the field.
If a content is already added, a yes no confirm dialog to indicate that the content already written will be erased can be enough.

This can make blogging easier than already that its.

**Comment by erezrokah** [comment] 2020-12-01 11:21
closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/3488.
Please comment if you think this is a different issue

**Closed by erezrokah** 2020-12-01 11:21 UTC
Labels: type: feature
