### ISSUE TITLE
Support for React Hooks

### ISSUE THREAD

**Issue by Knaackee** [netlify/netlify-cms#2026] opened 2019-01-23 10:08 UTC
My GatsbyJS site uses React Hooks (currently in alpha).
Netlify CMS does not support React Hooks at the moment. I am getting

> Sorry!
> There's been an error - please report it!
> 
> Invariant Violation: Minified React error #298; visit https://reactjs.org/docs/error-decoder.html?invariant=298 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
> 
> Hooks can only be called inside the body of a function component.

Any ideas?

**Comment by talves** [comment] 2019-01-23 18:39
Any way you can reproduce with a code example on a test repository?

Since Hooks are still in alpha, it may take a while for review. I'm currently waiting for release before I try to tackle integration, but your example would help also.

**Comment by Knaackee** [comment] 2019-02-06 21:08
Sorry for the late reply. 
React just released version 16.8 today.
This version contains hooks.

**Comment by erquhart** [comment] 2019-02-06 21:17
Yep, stable now. We'll take a PR to upgrade React packages to 16.8.

**Comment by talves** [comment] 2019-02-07 15:27
@erquhart do you see the PR being anything other than bumping the versions? I think we should make it a priority.

I will take it.

**Comment by erquhart** [comment] 2019-02-08 02:20
Yep just a bump of the react packages.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Knaackee** [comment] 2019-02-13 08:04
Should it work now? I just updated the packages but still getting 

`Hooks can only be called inside the body of a function component.`

Is there any release date ?

Thank you very much!

**Comment by erquhart** [comment] 2019-02-13 13:31
It's working as of 2.4.1 - that error means you're calling Hooks from somewhere other than the body of a function component.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by talves** [comment] 2019-02-14 16:54
@Knaackee you are correct. You will not be able to use hooks until we find a solution for using the same instance of react.

**Comment by Neddz** [comment] 2019-02-14 18:15
I am having the same issue, my component works everywhere and with other libraries except when I use it in the `registerPreviewTemplate`.

I am getting the same error that people above:
`Hooks can only be called inside the body of a function component.`

**Comment by talves** [comment] 2019-02-14 18:22
@Neddz Is the component using hooks? If so, it will not work until we find a solution.

**Comment by Neddz** [comment] 2019-02-14 18:23
@talves It is, I just wanted to confirm that this is happening to me as well and it is not a problem in the component itself.

**Comment by talves** [comment] 2019-02-14 22:50
@erquhart I made a PR of what I am proposing for a fix.

I created #2097 to have `netlify-cms-core` use react, react-dom as peer dependencies.
There is a proposed new bundle build that will be a manual init build (`dist/netlify-cms-manual-init.js`) with react and react-dom as an external dependency, so we can import the library into a custom build that can use react hooks and allow for the CMS to use the same instance of react on the CMS as any registered widgets and backends.

I believe this is the correct way to solve this issue. This will allow for projects to continue with hooks and for NetlifyCMS to figure out if it will create a new library for 3.0 and move the build into it's' own library.

Caveat: Automatic init bundle `dist/netlify-cms.js` will not be able to use widgets that use react-hooks still. That is the side affect of the way the bundle is built and the the way registering  widgets and backends currently work.

**Comment by talves** [comment] 2019-02-16 18:56
On the netlify-cms-manual-init.js bundle, I would like to take the globals into the CMS global (i.e. CMS.init, CMS.createClass) and leave the createElement on the React global. 

@erquhart  Any objections?

Esentially, we would have:
```
  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/netlify-cms@latest/dist/netlify-cms-manual-init.js"></script>
  <script>
    var h = React.createElement;
    var createClass = CMS.createClass;
    CMS.init();
  </script>
```

**Comment by erquhart** [comment] 2019-02-19 16:03
So here's my concern: even once Netlify CMS is (eventually) completely decoupled from the SPA distribution package (with the current routing, auto bootstrap, etc), that SPA distro will still be the one most folks use. We need to support React Hooks in a way that can be used in SPA distro, otherwise we're going to end up with a fragmented ecosystem where folks find a widget they want to use, but it's incompatible with their CMS unless they go modular.

Thoughts?

**Comment by talves** [comment] 2019-02-19 17:39
Currently no-one can really create an external library (widget, preview, etc) without a duplicate React instance unless they use the `createClass` global.
Using a global class from a script without using externals will break if someone tries to use hooks in their library and tries to register it into the SPA.

I have spent quite a bit of time on this issue and the only way I can think of doing this is the way I have outlined.

My # PR will not solve this issue, so I am going to close it. It would require a new library bundle and I did not have luck getting it to work inside the monorepo.

**Comment by erquhart** [comment] 2019-02-19 20:48
Gotcha - thanks for your effort on this. It will remain a general priority, as shared dependencies are a blocker for a real ecosystem (community widgets, etc).

**Comment by talves** [comment] 2019-03-06 21:30
The first step solution is now in PR #2141 and will allow us to have a module bundle that has React and ReactDOM as external peer dependencies.

We will be able to close this issue once that module library is available.

**Comment by talves** [comment] 2019-03-27 23:14
Now we will be able to patch the gatsby-plugin-netlify-cms with #2252

Will resolve any issue with using React Hooks in NetlifyCMS for Gatsby and any other custom build solution for that matter.

**Comment by leifriksheim** [comment] 2019-04-15 17:48
@talves 
I still get this error when using Gatsby. I have updated both the netlify-cms package to the latest beta and the Gatsby plugin. Is this problem not resolved for Gatsby yet?

**Comment by talves** [comment] 2019-04-15 17:54
No, the new plugin is not released. They are reviewing it soon.

**Comment by buz-zard** [comment] 2019-05-07 08:13
Upgraded to `netlify-cms-app@2.9.1` from `netlify-cms@
2.8.1-beta.1` in my gatsby app, getting some console errors on the edit fields
![image](https://user-images.githubusercontent.com/3521740/57283915-d7e65280-70b8-11e9-8dc9-47e76d2059dc.png)
but nonetheless the update was seamless and hooks are working, thx for the work!

**Comment by talves** [comment] 2019-05-07 13:56
@buz-zard that is a known warning. Thanks.

[`gatsby-plugin-netlify-cms@4.0.0`][1] merged, closing this. See [README][2] for update.

Please create a new issue if you find a problem.

[1]: https://github.com/gatsbyjs/gatsby/pull/13036
[2]: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/README.md

**Closed by talves** 2019-05-07 13:56 UTC
Labels: priority: high
