### ISSUE TITLE
Ability to reorder items in a collection

### ISSUE THREAD

**Issue by markjohnson4** [netlify/netlify-cms#5469] opened 2021-06-02 20:48 UTC
It would be nice to be able to drag/drop collection items in order to re-order them.  I imagine defining somewhere the meta field name that relates to a collection item's order (for Hugo the field name is "weight").  And then that field would get updated for all items in a collection whenever an item is dragged/dropped somewhere on the CMS side.

Thanks in advance for considering this!

**Comment by erezrokah** [comment] 2021-06-02 20:53
Hi @markjohnson4, closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/475.

Please comment if you feel your use case is different.

**Closed by erezrokah** 2021-06-02 20:53 UTC
Labels: type: feature
