### ISSUE TITLE
Jekyll Collections not sorting by date

### ISSUE THREAD

**Issue by shushugah** [netlify/netlify-cms#5198] opened 2021-04-01 19:00 UTC
**Describe the bug**
In both the default and manually specified `sortable_fields: ['fields.date']`, the collection (events) is sorted by their file name and not their front matter date. This is the [repository](https://github.com/techworkersco/twc-site-berlin/blob/develop/admin/config.yml) https://github.com/techworkersco/twc-site-berlin, and the [admin-configs](https://github.com/techworkersco/twc-site-berlin/blob/develop/admin/config.yml)

<img width="204" alt="Screenshot 2021-04-01 at 15 02 04" src="https://user-images.githubusercontent.com/7111514/113341110-0f092100-932d-11eb-9326-0d76010ad14f.png">
<img width="245" alt="Screenshot 2021-04-01 at 15 09 39" src="https://user-images.githubusercontent.com/7111514/113341113-0fa1b780-932d-11eb-9924-ee95be8d0506.png">

In either situation, the files "sorted" by date, show collection of events 1.md, 10.md, 11.md, 2.md, 21.md etc.. 

**Expected behavior**
I'd expect that the date column is used to sort the files

**Comment by erezrokah** [comment] 2021-04-04 07:29
Hi @shushugah I believe this is a duplicate of https://github.com/netlify/netlify-cms/issues/4637.

You should use ISO format for the dates in order for the sort to treat them as dates and not strings (until that issue is resolved).
See https://raw.githubusercontent.com/netlify/netlify-cms/master/website/content/blog/netlify-cms-2-4-0.md

Closing, please comment if you have additional questions

**Closed by erezrokah** 2021-04-04 07:29 UTC
Labels: area: ui/collection, type: bug
