### ISSUE TITLE
Show diff of content changes to reviewer

### ISSUE THREAD

**Issue by theetrain** [netlify/netlify-cms#3576] opened 2020-04-10 17:55 UTC
Thank you for maintaining NetflifyCMS. It's a great product and I hope to make extended use of it over time. ⭐ 

**Is your feature request related to a problem? Please describe.**

When using editorial flow to propose content changes, the reviewer would like to easily see what has changed.

**Describe the solution you'd like**

When selecting a change in the Editorial flow, it would be convenient to show an optional diff view of the changes, to help the reviewer easily identify what has changed. Maybe a 'Highlight changes' button next to 'View preview' that toggles a content diff would help.

**Describe alternatives you've considered**

The current workaround is to view the changes in the corresponding pull request, or have authors explicitly communicate what has changed. The problem with this is it leads to additional effort for the author.

**Additional context**

NetlifyCMS v2.10.42
Config: GitLab backend with Editorial flow enabled

**Comment by tomrutgers** [comment] 2020-04-10 21:39
Thanks for addressing this, it would indeed be a valuable feature. I’m closing this as it’s a duplicate of #2735, please upvote and comment there.

**Closed by tomrutgers** 2020-04-10 21:39 UTC
