### ISSUE TITLE
netlify-cms-app@2.12.5 regression: datetime widget value is being written as string

### ISSUE THREAD

**Issue by smashercosmo** [netlify/netlify-cms#3567] opened 2020-04-09 09:16 UTC
**Describe the bug**
datetime widget value is being written as string: 

```md
---
title: test
description: test
date: "2020-04-08T09:03:16.371Z"
draft: true
---
test
```

as a result I get
```
TypeError: (date || (intermediate value)).toISOString is not a function
```

**To Reproduce**
Just use datetime widget with netlify-cms-app@2.12.5

**Expected behavior**
datetime widget value should be written as date: 
```md
---
title: test
description: test
date: 2020-04-08T09:03:16.371Z
draft: true
---
test
```

**Applicable Versions:**
 - Netlify CMS version: 2.12.5 (2.12.4 works fine)

**Comment by erezrokah** [comment] 2020-04-09 09:50
Duplicate of https://github.com/netlify/netlify-cms/issues/3568. Thanks for repording

**Comment by erezrokah** [comment] 2020-04-09 10:07
Actually just realised you opened the issue first

**Closed** 2020-04-09 11:17 UTC

**Comment by erezrokah** [comment] 2020-04-09 15:01
This is now released with `netlify-cms@2.10.42`

**Comment by Saswat689** [comment] 2023-07-28 06:47
how to fix it ??

**Comment by Saswat689** [comment] 2023-07-28 06:47
@erezrokah Still stuck on the issue. I am using netlify cms(cdn v1 as in docs). It returns a string datetime
