### ISSUE TITLE
Next.JS Starter Template is Not Allowing for An Admin Invite 

### ISSUE THREAD

**Issue by bigcurry** [netlify/netlify-cms#4739] opened 2020-12-19 22:29 UTC
**Describe the bug**
When creating a new Next.JS blog from the starter template, the admin email does not actually have an admin registration modal pop up. 

**To Reproduce**

**Expected behavior**
I tried this out with Gatsby and it works 

I believe this is a bug, I am still new to Netlify so please excuse me if this is inappropriate.

**Comment by erezrokah** [comment] 2020-12-20 09:18
Hi @bigcurry, this seems like a duplicate of https://github.com/wutali/nextjs-netlify-blog-template/issues/13
I'm closing this issue in favor of that one.

**Closed by erezrokah** 2020-12-20 09:18 UTC
Labels: type: bug

**Comment by tengkuzulfadli** [comment] 2021-08-31 00:56
I have the same issue with Nextjs-Netlify Blog template
