### ISSUE TITLE
Error: The GitLab backend does not support the Editorial Workflow.

### ISSUE THREAD

**Issue by ediano** [netlify/netlify-cms#2003] opened 2019-01-13 21:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment] 2019-01-14 07:14
The editorial workflow is not yet available for GitLab 

Duplicate of #568

There’s a PR on the way: #1817

**Closed by tomrutgers** 2019-01-14 07:14 UTC

**Comment by johnhashim** [comment] 2019-03-05 03:02
hey, so what is available right now?

**Comment by talves** [comment] 2019-03-05 03:11
@johnhashim Editorial Workflow is available for Github.
