### ISSUE TITLE
Date widget inside list widget not showing default date value

### ISSUE THREAD

**Issue by thebetternewt** [netlify/netlify-cms#1117] opened 2018-02-18 19:09 UTC
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

I have a list widget with each item containing multiple date fields. However, all date fields other than the last field are initially blank instead of showing the default value (the current date in this case). I am using CMS version 1.2.0 according to my browser console.

Here is a link to my config.yml:

[config.yml](https://github.com/thebetternewt/loveleerolls_victor_hugo/blob/master/site/static/admin/config.yml)

**Comment by louMoxy** [comment] 2018-03-24 15:56
Hi @thebetternewt 
I have just tried to replicate the problem, but I don't see any issues. All the dates are displaying as expected. Are you still having issues?

**Comment by erquhart** [comment] 2018-03-27 21:43
This seems to be fixed in 1.3.5, not sure where the fix actually occurred. Please comment if you're still able to reproduce.

**Comment by thebetternewt** [comment] 2018-03-28 02:00
Hi. Sorry for the delayed response. Yes I thought this issue was already confirmed and fixed. I did not realize the issue was still open. It has been working for a while now. Thanks your your help!

**Comment by tech4him1** [comment] 2018-04-16 22:49
I can still reproduce this using the original config:

```yaml
collections:
  - label: "Settings"
    name: "Settings"
    files:
      - name: "date_settings"
        label: "Date Settings"
        file: "data/date_settings.json"
        description: "Set blackout dates"
        fields:
          - label: "Blackout Dates"
            name: "blackout_dates"
            widget: "list"
            fields:
              - {label: "Note", name: "note", widget: "string"}
              - {label: "Start Date", name: "start_date", widget: "date"}
              - {label: "End Date", name: "end_date", widget: "date"}
```

**Comment by tech4him1** [comment] 2018-04-17 01:39
When a new list item is created, the Date widget calls `onChange` to set its default.

The nested default is set using this code:
https://github.com/netlify/netlify-cms/blob/1a3454f244b1e1a190f24fe2acfb9b1583446bc6/src/components/EditorWidgets/List/ListControl.js#L163

For some reason, when the list is first being created, `getObjectValue` returns an empty Map on every call. Therefore, when there are multiple widgets in the list item, only the last one will have remain (1 will overwrite 2, 2 will overwrite 3, etc.).

**Comment by barthc** [comment] 2018-12-12 11:01
@erquhart  ping!!!

**Comment by erquhart** [comment] 2018-12-17 18:46
@barthc sorry about that, yes!

**Closed by erquhart** 2018-12-17 18:46 UTC
Labels: area: extensions/widgets, good first issue, kind: bug, status: confirmed
