### ISSUE TITLE
TypeError: Can't set option year when dateStyle is used

### ISSUE THREAD

**Issue by Anas-Aqeel** [netlify/netlify-cms#4809] opened 2021-01-06 19:08 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.10`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
media_folder: content/assets
public_folder: ../assets
collections:
  - name: social
    label: Social
    editor:
      preview: false
    files:
      - label: Social links
        name: social
        file: content/social/social.md
        fields:
          - label: Type
            name: type
            widget: hidden
            default: social
          - label: Twitter
            name: twitter
            widget: string
            default: ""
            required: false
            hint: Full link to your Twitter profile
            pattern:
              - ^http(s)?://.*..*(/)?
              - Must be a valid URL
          - label: Facebook
            name: facebook
            widget: string
            default: ""
            required: false
            hint: Full link to your Facebook page
            pattern:
              - ^http(s)?://.*..*(/)?
              - Must be a valid URL
          - label: LinkedIn
            name: linkedin
            widget: string
            default: ""
            required: false
            hint: Full link to LinkedIn profile
            pattern:
              - ^http(s)?://.*..*(/)?
              - Must be a valid URL
          - label: Email
            name: email
            widget: string
            default: ""
            required: false
            hint: Just your email address
    publish: true
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
    view_groups: []
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: posts
    slug: "{{slug}}"
    folder: content/posts
    view_groups: []
    publish: true
    label: Text post
    fields:
      - label: Type
        name: type
        widget: hidden
        default: text
      - label: Featured Image
        name: image
        widget: image
        required: false
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: DD MMM, YYYY
        date_format: DD MMM, YYYY
      - label: Post
        name: body
        widget: markdown
    create: true
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: videos
    slug: "{{slug}}"
    folder: content/videos
    view_groups: []
    publish: true
    label: Video post
    fields:
      - label: Type
        name: type
        widget: hidden
        default: video
      - label: Featured image
        name: image
        widget: image
        required: false
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Publish date
        name: date
        widget: datetime
        dateFormat: DD MMM, YYYY
        timeFormat: false
        date_format: DD MMM, YYYY
        time_format: false
      - label: Link to video
        name: link
        widget: string
        pattern:
          - ^http(s)?://.*..*(/)?
          - Must be a valid URL
    create: true
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: audio
    slug: "{{slug}}"
    folder: content/audio
    view_groups: []
    publish: true
    label: Audi
...

**Comment by erezrokah** [comment] 2021-01-07 10:48
Hi @Anas-Aqeel can you please follow the [issue template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title)?

**Comment by Anas-Aqeel** [comment] 2021-01-07 21:06
What info is more required?

**Comment by Anas-Aqeel** [comment] 2021-01-07 21:06
Can you tell me?

**Comment by Anas-Aqeel** [comment] 2021-01-07 21:07
![Uploading image.png…]()

**Comment by talves** [comment] 2021-01-07 22:10
@Anas-Aqeel There needs to be a more detailed summary of what "Can't set option year when dateStyle is used" defines. Leaving all the form questions blank requires someone who will take this task on to guess what the issue is.

Describe the bug (what error was printed to console or screen if any)

To Reproduce (maybe a simple example to show how to reproduce the bug error)

Expected behavior (what exactly was the output expected if not obvious)

Screenshots (Screenshots, if pertinent to the error would be helpful, but not always required)

**Comment by haris-aqeel** [comment] 2021-01-08 05:31
Everything working fine. When I change data in Netlify CMS. It is reflected in the gatsby project. The problem occurs when I am not able to see the data I am changing on netlify CMS preview wherever I used widget Date.
![Screenshot from 2021-01-08 10-26-52](https://user-images.githubusercontent.com/56465230/103978004-4cca3380-519c-11eb-9594-335d7b13ad51.png). FOr example See this image When I am filling the fields here on left side. Why my right side showing an error in Details
TypeError: Can't set option year when dateStyle is used

One more thing in the Pages node where I am not using date widget It is rightly displaying.
![Screenshot from 2021-01-08 10-31-06](https://user-images.githubusercontent.com/56465230/103978147-a5013580-519c-11eb-85b7-34c8eeadf6e4.png)

**Comment by erezrokah** [comment] 2021-01-08 10:42
Hi @haris-aqeel, thank you for the additional information.
Those kind of errors coming the the preview pane (the right pane) are usually caused by custom preview templates.
Can you share you repo or an example repo with this issue?

**Comment by erezrokah** [comment] 2021-02-02 11:22
Closing this issue pending more information

**Closed by erezrokah** 2021-02-02 11:22 UTC
Labels: status: more info needed
