### ISSUE TITLE
Cannot save changes (API_ERROR: Reference update failed - "UNPUBLISHED_ENTRY_PERSIST_FAILURE")

### ISSUE THREAD

**Issue by Petrolog-IT** [netlify/netlify-cms#2544] opened 2019-08-15 12:08 UTC
**Describe the bug**

I am getting an error when I try to save some changes in the CMS of a site deployed on Netlify.
The error I get when I make a change and click the Save button is this: `Failed to persist entry: API_ERROR: Reference update failed`

To use GitHub as the authentication method for the CMS (so that my GitHub user can login into the CMS), I followed [the instructions of the docs](https://www.netlifycms.org/docs/authentication-backends/#github-backend). The configuration can be seen here: https://github.com/Petrolog-IT/one-click-hugo-cms/blob/master/site/static/admin/config.yml

```yml
backend:
  name: github
  repo: Petrolog-IT/one-click-hugo-cms
  branch: master
```

As [the docs mentioned](https://www.netlify.com/docs/authentication-providers/#using-an-authentication-provider), I created an OAuth app on GitHub and added the Client ID and Secret in the appropriate settings page of Netlify:

![image](https://user-images.githubusercontent.com/25299057/63093294-def8e880-bf64-11e9-9359-914f99fbdf56.png)

I can login into the CMS of the site deployed on Netlify with the `Petrolog-IT` GitHub user successfully. I can also delete things from the CMS successfully. But I cannot save any changes.

**To Reproduce**

**Expected behavior**

Create a commit with the changes.

**Screenshots**

![image](https://user-images.githubusercontent.com/25299057/63093515-d81ea580-bf65-11e9-990d-e45be872f5ed.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: Ubuntu Xenial 16.04
 - Browser version Version 75.0.3770.142

 - Node.JS version:

**CMS configuration**

https://github.com/Petrolog-IT/one-click-hugo-cms/blob/master/site/static/admin/config.yml

**Additional context**

These related issues didn't help:
- https://github.com/netlify/netlify-cms/issues/2461
- https://github.com/netlify/netlify-cms/issues/1187#issuecomment-377320213
- https://github.com/netlify/netlify-cms/issues/1994

**Comment by erquhart** [comment] 2019-08-24 20:51
Forked your repo and was able to save changes to existing entries as well as create new ones :/

**Comment by Petrolog-IT** [comment] 2019-08-26 08:33
I also managed to do it through a different profile on GitHub, but for some reason it doesn't work with this account.

**Comment by robinsingh-bw** [comment] 2019-10-01 14:20
Having the same issue. I can save entries if i disable the editorial workflow though

**Comment by jimmyangel** [comment] 2019-12-20 04:15
I am seeing the same exact issue (i.e., UNPUBLISHED_ENTRY_PERSIST_FAILURE). It works with no editorial workflow, but it fails when I enable it.

I am using version 2.10.2-beta.0, but I tried with 2.0.0 and experienced the same problem.

Any clues?

**Comment by jimmyangel** [comment] 2019-12-20 22:11
Hi @erquhart, would you be able to point out the possible cause for this problem?

This only happens with editorial_workflow, which I need because I am storing images (and others files) relative to the content.

My repo: [https://github.com/jimmyangel/librorojoetv](https://github.com/jimmyangel/librorojoetv)

Any help is greatly appreciated!

**Comment by erezrokah** [comment] 2019-12-22 11:27
@Petrolog-IT I can't access the repo in the issue (is it private/deleted?). Also can you share your network traffic?

@jimmyangel Thank you for sharing the repo, do you mind sharing network traffic while getting the error?

**Comment by jimmyangel** [comment] 2019-12-22 22:04
Hi @erezrokah, here are the har capture and the console log:

[prototipo-librorojoetv.netlify.com.har.txt](https://github.com/netlify/netlify-cms/files/3993045/prototipo-librorojoetv.netlify.com.har.txt)
[prototipo-librorojoetv.netlify.com-1577052063765.log](https://github.com/netlify/netlify-cms/files/3993046/prototipo-librorojoetv.netlify.com-1577052063765.log)

Thank you very much for your time!

Ricardo

**Comment by barthc** [comment] 2019-12-22 23:15
@erezrokah  looks like the github api can't create a ref like so `refs/heads/cms/home/home` the first home is the collection name and the second one is the slug

**Comment by erezrokah** [comment] 2019-12-23 10:05
This is solved by deleting the `cms` branch from the repo. I remeber it from a previous issue. I'll check why having a branch with that name breaks editorial workflow

**Comment by barthc** [comment] 2019-12-23 10:12
I tried creating a  workflow branch that has collection name and slug the same, and got the same error. For example, collection like so:
```
collections:
  - name: 'posts' 
    slug: '{{slug}}'
```
If I type `posts` on the identifier field so the slug matches the collection name, the error shows.

**Comment by erezrokah** [comment] 2019-12-23 10:13
Let me check again as I tried the same thing and it worked

**Comment by barthc** [comment] 2019-12-23 10:29
Yup, you are right it's a branch issue. I don't have a branch ` cms/posts/posts`  but I have branches like `cms/posts/posts/some-other-string`

**Comment by erezrokah** [comment] 2019-12-23 11:41
This is a git restriction when creating branches.
You can easily reproduce locally by doing:

```bash
git branch cms
git branch cms/foo
```

In order to prevent such cases in the future we will need to change our branch naming scheme, possibly as a part of https://github.com/netlify/netlify-cms/issues/1669

Closing this, @Petrolog-IT please re-open with a link to the repo+network traffic if issue persists.
@robinsingh-bw, @jimmyangel please comment if the workaround of deleting the `cms` branch doesn't work for you

**Closed by erezrokah** 2019-12-23 11:41 UTC

**Comment by tomrutgers** [comment] 2019-12-23 11:51
I added this to the list of API_ERROR solutions and workarounds: https://github.com/netlify/netlify-cms/issues/2827

**Comment by jimmyangel** [comment] 2019-12-23 18:35
Hi @erezrokah, I deleted the cms branch and it is working like a charm!

You guys are awesome! Thank you very much for your help.

Happy holidays!
