### ISSUE TITLE
Failed to load config.yml

### ISSUE THREAD

**Issue by sofievergauwe** [netlify/netlify-cms#683] opened 2017-10-12 14:28 UTC
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The backend is looking for the config file in the site root "/" instead the "admin/" folder
Working fine when I move config from "/admin/config.yml" to "/config.yml"

Error:

```
The config.yml file could not be loaded or failed to parse properly.
Error message: Error: Failed to load config.yml (404)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
Surf to /admin on a new site

**- What is the expected behavior?**
Config should be loaded from "/admin/config.yml"

**Comment by tech4him1** [comment] 2017-10-12 15:49
@sofievergauwe Thank you for reporting this issue, but it is a duplicate of #332. You should be able to access the CMS correctly by going to `/admin/` (with the trailing slash in the URL).

**Closed by tech4him1** 2017-10-12 15:49 UTC
