### ISSUE TITLE
Nested validation failing silently

### ISSUE THREAD

**Issue by axelboc** [netlify/netlify-cms#2320] opened 2019-05-08 16:16 UTC
**Describe the bug**
After upgrading Netlify CMS, I'm no longer able to publish or save changes. When I hit the _Publish Now_ button (or the _Save_ button when the editorial workflow is enabled), nothing happens; there's no progress bar at the top and the content is not published/saved. The following error appears in the console:

```
Uncaught (in promise) undefined
  (anonymous) @ netlify-cms-app.js:227
  async function (async)
  (anonymous) @ netlify-cms-app.js:227
  (anonymous) @ netlify-cms-app.js:227
  onSelection @ netlify-cms-app.js:59
  (anonymous) @ netlify-cms-app.js:180
  o.selectItem @ netlify-cms-app.js:180
  (anonymous) @ react-dom.production.min.js:14
  d @ react-dom.production.min.js:15
  [... some more calls in react-dom here]
```

I was able to narrow down the version of Netlify CMS that introduced the regression: [v2.4](https://github.com/netlify/netlify-cms/compare/netlify-cms@2.3.3...netlify-cms@2.4.0). The problem is still present in v2.9.1.

**Applicable Versions:**
 - Netlify CMS version: **2.4.2**
 - Git provider: **git-gateway** (GitHub)
 - OS: Windows 10
 - Browser version: Firefox 66, Chrome 74

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: "https://..."

collections:
  - name: "pages"
    label: "Pages"
    files:
      - ...
      - ...
```

My config only has a single `files` collection, so the problem occurs when editing individual "pages". I've tried setting the following config options without success:

- `publish-mode: editorial_workflow`
- `show_preview_links: false`

**Additional context**
Thinking it was a permission issue with GitHub, I re-linked my repository in Netlify and requested a new access token for Netlify Identity, but the problem remained.

**Comment by erquhart** [comment] 2019-05-09 19:43
Still an issue? Hard to know where to trace this without being able to reproduce.

**Comment by axelboc** [comment] 2019-05-09 22:28
Phew ... so after a good 2 hours of debugging, it turns out that one of the entries of a list widget on the page I was trying to edit had a validation error. The value of one of the entry's fields (a `string` field) did not match the regex pattern specified in the config. The entries in the list were collapsed, so the validation error was not visible...

No idea why this validation error was not preventing me from publishing in v2.3 and below... However, I've narrowed down the line that triggers the "unknown" promise rejection since v2.4: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/actions/entries.js#L475

The validation error should probably be passed to the promise rejection so the error message in the console is clearer. I also find it weird that the validation error didn't appear more prominently on the page. A big red piece of text next to the publish button would be really helpful!

**Comment by erquhart** [comment] 2019-05-10 14:24
It's because nested field validation was not working prior to 2.4, fixed here: https://github.com/netlify/netlify-cms/pull/1873

You're definitely right, the failure should have resulted in a message up top. If you're up for submitting a PR to improve any aspect of what you experienced, please do!

cc/ @barthc in case you have any insights

**Comment by barthc** [comment] 2019-05-27 14:34
@erquhart  Yes, we need to show popup for validation error type ` PATTERN`. We may also need to include the  `RANGE` and `CUSTOM` error type while we are at it.

**Comment by erezrokah** [comment] 2020-07-07 13:16
Is this still relevant? With https://github.com/netlify/netlify-cms/pull/3726 merged we should proper errors for nested and list fields.

**Comment by erezrokah** [comment] 2020-07-09 12:39
Closing, please comment if still relevant

**Closed by erezrokah** 2020-07-09 12:39 UTC
Labels: area: ui/editor, area: validation, kind: bug, pinned
