### ISSUE TITLE
In admin => when overwriting images => don't pull preview from 'master' branch

### ISSUE THREAD

**Issue by alexboots** [netlify/netlify-cms#2772] opened 2019-10-21 14:08 UTC
**Is your feature request related to a problem? Please describe.**

In admin, when a user updates a graphic by overwriting it, the graphic on the preview to the right references the 'master' branch so it doesn't visually change until master has published. The thumbnail in the editor to the left references github, so that one displays correctly. 

This caused confusion for some admins as I guess their workflow involves updating graphics with the same name by overwriting them. Not seeing the update to the right immediately makes them reach out and think something is wrong. 

I replicated it to see what was going on and realized the preview graphic is still referencing master. 

**Describe the solution you'd like**

The same logic for uploading new graphics should be applied to overwriting graphics so the preview doesn't pull from an outdated graphic on master branch.  (I'm ignorant of the codebase so take that as involving a lot of presumptions about how things work). 

**Describe alternatives you've considered**

Tell people to chill out and wait a bit as it only takes like 5 mins to update :P

**Comment by tomrutgers** [comment] 2019-10-21 16:05
Closing this as a duplicate of #2516

**Closed by tomrutgers** 2019-10-21 16:05 UTC
