### ISSUE TITLE
Can i run Netlify CMS while not using Netlify?

### ISSUE THREAD

**Issue by wouter-muller** [netlify/netlify-cms#2774] opened 2019-10-22 14:24 UTC
For a client, i am developing a website and they want to run the website on their own servers. Is it possible to use Netlify CMS while not using Netlify hosting? 

I tried doing this and when i try to access the Netlify CMS admin interface (the `/admin/` one), it says "Failed to load settings from /.netlify/identity".

**Comment by erezrokah** [comment] 2019-10-22 15:51
Hi @wouter-muller and thank you opening this issue.
Do you mind transferring your comment to this [issue](https://github.com/netlify/netlify-cms/issues/2695) as they seem related.
I think my comment there might help with your question.

**Comment by erezrokah** [comment] 2019-10-24 05:43
@wouter-muller I'm closing this as a duplicate of #2695, please comment on the original issue or re-open if you think it is necessary

**Closed by erezrokah** 2019-10-24 05:43 UTC
