### ISSUE TITLE
[feature request] Pagination inside the CMS

### ISSUE THREAD

**Issue by gedeondt** [netlify/netlify-cms#1362] opened 2018-05-16 18:27 UTC
When working with big amounts of documents for a document type it seems that all of them are listed at once inside the CMS. I have tested a site with 10.000 posts and all of them were listed with no pagination on the CMS.

Thanks

**Comment by tech4him1** [comment] 2018-05-17 13:51
@Benaiah will your pagination work for GitLab affect GitHub as well?

**Comment by erezrokah** [comment] 2020-03-04 14:34
Closing as duplicate of https://github.com/netlify/netlify-cms/issues/50

**Closed by erezrokah** 2020-03-04 14:34 UTC
