### ISSUE TITLE
[bug] Cannot upload or view image in media assets

### ISSUE THREAD

**Issue by caelialuk** [netlify/netlify-cms#1454] opened 2018-06-20 03:54 UTC
**- Do you want to request a *feature* or report a *bug*?** 
bug

**- What is the current behavior?**

Images not uploading to media assets
![screen shot 2018-06-19 at 11 45 41 pm](https://user-images.githubusercontent.com/24300124/41636193-fd791708-741a-11e8-85ab-fdbb6fac83ba.png)

and image links are broken 
![screen shot 2018-06-19 at 11 53 06 pm](https://user-images.githubusercontent.com/24300124/41636366-ff6efde2-741b-11e8-9163-5af3c7f2f17d.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
created a site using hugo site starter with gitlab as backend
unable to upload images and view them 

**- What is the expected behavior?**

Images can be uploaded and image links are not broken 

Netlify CMS version: 1.9.2
Browser version: Chrome 67

**- Please link or paste your `config.yml` below if applicable.**

media_folder: "site/static/img"

**Comment by tech4him1** [comment] 2018-06-20 14:29
This looks like a duplicate of https://github.com/netlify/netlify-cms/issues/1436, can you confirm?

**Comment by caelialuk** [comment] 2018-06-21 04:54
Yes! Thank you, the thumbnail is a duplicate of #1436. But how do I implement solution #1433 (gitlab api) to my current project?

**Comment by erquhart** [comment] 2018-06-26 20:13
@caelialuk we'll be getting that merged and released soon.

**Comment by tech4him1** [comment] 2018-06-27 03:28
Sorry for the delay on this -- I just confirmed uploading is broken on the `git-gateway` backend with GitLab, but not when using the GitLab backend directly. @Benaiah any thoughts?

**Comment by idiazroncero** [comment] 2018-07-23 11:05
+1 here on a fresh install of netlifycms official gatsby starter based on gitlab... can we know if this is going to be fixed soon? Thanks!

**Comment by pojntfx** [comment] 2018-07-29 17:43
+1 here as well. See [my GitLab repo](https://gitlab.com/pojntfx/ergotherapie-ssl-website) for the exact site where it appears.

**Comment by tech4him1** [comment] 2018-08-01 14:25
Splitting this out into two separate issues:
- #1436 for viewing media.
- #1565 for uploading.

**Closed by tech4him1** 2018-08-01 14:25 UTC
Labels: area: extensions/backends, area: media-library, kind: bug

**Comment by piedoom** [comment] 2018-08-06 14:11
Hi, I'm still experiencing this issue despite it being marked closed.  Anyone else having issues?

**Comment by estherholleman** [comment] 2018-08-06 14:53
It is also still not working for me. It builds fine, but when I try to change or upload an image I still get 'no assets found' even with a fresh install of the official Gatsby starter with GitLab and after updating gatsby-plugin-netlify-cms to version ^1.0.12, gatsby-plugin-netlify to ^1.0.21, and netlify-cms" to "^1.9.3. Is there perhaps anything else I should be updating or something I'm forgetting?

**Comment by estherholleman** [comment] 2018-08-06 16:14
I found out so far that the newest version of netlify-cms is 2.08, however the gatsby plugin is setting the netlify-cms version so it needs to be overriden with 'resolutions' in the package.json file. I attempted this following the instructions here (https://www.npmjs.com/package/npm-force-resolutions), which included removing the node-modules folder, running npm-force-resolutions, and then npm install. This seemed to work for the gatsby-plugin-netlify-cms, but not for netlify-cms, which, even after I manually install it again with 'npm install --save netlify-cms' after the whole force-resolutions thing, cannot be found anymore/is empty when I run 'npm ls netlify-cms' (even though it appears in the node-modules folder).

**Comment by piedoom** [comment] 2018-08-06 18:50
let me know if I can help test anything on my end!

**Comment by tech4him1** [comment] 2018-08-06 20:29
@piedoom @estherholleman See [my last comment above](https://github.com/netlify/netlify-cms/issues/1454#issuecomment-409593808) -- fixes are still in progress, it has just been split into two different issues.

**Comment by tech4him1** [comment] 2018-08-06 23:34
@piedoom Yes please. Also, make sure you are on the latest version of the CMS (v2.0.8) -- there were a lot of recent bug fixes.
