### ISSUE TITLE
Text-editor in NetlifyCMS admin dashboard cannot type any Chinese characters normally

### ISSUE THREAD

**Issue by dev-techmoe** [netlify/netlify-cms#4837] opened 2021-01-11 14:15 UTC
**Describe the bug**

Any Chinese words cannot be typed into the BODY editor (see GIF below)
 
**To Reproduce**

1. Go to admin dashboard (`<site_url>/admin`)
2. Click on "New Blog"
3. Scroll down to the "BODY" editor area and type some Chinese words with default Chinese IME in Win10 (Microsoft Pinyin)

**Expected behavior**
see below

**Screenshots**

![image](https://aws1.discourse-cdn.com/netlify/original/3X/1/b/1bde4c18f3d0bfc7314ee8a9b8289659324743d6.gif)

**Applicable Versions:**

 - Netlify CMS version: `netlify-cms-app 2.12.19`
 - Git provider: Github
 - OS: Win10
 - Browser version Chrome 87.0.4280.141

(My site was generated by the "Deploy to Netlify" Button in [here](https://www.netlifycms.org/docs/start-with-a-template/), I'm using Gatsby template)

**CMS configuration**

all using default config

**Comment by xianbinKit** [comment] 2021-01-16 01:23
the same here

**Comment by MannyCooper** [comment] 2021-01-28 18:14
Really love netlify-cms, please fix this bug soon if possible. This seems to only appear in the BODY editor.

**Comment by erezrokah** [comment] 2021-01-28 18:22
Hi all 👋  We would love a contribution for this issue.

**Comment by banyudu** [comment] 2021-02-20 06:28
Can't reproduce in macOS. Have tried Baidu Wubi, Baidu Pinyin, Sogou Wubi, Sogou Pinyin, and the JianTi Pinyin IME comes with macOS.

**Comment by inajob** [comment] 2021-03-13 19:20
Same error in Japanese IME on Windows 10.

**Comment by kenchon** [comment] 2021-05-16 17:06
Same bug in following environment:
❌
- Lang: Japanese
- OS: iOS 14.4.2
- Browser: Safari/Chrome

But it works well in OSX:
✅
- Lang: Japanese
- OS: OSX Big Sur
- Browser: Chrome

**Comment by kenchon** [comment] 2021-05-17 14:46
I found similar issue #4539 and this PR #4607 solved this.

**Comment by kenchon** [comment] 2021-05-19 09:16
I'm not sure I'm looking properly, netlify-cms's markdown editor uses [`slate-react`](https://github.com/ianstormtaylor/slate) [here](https://github.com/netlify/netlify-cms/blob/10327d6ede26e279ef6b4432beddc0d533740def/packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js#L127).
In `slate-react` project, [IME related bugs are reported](https://github.com/ianstormtaylor/slate/issues?q=is%3Aopen+label%3Abug+IME) and I think ours are one of them.

[netlify-cms-widget-markdown](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-widget-markdown) uses [`"slate-react": "^0.22.0"`](https://github.com/netlify/netlify-cms/blob/10327d6ede26e279ef6b4432beddc0d533740def/packages/netlify-cms-widget-markdown/package.json#L35) and latest is `0.63.0`.
Updating `slate-react` may solve some of the issues we found ?😂

**Comment by kenchon** [comment] 2021-05-19 16:15
[Here](https://github.com/ianstormtaylor/slate/issues/2368#issuecomment-545033238) describes the root cause of the IME problem, and `slate` maintainer says this was solved by this [PR](https://github.com/ianstormtaylor/slate/pull/3093).

Although there still remains some bugs in IME, updating `slate` should be the solution of this issue. The problem is updating `slate` requires many breaking changes ... 🤔

**Comment by erezrokah** [comment] 2021-07-28 10:54
Closing in favor of https://github.com/netlify/netlify-cms/issues/1347

**Closed by erezrokah** 2021-07-28 10:54 UTC
Labels: area: ui/editor, good first issue, type: bug
