### ISSUE TITLE
Broken password rest link

### ISSUE THREAD

**Issue by gimyboya** [netlify/netlify-cms#5109] opened 2021-03-14 08:11 UTC
**Describe the bug**
the URL sent for setting up the user for the first time or for resetting the password is broken

while the link looks like this in the email: `https://WHATEVER.netlify.app/#recovery_token=THE_TOKEN`

it should actually be: `https://WHATEVER.netlify.app/admin/#recovery_token=THE_TOKEN`

the `/admin` is missing.

**To Reproduce**
I just started a brand new Nuxtjs template and tried to set up a user for the first time and had to go to the identity tab in the dashboard to send a new reset password email again.

both were sending me an email with a broken URL.

this bug is also mentioned and solved [here](https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/30)

**Expected behavior**
the URL containing `/admin` before the token

**Applicable Versions:**

 - Netlify CMS version: 2.10.99
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version chrome  89.0.4389.82 (Official Build) (64-bit), firefox 86.0.1 (64-bit)

**CMS configuration**
didn't touch anything

**Additional context**
fresh new from the boilerplate

**Comment by erezrokah** [comment] 2021-03-14 10:28
Hi @gimyboya. This is not a bug with the CMS - by default Netlify Identity links point to the root path of your site.
If you'd like to change it you can follow the guide here https://answers.netlify.com/t/common-issue-netlify-cms-git-gateway-email-not-confirmed/10690 to update the email templates.

Closing the issue. Please comment if anything is unclear.

**Closed by erezrokah** 2021-03-14 10:28 UTC
Labels: type: bug

**Comment by gimyboya** [comment] 2021-03-15 08:48
Maybe I misunderstood you. but as I stated, this is a fresh setup and the email was sent from netlify, not myself (there is no email template involved), Alos for context I have linked an issue please find it [here](https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/30)

the idea is that a new user when I click the link I receive from netlify nothing happens and that's definitely a bug.

![image](https://user-images.githubusercontent.com/14952013/111126988-48f8ca00-85ae-11eb-9240-79736ba48650.png)

**Comment by erezrokah** [comment] 2021-03-15 10:01
Thanks for the added information @gimyboya.
I understand the email is coming from Netlify - the Netlify Identity service is the one sending those emails.
By default the identity service include links to the root path of your site (it doesn't know that you're using identity under `/admin`).

In order to make it work by default you need to include the Identity Widget under the root path of the site as described here https://github.com/netlify/netlify-identity-widget#usage

That's not a bug - this is how the service works - in order to handle the links you need the widget.

So you have 2 options:
1. Setup the Identity Widget as described here https://github.com/netlify/netlify-identity-widget#usage
2. Change the links to point to `/admin` as described here https://answers.netlify.com/t/common-issue-netlify-cms-git-gateway-email-not-confirmed/10690

**Comment by gimyboya** [comment] 2021-03-15 10:05
@erezrokah thank you for the elaboration. It's much clearer now. I hope that this issue might help others in the future. I somehow missed that part of the docs.
