### ISSUE TITLE
Customize plugins in markdown widget toolbar dropdown

### ISSUE THREAD

**Issue by sddaniels** [netlify/netlify-cms#2060] opened 2019-02-04 05:01 UTC
**Is your feature request related to a problem? Please describe.**
The `markdown` widget allows you to customize the buttons on the toolbar in the editor, but it does not allow you to remove any plugins that appear in the dropdown such as "Image". For example, if a developer is saying that only bold and italics are appropriate, it's unlikely that an embedded image would be appropriate either.

**Describe the solution you'd like**
There should be a way to define which plugins appear in a particular markdown editor's toolbar, similar to the way that was provided with buttons.

**Describe alternatives you've considered**
It might be enough to simply disable the dropdown entirely for certain widgets.

**Additional context**
![screen shot 2019-02-03 at 10 58 37 pm](https://user-images.githubusercontent.com/1263925/52190901-43ddc400-2807-11e9-8678-696547cd9038.png)

**Comment by erquhart** [comment] 2019-02-04 16:53
Man our docs _really_ need improved discoverability 😅

The [Editor Components API](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) does exactly this. Only components that you register will appear in the dropdown.

Unfortunately, the `Image` component can't be removed, the CMS currently depends on it, but that's definitely something we'd like to change.

**Comment by erquhart** [comment] 2019-02-05 20:03
Ah, I see what you mean - it'd be incredibly simple to do. Going to close this as a duplicate of #1788, but I'll add some labels over there to get better visibility for it.

**Closed by erquhart** 2019-02-05 20:03 UTC
