### ISSUE TITLE
Media section is not showing the images

### ISSUE THREAD

**Issue by mittalyashu** [netlify/netlify-cms#1619] opened 2018-08-15 14:44 UTC
**Describe the bug**

I have uploaded a few images in the `media_folder` and when I clicked on the `media` tabs and it didn't load any images.

**To Reproduce**

Steps to reproduce the behaviour:

1. Click on Media from the tabs
2. See the bug
3. It doesn't show the images 

**Expected behaviour**

It should show the images.

**Screenshots**

![image](https://user-images.githubusercontent.com/29014463/44154161-b861a4b2-a0c7-11e8-8343-eade7d9f07f7.png)

**Applicable Versions:**

 - Netlify CMS version: 2.0.9
 - Git provider: GitLab
 - OS: Windows 10
 - Browser version: 68.0.3440.106

**Comment by tech4him1** [comment] 2018-08-15 15:39
Duplicate of #1436. Thanks for reporting, though!

**Closed by tech4him1** 2018-08-15 15:39 UTC
