### ISSUE TITLE
Add an entry to the front of the list of a file collection

### ISSUE THREAD

**Issue by magomimmo** [netlify/netlify-cms#3953] opened 2020-06-28 08:34 UTC
**Is your feature request related to a problem? Please describe.**

When you're adding entries to a file collection by using the `Add something` button, the new entry is always added to the end of the list. After few entry additions to add a new entry you need to scroll all the way down to the end of the list and of you need to add a new one, you have scroll up again, click the `Add something` button and scroll all the way down again. This is not a fluid UX for the editor. 
 
**Describe the solution you'd like**

Add a new entry to the front of the list

**Describe alternatives you've considered**

No alternatives

**Comment by erezrokah** [comment] 2020-06-29 08:13
Closing this as duplicate of https://github.com/netlify/netlify-cms/issues/3270,
Please comment if not a duplicate.

**Closed by erezrokah** 2020-06-29 08:13 UTC
Labels: area: extensions/widgets, area: ux, duplicate, type: feature
