### ISSUE TITLE
TypeError: r.toJS is not a function

### ISSUE THREAD

**Issue by samwhiteiv** [netlify/netlify-cms#3788] opened 2020-05-20 06:12 UTC
**Describe the bug**
When loading up the view to create or edit an item from a collection, after a few seconds then the page goes to the error screen.

**To Reproduce**
Click on any collection and wait for the error after a few seconds.

**Expected behavior**
The page not to go to an error screen.

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.49`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  repo:
  accept_roles:
    - admin
    - editor
media_folder: static/uploads
public_folder: /uploads
collections:
  - name: page
    slug: "{{slug}}"
    folder: assets/content
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    label: Pages
    format: json
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
        required: false
        hint: Used when sharing only
      - label: Meta Description
        name: description
        widget: string
        required: false
      - label: Use sticky footer bar
        name: use-sticky-footer
        widget: boolean
        default: false
      - label: Sections
        name: sections
        widget: list
        required: false
        types:
          - label: Title and Body
            name: section-with-title
            widget: object
            fields:
              - label: ID
                name: id
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: markdown
              - label: Large Body style
                name: large-body
                widget: boolean
                default: false
              - label: Background color
                name: bg
                widget: select
                options:
                  - label: White
                    value: white
                  - label: Dark grey
                    value: dark-grey
                  - label: Black
                    value: black
                default: white
          - label: Image Text Block
            name: image-text-block
            widget: object
            fields:
              - label: ID
                name: id
                widget: string
              - label: "Image: Desktop"
                name: image-lg
                widget: image
              - label: "Image: Mobile"
                name: image-sm
                widget: image
              - label: Title
                name: title
                widget: string
                required: false
              - label: Title HTML
                name: title-html
                widget: string
                required: false
              - label: Body
                name: body
                widget: markdown
                required: false
              - label: Large Body style
                name: large-body
                widget: boolean
                default: false
              - label: Background color
                name: bg
                widget: select
                options:
                  - label: White
                    value: white
                  - label: Dark grey
                    value: dark-grey
                  - label: Black
                    value: black
                default: white
              - label: Layout
                name: layout
                widget: select
                options:
                  - label: Image Left
                    value: left
                  - label: Image Right
                    value: right
                  - label: Image Above
                    value: top
                  - label: Image Below
             
...

**Comment by erezrokah** [comment] 2020-05-20 08:17
Thanks @samwhiteiv, closing as duplicate of https://github.com/netlify/netlify-cms/issues/3787

**Closed by erezrokah** 2020-05-20 08:17 UTC
