### ISSUE TITLE
CMS crashes on Firefox ESR

### ISSUE THREAD

**Issue by agush22** [netlify/netlify-cms#959] opened 2017-12-22 04:25 UTC
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
CMS crashes after typing in the WYSIWYG editor in Firefox 52 ESR

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Log in to the CMS
- Create a new item or update an existing one on a collection
- Click on body field
- Type any key

**- What is the expected behavior?**
CMS should not crash

**- Please mention your CMS, node.js, and operating system version.**
Operating system: Arch Linux 4.13.12-1-ARCH
Browser: Firefox ESR  52.5.2 (64-bit)
CMS version: 1.0.3
Console Log:
```
Netlify CMS version 1.0.3  cms.js:1:675344

TypeError: r.setBaseAndExtent is not a function
Stack trace:
t/n.updateSelection@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:1605443
t/n.componentDidUpdate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:1604747
Et/T</<.commitLifeCycles@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:731153
t@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:717537
E@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722985
_@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722686
Et/<.batchedUpdates@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:732226
Z@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:693321
Se@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:697215
  cms.js:1:720745
	s https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:720745
	t https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:717947
	E https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722985
	_ https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722686
	Et/<.batchedUpdates https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:732226
	Z https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:693321
	Se https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:697215

TypeError: r.setBaseAndExtent is not a function
Stack trace:
t/n.updateSelection@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:1605443
t/n.componentDidUpdate@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:1604747
Et/T</<.commitLifeCycles@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:731153
t@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:717537
E@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722985
_@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722686
Et/<.batchedUpdates@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:732226
Z@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:693321
Se@https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:697215
  cms.js:1:502304
	ei</<.value https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:502304
	t https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:717731
	E https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722985
	_ https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:722686
	Et/<.batchedUpdates https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:732226
	Z https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:693321
	Se https://unpkg.com/netlify-cms@%5E1.0.0/dist/cms.js:1:697215
```

**Comment by erquhart** [comment] 2017-12-30 23:24
Thanks for reporting this @agush22. We definitely want to support LTS browsers, but we currently don't. There are almost certainly other issues beyond this one (just try doing anything in the live [demo site](https://cms-demo.netlify.com) in ESR). It may be as simple as transpiling more things, not certain. If you're up for digging in to the general FF ESR story a bit, we'll definitely support the effort.

@tech4him1 any chance this can be fixed through polyfills/transpiling? Can't recall where we left that with Babel.

**Comment by tech4him1** [comment] 2017-12-31 02:24
@erquhart I'll look into polyfills, but we are already transpiling for it right now (since https://github.com/netlify/netlify-cms/pull/765 hasn't been merged yet).

**Comment by tech4him1** [comment] 2018-01-03 02:44
@erquhart Adding the Babel polyfills didn't seem to fix the error (only delay it a small amount some times, by the error not throwing until you actually typed a character in the editor). 

I've pasted the full stacktrace for you below, since it seems to be in the editor code:

```
The above error occurred in the <Content> component:
    in Content (created by Editor)
    in Editor (created by RawEditor)
    in div (created by RawEditor)
    in RawEditor (created by MarkdownControl)
    in div (created by MarkdownControl)
    in MarkdownControl (created by Widget)
    in Widget (created by EditorControl)
    in div (created by EditorControl)
    in EditorControl (created by ControlPane)
    in div (created by ControlPane)
    in ControlPane (created by EditorInterface)
    in div (created by EditorInterface)
    in ScrollSyncPane (created by EditorInterface)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by EditorInterface)
    in div (created by EditorInterface)
    in ScrollSync (created by EditorInterface)
    in div (created by EditorInterface)
    in div (created by EditorInterface)
    in EditorInterface (created by Editor)
    in Editor (created by _class)
    in _class (created by Connect(_class))
    in Connect(_class) (created by Connect(Connect(_class)))
    in Connect(Connect(_class)) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by Root)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Root)
    in Provider (created by Root)
    in ErrorBoundary (created by Root)
    in Root

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by erquhart** [comment] 2018-01-03 21:20
@tech4him1 alright, thanks for checking.

**Comment by agush22** [comment] 2018-01-09 06:50
Thanks for the reply! Yeah LTS browser support would be good, but I understand it's not a priority.
At the moment I'm just sticking with Chrome instead

**Comment by w96k** [comment] 2018-08-21 17:38
Just want to confirm that this error still exists

**Comment by tech4him1** [comment] 2018-08-22 01:18
Can we confirm this is only Firefox ESR v52, not affecting ESR v60?

**Comment by tech4him1** [comment] 2018-09-04 22:14
I can no longer reproduce this with CMS v2.0.11. If anyone else can, please comment and we can re-open.

**Closed by tech4him1** 2018-09-04 22:14 UTC
Labels: area: browser-compatibility, area: extensions/widgets/markdown, kind: enhancement
