### ISSUE TITLE
TypeError: r.toJS is not a function

### ISSUE THREAD

**Issue by jeffrummel** [netlify/netlify-cms#3791] opened 2020-05-20 14:28 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.49`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
  repo: risingcampaigns/rc--ace-enough
  branch: production
logo_url: https://candidate.risingcampaigns.com/img/logo.svg
media_folder: img/uploads
public_folder: /img/uploads
collections:
  - name: homepage
    label: Homepage
    files:
      - file: src/site/content/homepage/marquee.md
        label: Marquee
        name: home_marq
        fields:
          - label: Title
            name: title
            widget: string
          - label: Featured Image
            name: thumbnail
            widget: image
          - label: Body
            name: body
            widget: markdown
      - file: src/site/content/homepage/supplemental.md
        label: Supplemental
        name: home_supp
        fields:
          - label: Supplemental Headline
            name: title
            widget: string
          - label: Supplemental Image
            name: sup__thumbnail
            widget: image
          - label: Supplemental Body
            name: body
            widget: markdown
          - label: Supplemental Link Text
            name: supCtaTxt
            widget: string
          - label: Supplemental Link URL
            name: supCtaUrl
            widget: string
      - file: src/site/_data/kickers.json
        name: kick
        label: Promotional Kickers
        fields:
          - label: Heading
            name: hed
            widget: string
          - label: Deck
            name: kick_dek
            widget: text
            required: false
          - label: Kickers
            name: kick
            widget: list
            fields:
              - label: Title
                name: kick_title
                widget: string
              - label: Deck
                name: kick_dek
                widget: text
                required: false
              - label: Kicker Image
                name: kick_img
                widget: image
              - label: link
                name: Link
                widget: object
                fields:
                  - label: Label
                    name: kick_label
                    default: Take Action
                    widget: string
                  - label: Path
                    name: kick_path
                    widget: string
                    required: false
                  - label: Link
                    name: kick_link
                    widget: relation
                    collection: pages
                    searchFields: title
                    valueField: title
                    displayFields: title
                    required: false
      - file: src/site/_data/donate.json
        label: Donation Amounts
        name: donation
        widget: list
        fields:
          - label: Donation Headline
            name: hed
            widget: string
          - label: Donation URL
            name: donateUrl
            widget: string
          - label: Dollar Amount
            name: usd
            widget: list
            fields:
              - label: Amount
                name: amount
                widget: number
          - label: Featured Image
            name: thumbnail
            widget: image
      - file: src/site/_data/contentOrderHome.json
        label: Content Order
        name: home_order
        fields:
          - label: First Content Block
            name: p_content_block
            widget: select
            options:
              - label: Platform
                value: platform
              - label: Supplemental
                value: supp
              - label: 
...

**Comment by erezrokah** [comment] 2020-05-20 14:34
Hi @jeffrummel, closing as duplicate of https://github.com/netlify/netlify-cms/issues/3787

**Closed by erezrokah** 2020-05-20 14:34 UTC
