### ISSUE TITLE
author-name/author-login should work outside of open authoring

### ISSUE THREAD

**Issue by djMax** [netlify/netlify-cms#3793] opened 2020-05-21 15:29 UTC
**Is your feature request related to a problem? Please describe.**
Right now, my commit messages have no information about who made a change, even though everyone is logging in to the CMS (with github accounts, for whatever that's worth). I tried to use {{author-name}} in the commit messages, but that doesn't work because the code explicitly stops it from doing so:

https://github.com/netlify/netlify-cms/blob/334304ed5262bfa10fec56fda1381bd27f096a49/packages/netlify-cms-core/src/lib/formatters.ts#L66

I assume there was a reason, but there should certainly be some way of getting identity information in the commit.

**Describe the solution you'd like**
Allow {{author-name}} and {{author-login}} to work regardless of openAuthoring.

**Describe alternatives you've considered**
In a perfect world, given OUR situation where we use github logins, I would love the commit itself to be from the editor. But I get that that's a much more complicated question and not generally useful to all situations.

**Comment by djMax** [comment] 2020-05-21 15:35
Minor update, it's not the if that's the problem, it's that author-name and author-login variables should perhaps be up higher.

**Comment by erezrokah** [comment] 2020-05-21 15:46
Thanks @djMax, this was done here https://github.com/netlify/netlify-cms/pull/2810 to resolve https://github.com/netlify/netlify-cms/issues/2809, since open authoring PRs have to be merged manually via GitHub by the repo maintainer (some added visibility was useful).

Just to confirm - the commits has the correct committer attached to them right? Just not as a part of the message?

**Comment by djMax** [comment] 2020-05-21 16:08
No, all my PRs are from a single account (mine), I assume because of this:

https://github.com/gas-buddy/docker-netlifycms-identity/blob/master/setup.sh#L51

Where I set a single access token for git-gateway. Should I be doing something different?

**Comment by erezrokah** [comment] 2020-05-21 16:16
The CMS should override the commit author with the email it gets from the Identity service:
https://github.com/netlify/netlify-cms/blob/d3aaf4ddb326efcaffdbcc5af5c0e5c8bcaa36ea/packages/netlify-cms-backend-git-gateway/src/GitHubAPI.ts#L100
If that email matches to a GitHub account it should show up in the commits (https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user).

I had a similar report from @jeremyzilar on slack.
I think there is a bug in that functionality - let me try and reproduce it.

**Comment by djMax** [comment] 2020-05-21 16:23
Ok great. I've got a custom build going here too, so if I can add debugging somewhere, please let me know

**Comment by djMax** [comment] 2020-05-21 16:25
Also, to confirm, when I put author-name and author-login in the original commit message substitution code, it does work. Not sure if that is useful outside of the issue with the commit author.

**Comment by erezrokah** [comment] 2020-05-21 16:45
You can submit a PR for that change if you'd like. It can help with having less confusion when using the templates.

**Closed** 2020-05-25 06:36 UTC
Labels: good first issue, type: feature
