### ISSUE TITLE
Media Manager Not Working

### ISSUE THREAD

**Issue by mskian** [netlify/netlify-cms#1615] opened 2018-08-14 16:32 UTC
Images not uploading - I found some errors on the console
also, it does not show the Preview and previously uploaded images
I am using **Gitlab** (Private Respo) & **Hugo** 
backend Method  - `git-gateway`

```
Uncaught (in promise) TypeError: Cannot read property 'find' of undefined
    at M (mediaLibrary.js:84)
    at index.js:9
    at bindActionCreators.js:3
    at ae (MediaLibrary.js:125)
    at Object.<anonymous> (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
    at C (react-dom.production.min.js:20)
    at N (react-dom.production.min.js:22)
    at I (react-dom.production.min.js:22)
```

Rest Features are Working fine

**Comment by tech4him1** [comment] 2018-08-14 17:32
This looks like a duplicate of #1608, let's discuss there. Thanks for reporting!

**Closed by tech4him1** 2018-08-14 17:32 UTC
