### ISSUE TITLE
New News Post - TypeError: a.get is not a function

### ISSUE THREAD

**Issue by ToniBonittoGSA** [netlify/netlify-cms#5230] opened 2021-04-09 00:07 UTC
When I click the New button, I get this error; the link created this Issue

<img width="587" alt="Screen Shot 2021-04-08 at 8 05 00 PM" src="https://user-images.githubusercontent.com/19961574/114110808-5e5bce00-98a6-11eb-8efd-7fb45934ade1.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.111`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

**CMS configuration**
```
site_url: https://digital.gov
logo_url: https://digital.gov/logos/digitalgov-logo.png
backend:
  name: github
  repo: GSA/digitalgov.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  use_graphql: true
  branch: main
  open_authoring: true
  squash_merges: true
publish_mode: editorial_workflow
local_backend:
  url: http://localhost:8081/api/v1
media_folder: /content/images/_inbox
slug:
  clean_accents: true
  encoding: unicode
  sanitize_replacement: "-"
defaults:
  editor:
    preview: false
  create: true
  delete: false
  publish: false
editorComponents:
  editorComponents:
    - accordion
    - assetImg
    - box
    - button
    - cardQuote
    - fbVideo
    - footnote
    - imgRight
    - img
    - instagram
    - legacyFile
    - legacyImgRight
    - legacyImg
    - note
    - ref
    - tweet
    - youtube
collections:
  - editor:
      preview: false
    create: true
    delete: false
    publish: false
    name: authors
    label: Authors
    label_singular: Author
    description: This page will help create a new author profile on Digital.gov
    folder: content/authors
    identifier_field: display_name
    path: "{{slug}}/_index"
    preview_path: authors/{{display_name}}
    fields:
      - label: Display Name
        name: display_name
        widget: string
        hint: How you prefer to be referred to.
      - label: First Name
        name: first_name
        widget: string
      - label: Last Name
        name: last_name
        widget: string
      - label: Pronoun
        name: pronoun
        widget: string
        hint: >
          List your pronoun(s) if you want them displayed alongside your name.
          If blank, we'll use just your name. Learn more http://mypronouns.org"
        comment: |-
          List your pronoun(s) if you want them displayed alongside your name.
           If blank, we'll use just your name. Learn more http://mypronouns.org
        required: false
      - label: Email
        name: email
        widget: string
        hint: If you include an email address, it will be displayed on your profile page
        comment: If you include an email address, it will be displayed on your profile
          page
        required: false
      - label: Bio
        name: bio
        widget: text
        hint: Keep it under 50 words and only one paragraph
        comment: Keep it under 50 words and only one paragraph
        required: false
      - label: Bio URL
        name: bio_url
        widget: string
        hint: >
          Where can people learn more about your work? Provide a full URL [e.g.
          'https://www.example.gov/']
        comment: |-
          Where can people learn more about your work?
           Provide a full URL [e.g. 'https://www.example.gov/']
        required: false
      - label: Agency Full Name
        name: agency_full_name
        widget: string
        hint: e.g. U.S. General Services Administration
        comment: e.g. U.S. General Services Administration
        required: false
      - label: Agency Acronym
        name: agency
        widget: string
        hint: e.g. GSA
        comment: Agency Acronym [e.g., GSA]
        required: false
      - label: Location
        name: location
        widget: string
        hint: >-
          Help us show that the federal workforce is not all in the D.C. area.

          Where in the country do you live in? [e.g. 'New York City' or 'Portland, OR']
        comment: Tell us where you live and work [e.g. 'New York City' or 'Portland,
          OR']
        required: false
      - label: GitHub ID
...

**Comment by ToniBonittoGSA** [comment] 2021-04-09 00:23
We have 10 collections in our Workflow site, https://digital.gov/workflow/ -- this is one of 6 that are giving this error today. An Issue was created for each.
Thank you

**Comment by tomrutgers** [comment] 2021-04-09 07:34
I closed your other issues as it doesn't exactly help having to answer on six different topics for a single site. Please fill out the missing issue template information

**Comment by erezrokah** [comment] 2021-04-12 07:08
Thanks @tomrutgers ❤️ @ToniBonittoGSA, per @tomrutgers's comment, in order to unidentify the cause for the error we need more information. Specifically the full `config.yml` and a step by step reproduction of the issue.

**Comment by ToniBonittoGSA** [comment] 2021-04-13 18:10
Thanks. We have 10 collections in our Workflow, but 6 of them are not working properly. To see the error, follow these steps: 

1. Start here https://digital.gov/workflow/ 
2. In the left Collections list, click on News.
3. Once the page loads, see the list of current blog posts on the right (if it says "no entries," reload the page), and at the top, a _**New Blog Post**_ button.
4. Click the _**New Blog Post**_ to see the "a.get is not a function" error with a link to submit an Issue here.

Normally, when we click the **_new &#95;&#95;&#95;&#95;&#95;_** button on any of those 6 collections (News, Community, Events, Resource, Service, and Source), a form is supposed to load so we can enter new content for our site. Instead, we get the "a.get is not a function" error and link to submit an Issue on all six.

<img width="587" alt="114110808-5e5bce00-98a6-11eb-8efd-7fb45934ade1" src="https://user-images.githubusercontent.com/19961574/114599526-38954700-9c61-11eb-80c8-1bff72c433a2.png">

**Comment by erezrokah** [comment] 2021-04-14 11:25
Hi @ToniBonittoGSA, this error is coming from a custom widget called `async-select`.
See 
![image](https://user-images.githubusercontent.com/26760571/114702370-a8bccf00-9d2c-11eb-8c7a-281962dbb9ac.png)
and https://github.com/GSA/digitalgov.gov/blob/b5f8434e9481e299ddb8456e7175d0a17f0b0d86/themes/digital.gov/static/workflow/index.html#L12

I recommend updating to the latest version of the widget, and if that doesn't work open an issue on [that repo](https://github.com/chrisboustead/netlify-cms-widget-async-select).

Closing the issue as I believe this is not related to core CMS code.

Please comment if reaching out to the custom widget repo didn't help.

**Closed by erezrokah** 2021-04-14 11:25 UTC
Labels: status: more info needed

**Comment by ToniBonittoGSA** [comment] 2021-04-14 15:48
Thank you!
