### ISSUE TITLE
List widget should work without a key name

### ISSUE THREAD

**Issue by insidedwebsite** [netlify/netlify-cms#621] opened 2017-09-20 10:26 UTC
For example if I have such a _data file in Jekyll without an initial key, I can't add a new item with the list widget, cause it always has to have a name. Possible solution could be if the -name key is an empty string that should mean we don't want to have a name key, not undefined as is know.
This is the sample _data file I'd like to modify via the CMS: 

<img width="452" alt="screen shot 2017-09-20 at 12 29 03" src="https://user-images.githubusercontent.com/31308503/30639472-58f11132-9dff-11e7-97ca-6cbdb2858674.png">

**Comment by tech4him1** [comment] 2017-09-20 12:49
This is somewhat related to #596, but it will probably require a separate implementation.

**Comment by tech4him1** [comment] 2017-09-22 19:52
Duplicate of #531.

**Closed by tech4him1** 2017-09-22 19:52 UTC
Labels: feature request
