### ISSUE TITLE
Permission denied to access property "nodeType" on Alt Text (image) editing 

### ISSUE THREAD

**Issue by idiazroncero** [netlify/netlify-cms#1709] opened 2018-09-04 10:52 UTC
**Describe the bug**
Error when uploading an image using the WYSIWG editor (widget:markdown, body field).
The error happens when you click on the ALT field of the image, (the image uploads correctly).
The error happens using both a gitlab and github backend.
The error is: Error: Permission denied to access property "nodeType""

**To Reproduce**

- Install a template based on a GitLab / GitHub back-end (I tried both) I used this:
https://templates.netlify.com/template/eleventy-netlify-boilerplate/
- Login to the admin and edit/create a new post.
- Add an image to the markdown field. Upload a new image and select it.
- Click on the Alt field
- The error happens. Blank screen and message:

"Sorry!
There's been an error - please report it!
Error: Permission denied to access property "nodeType""

**Expected behavior**
Error doesn't happen.

**Applicable Versions:**
 - Netlify CMS version: 2.0.11
 - Git provider: Tried github and gitlab
 - OS: macOS Hight Sierra
 - Browser version: Firefox 61.0.2
 - Node.JS version: 8.11.4

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'blog'
    label: 'Post'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Page'
    folder: 'pages'
    create: false
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Navigation Title', name: 'navtitle', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'nav' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

It's the original from the repo

**Comment by tech4him1** [comment] 2018-09-04 16:17
I can reproduce this on the CMS demo site in Firefox.

**Comment by tomrutgers** [comment] 2018-09-04 16:19
Possibly related to a bug with `e.originalTarget` in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=208427

**Comment by erquhart** [comment] 2018-09-04 18:03
Looks like:

1. This functionality broke in 2.0.10 ([repro](https://2-0-10--cms-demo.netlify.com/#/collections/posts/new)), originally giving error: `TypeError: i is not a function`.
2. Something changed in 2.0.11 ([repro](https://2-0-11--cms-demo.netlify.com/#/collections/posts/new)) so that the error message reported above shows.

The errors are originating from Slate. I'm betting the original break occurred due to the Slate dependency [update](https://github.com/netlify/netlify-cms/pull/1451) that was released in 2.0.10. [An issue](https://github.com/ianstormtaylor/slate/issues/1744) on their repo shows other users experiencing this in recent months, and one of the commenters opened a Firefox [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1449936).

It seems this needs to be address within Firefox, but we won't know until someone responds to the bug report. Keeping open for now.

**Comment by erquhart** [comment] 2018-09-04 18:26
If someone is up for forking the Slate repo and figuring it which commit broke things, that would probably help their team on investigating a fix. I'm guessing it's the `slate-react` package, as I believe all DOM things happen there, but not certain.

**Comment by misterr8472** [comment] 2018-09-15 12:49
Windows 10 x64, FF 62.00 reporting in. Same issue.

**Comment by geonnave** [comment] 2018-11-22 01:59
This issue also happens on Ubuntu 18.04 64-bit, Firefox 63.0 64-bit.

**Comment by anderskitson** [comment] 2018-12-27 17:02
Same issue windows 10, firefox

**Comment by tech4him1** [comment] 2018-12-29 15:16
See https://github.com/ianstormtaylor/slate/pull/2178.

**Comment by GitToby** [comment] 2018-12-31 13:02
same issue with win10 firefox, also with the title edit section too

**Comment by danoc** [comment] 2019-10-19 00:17
Seems like the downstream fix has not yet made it into Netlify CMS. Any chance we can get `slate-react` upgraded? Happy to help if needed.

**Comment by erquhart** [comment] 2019-11-05 21:19
This will be fixed with https://github.com/netlify/netlify-cms/pull/2828.

**Comment by erezrokah** [comment] 2020-04-19 13:02
Closing as fixed (didn't reproduce with Firefox/Chrome). Please comment/re-open if issue persists

**Closed by erezrokah** 2020-04-19 13:02 UTC
Labels: area: browser-compatibility, area: extensions/widgets/markdown, kind: bug, status: confirmed, status: needs attention, status: needs vendoring
