### ISSUE TITLE
Error: Invariant failed

### ISSUE THREAD

**Issue by tsavlis** [netlify/netlify-cms#3539] opened 2020-04-05 11:18 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.39`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: '-'
backend:
  name: git-gateway
  branch: master
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: pages
    label: Page
    delete: false
    editor:
      preview: true
    files:
      - file: content/pages/contact.md
        label: Contact Page
        name: contact-page
        fields:
          - label: Title
            name: title
            widget: string
          - label: Featured Image
            name: featuredImage
            widget: image
          - label: Subtitle
            name: subtitle
            widget: markdown
          - label: Body
            name: body
            widget: markdown
          - label: Address
            name: address
            widget: text
          - label: Phone
            name: phone
            widget: string
          - label: Email Address
            name: email
            widget: string
          - label: Meta
            required: false
            name: meta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Description
                name: description
                widget: text
                required: false
                pattern:
                  - '.{,300}'
                  - Must not exceed 300 characters
              - label: Canonical Link
                name: canonicalLink
                widget: string
                required: false
              - label: Noindex
                name: noindex
                widget: boolean
                required: false
      - file: content/pages/blog.md
        label: Blog Page
        name: blog-page
        fields:
          - label: Title
            name: title
            widget: string
          - label: Featured Image
            name: featuredImage
            widget: image
          - label: Subtitle
            name: subtitle
            widget: markdown
          - label: Meta
            required: false
            name: meta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Description
                name: description
                widget: text
                required: false
                pattern:
                  - '.{,300}'
                  - Must not exceed 300 characters
              - label: Canonical Link
                name: canonicalLink
                widget: string
                required: false
              - label: Noindex
                name: noindex
                widget: boolean
                required: false
      - file: content/pages/about.md
        label: About Page
        name: about-page
        fields:
          - label: Title
            name: title
            widget: string
          - label: Featured Image
            name: featuredImage
            widget: image
          - label: Subtitle
            name: subtitle
            widget: markdown
          - label: Section 1
            name: section1
            widget: markdown
          - label: Section 2
            name: section2
            widget: markdown
          - label: Meta
            required: false
            name: meta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Description
                nam
...

**Comment by erezrokah** [comment] 2020-04-05 12:07
Hi @tsavlis, can you share your full `config.yml` and possible a screenshot of where you got the error? A reproduction repo can also help a lot in getting the issue resolved.

**Comment by erezrokah** [comment] 2020-04-06 07:01
Closing due to lack of information, please re-open and follow the issue template.

**Closed by erezrokah** 2020-04-06 07:01 UTC
