### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by sten-dev** [netlify/netlify-cms#3006] opened 2019-12-27 04:11 UTC
I am getting this problem when deploying netlify-cms with custome youtube editor widget markdown

```
export const YoutubeLink = {
  id: "youtube",
  label: "Youtube",
  fields: [{ name: 'id', label: 'Youtube Video ID', widget: 'string' }],
  pattern: /^<span class="yo-youtube"><iframe src="\/\/www.youtube.com\/embed\/(.*)" frameborder="0" allowfullscreen><\/iframe><\/span>/,
  fromBlock: function (match) {
    // console.log(match)
    return {
      id: match && match[1] ? match[1] : ""
    };
  },
  toBlock: function (obj) {
    return (
      `<span class="yo-youtube"><iframe src="//www.youtube.com/embed/${obj.id}" frameborder="0" allowfullscreen></iframe></span>`
    );
  },
  toPreview: function (obj) {
    return (
      `<span class="yo-youtube"><iframe src="//www.youtube.com/embed/${obj.id}" frameborder="0" allowfullscreen></iframe></span>`
    );
  }
};
```

Deployment logs

`9:23:39 AM: success Generating image thumbnails - 15.325s - 52/52 3.39/s
9:24:18 AM: failed Building production JavaScript and CSS bundles - 53.788s
9:24:18 AM: error Generating JavaScript bundles failed
9:24:18 AM: Cannot read property 'match' of undefined
9:24:18 AM: not finished run queries - 54.144s
9:24:18 AM: npm
9:24:18 AM:  ERR! code ELIFECYCLE`

have no problem when i comment the `CMS.registerEditorComponent(YoutubeLink);` 
yarn run build runs without an error locally, but errors only on deployment

Applicable Versions:

Netlify CMS version: 2.10.1
Git provider: GitHub
OS: windows 10
Browser version: chrome 79
Node.JS version: 12.13.1

**Comment by erquhart** [comment] 2020-01-07 22:30
Hard to diagnose, but it sounds like a build system issue rather than anything with the CMS source. I don't see any place in your code where you're referencing a property named 'match', either.

**Comment by danoszz** [comment] 2020-01-19 16:52
@sten-dev It seems like it's an [NPM error](https://dev.to/stephencweiss/npm-cannot-read-property-match-of-undefined-238n). As suggested you can try to remove `node_modules` and `package-lock.json` and run `npm install`. Let me know if this works.

**Comment by erezrokah** [comment] 2020-01-20 13:14
Hi @sten-dev can you share your `config.yml` and Gatsby setup? I tried reproducing and the generated markdown looks ok to me https://github.com/erezrokah/netlify-cms-reproductions/pull/12/files

**Comment by erezrokah** [comment] 2020-01-21 07:53
Closing this due to lack of info

**Closed by erezrokah** 2020-01-21 07:53 UTC
