### ISSUE TITLE
Support for multilingual content authoring

### ISSUE THREAD

**Issue by gibujin** [netlify/netlify-cms#716] opened 2017-10-19 12:09 UTC
The good people at Netlify has confirmed to me that multilingual content is not really supported. But that doesn't necessarily mean that its not possible. For example having a post with a title field * languages supported doesn't really seem like a good idea. Another approach could be to create multiple admin interfaces (/admin/en, /admin/es etc.)for each language (if thats possible, haven't tested it). How would you approach this, any other suggestions?

**Comment by erquhart** [comment] 2017-10-23 20:15
If you're looking for multiple languages in the admin interface, there's a PR here that's close: https://github.com/netlify/netlify-cms/pull/403

**Comment by kations** [comment] 2017-10-25 17:33
@erquhart  I think @gibujin means multilingual content, that would be a nice feature. Maybe there is a way to define languages in config.yml like ['us', 'fr', 'de'] and than you have a global language select in the admin ui to create content for a specific lang.

**Comment by erquhart** [comment] 2017-11-27 22:49
In that case I'd expect it to be a bit of both, as selecting a global language setting should cause the UI to be labelled in that language. It sounds like you're looking to have the same content in multiple languages, so I imagine you'd want some way to see what entries exist that have no translation in the current language? Beyond that each language should publish to a separate directory, and we'd need certain string properties in the config to start accepting an object of language-keyed strings.

Thoughts?

**Comment by tech4him1** [comment] 2017-12-07 23:23
@erquhart Is this a duplicate of https://github.com/netlify/netlify-cms/issues/342?

**Comment by erquhart** [comment] 2017-12-09 07:56
I think @fool was more pointing at handling automation of translation. This is about supporting the manual creation of multilingual content.

**Comment by fool** [comment] 2017-12-09 16:32
Not even "automation" so much as "easy support for".  But yes not in the
admin gui, in the content.  E.g. Being able to take a template from an
English post with graphics and code blocks and turning it Spanish.  One
click "clone" with ability to identify articles that are missing
translations would be most of it.  Configuring your site to serve the
different content would be out of scope for the cms by my reckoning

On Dec 8, 2017 23:56, "Shawn Erquhart" <notifications@github.com> wrote:

I think @fool <https://github.com/fool> was more pointing at handling
automation of translation. This is about supporting the manual creation of
multilingual content.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/netlify/netlify-cms/issues/716#issuecomment-350431178>,
or mute the thread

**Comment by blgo** [comment] 2017-12-13 16:51
@fool 
I agree, the clone functionality would be ideal ! It will allow to match the original filename with the translated version.

In addition, It should allow to add a language suffix to the filename: i.e. "mypost.es.md". 

However, I realised that I cannot create this suffix ".es" using slug for naming the file because the code remove dots from slug.

Any ideas?

**Comment by erquhart** [comment] 2017-12-20 18:15
@gibujin you can already create multiple cms instances as you described, since the CMS is just a single page app.

@blgo @fool can you point to any examples out there of a CMS with the described clone functionality?

**Comment by tech4him1** [comment] 2017-12-20 18:25
@blgo The issue with extension suffixes is here: https://github.com/netlify/netlify-cms/issues/877

**Comment by fool** [comment] 2017-12-20 21:03
haven't used one but this link makes it seem like maybe drupal and joomla
both did it in 2015:
https://www.acclaro.com/blog/how-to-choose-cms-for-multilingual-website/

**Comment by erquhart** [comment] 2017-12-30 21:54
So it sounds like we need product level contributions at this point. So far we have:

- clone functionality for existing entries that need to be copied and translated
- some way of seeing which articles have/have not been translated into a given language
- ability to configure file names based on language

Anything missing? UX considerations? How do we make this unobtrusive?

**Comment by MarcCoet** [comment] 2018-01-30 23:38
just dropping my 2 cents. Contentful has a very neat UX for content translation / 'locales'. You may find it inspiring to have a look.

**Comment by erquhart** [comment] 2018-02-01 17:55
Great tip @MarcCoet, will do! Feel free to drop specifcs, screenshots, etc if you think anything specific aspect is particularly impactful for the project.

**Comment by andresgutgon** [comment] 2018-02-01 18:17
@erquhart do you have plan in terms of timings to develop multilingual?

**Comment by erquhart** [comment] 2018-02-02 04:17
There's no active development at the moment, still need to determine the right approach. You're welcome to help move things along if you're interested in digging in.

**Comment by whmountains** [comment] 2018-03-15 22:57
I'm a freelancer in South America 🇨🇱  and almost all my clients need a Spanish site for local clients and an English translation to reach foreign tourists.  So having official support for multiple languages would be really useful!

I agree with @MarcCoet that Contentful has a really convenient UI for translations.  Basically there are some checkboxes in the sidebar that let you select which languages to work on, and then it will show a copy of each field for each language.  Here's a screenshot to show what I mean: 

![screen shot 2018-03-15 at 7 52 40 pm](https://user-images.githubusercontent.com/8680147/37495102-91161600-288a-11e8-900a-1f2688c75b1d.png)

IMO an anti-pattern for localization is to simply offer a language switcher with no ability to view multiple languages at once.  You have to open multiple windows to see the original text and new text and it's annoying, although still much better than nothing.

**Comment by erquhart** [comment] 2018-03-16 15:29
Awesome, thanks for the specifics @whmountains.

@hcavalieri this ^^ just pointed out an issue with the tabbed i18n approach from #1166 - folks are going to want to look at multiple translations at once, especially while translating.

**Comment by kizu** [comment] 2018-04-27 18:48
I would like to link here to my comment in the issue about subfolders content: https://github.com/netlify/netlify-cms/issues/513#issuecomment-384623303 — one of the common patters (used in Hugo, for example) is to have one folder for each post/article/page, and have multiple localised index.LANG.md inside, for example:

```
├── 2018-04-26-my-awesome-post
    ├── index.en.md
    ├── index.ru.md
```

How I see this implemented in cms: have multiple tabs for different languages, or even multiple columns, so it would be possible to see same field with different languages next to each other. Similar to how there is a rendered preview for a post, it would be nice to have alternatively compare two languages, with the same sync scroll feature etc.

One issue that also appears related to such handling of content: very often you could want to have some metadata to be duplicated between multiple language versions. This can be true for fields like date (you could want to have it always the same), some attached images (you won't want to attach the same image twice or more), or any other non-textual content (like prices, external links etc.)

How I see this implemented: for each field/widget there can be a boolean param that would tell if that field is by default mirrored across multiple languages. Then, when you edit a page, editting one mirrored field would change others. And there should be a way to “unlink” a field for a page, for example if you'd want to upload a localised image at some point.

**Comment by moeamaya** [comment] 2018-04-29 16:04
Craft CMS has clever way of handling this by having a language toggle and small labels on each input. Seems like a decent way to handle the UX. 

![image](https://user-images.githubusercontent.com/1373293/39408496-0898f818-4b8c-11e8-8b5e-5c5328348598.png)

**Comment by cjonasw** [comment] 2018-05-29 10:06
Any update on this?

**Comment by CodeBarman** [comment] 2018-05-31 23:00
Yeap, I am interesting in this feature too.

**Comment by erquhart** [comment] 2018-06-06 22:10
### Update

Until someone volunteers to own this effort, or until the core team is able to dig in, we could at least ease the pain of multilingual authoring by completing #981 so that an existing entry can be duplicated. To that end, I've added that issue to the 2.0 board targeting the initial release. This doesn't guarantee that it will get in by 2.0, but we'll push.

Comprehensive multilingual support is still a major priority.

**Comment by fbnlsr** [comment] 2018-06-08 22:27
I don't know if this could be related, but it could be nice to be able to use a string widget to specify the filename of the page/post being created/edited.

Hugo has a specific behavior where it automatically links two pieces of content when their filename are identical, minus a language parameter. So for instance `about.md` and `about.fr.md` are automatically linked on build time.

**Comment by fbnlsr** [comment] 2018-06-14 21:21
Just to piggyback on my previous comment: Forestry does provide a way to provide/rename a file from their admin panel. When you create a new content (blog post / page / whatever) you can specify a filename and add your own extension. They then add a small icon with the language prefix of the files in the post list.

**Comment by rchrdnsh** [comment] 2018-11-11 06:54
Any updates?

**Comment by erquhart** [comment] 2018-11-14 16:39
Not yet, no. Definitely willing to support any devs that are able to work on this, though.

**Comment by RonaldDijkstra** [comment] 2018-11-16 09:50
+1

**Comment by erquhart** [comment] 2019-01-30 17:54
@schalkventer anything to add here?

**Comment by schalkventer** [comment] 2019-01-30 18:53
Thanks for the link @erquhart 

So when I'm hardcoding multilingual support currently with Gatsby I do the following. I have a single JSON file be the source of all the translations for a specific item:
```
{
  type: 'blog',
  id: 'example-title',
  en: {
    title: 'Example Title',
    date: '07/01/2018',
    thumbnail: 'https://placeholder.com/200x200',
    body: 'This an example message'
  },
  af: {
    title: 'Voorbeeld Titel',
    date: '07/01/2018',
    thumbnail: 'https://placeholder.com/200x200',
    body: 'Hierdie is \'n voorbeeld boodskap'
  },
  xh: {
    ...
  },
  so: {
    ...
  },
  fr: {
    ...
  }
}
```

I would the query a specific language version of that item as follows:
```
{
  allJson (filter: {  type: { eq: blog }}}) {
    af {
      title
      date
      thumbnail
      body
    }
  } 
}
```

This will then return an array of all the blog entries in Afrikaans. Seems to work easy enough for now.

However, it becomes a bit tricky when I want to do this with Netlify CMS, since I have to replicate each item in the dashboard for each language. This means the dashboard view for a specific item get pretty cluttered very easily, and just grows in size as more languages or content gets added. I have a project in production at the moment that support 15 languages.

**Comment by schalkventer** [comment] 2019-01-30 18:57
So my concern is mostly related to the UX experience in the dashboard (especially if clients need to add the translations themselves). I think @moeamaya's suggestion above in regards to Craft CMS seems pretty solid.

You could possibly define languages in the `config.yaml` file:
```
backend:
  name: github
  repo: user/repo

languages
 en: English
 af: Afrikaans
 xh: isiXhosa
 so: Southern Sotho
 fr: French

collections:
  - label: "Blog"
    name: "blog"
    folder: "_posts/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
```

**Comment by schalkventer** [comment] 2019-01-30 19:19
Another approach might be to manually enable translation for specific fields and even have a primary/default language: 

```
backend:
  name: github
  repo: user/repo

languages
 en: English
 af: Afrikaans
 xh: isiXhosa
 so: Southern Sotho
 fr: French

collections:
  - label: "Blog"
    language: "en"
    name: "blog"
    folder: "_posts/blog"
    create: true
    fields:
      - {label: "Type", name: "blog", widget: "hidden", default: "blog" }
      - {label: "Title", name: "title", widget: "string", translations: true }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", translations: true}
```

So the above might possibly give something like the following (which also solves the problem of `identifier_field` needing to be a root level field):

```
{
  type: 'blog',
  date: '07/01/2018',
  thumbnail: 'https://placeholder.com/200x200',
  title: 'Example Title',
  body: 'This an example message',
  af: {
    title: 'Voorbeeld Titel',
    body: 'Hierdie is \'n voorbeeld boodskap'
  },
  xh: {
    title: 'Isihloko Umzekelo',
    body: 'Lo ngumyalezo umzekelo',
  },
  so: {
    ...
  },
  fr: {
    ...
  }
}
```

**Comment by schalkventer** [comment] 2019-01-30 19:21
However, also keep in mind that the above is very specific to my circumstances/tooling, so there might be another approach that might be more useful for the majority of users.

**Comment by joallard** [comment] 2019-02-03 22:11
Hmm, I'm not sure if I understand `identifier_field` right, but indeed, there would need to be some kind of unique identifier that's not an object (uuid, serial int, string). Initially I thought that would be naturally the slug, but as the slug often follows the localized title, maybe not. (I'll update my example)

**Comment by erquhart** [comment] 2019-02-03 23:16
@joallard do you know of any static site generators that handle localization this way? The examples I'm aware of expect a separate file for each translation for repeatable content like blog posts.

**Comment by P233** [comment] 2019-04-23 06:23
I just created a workaround for this. If you are interested, please take a look at https://github.com/P233/gatsby-netlify-i18n-workaround, and feel free to improve it.

**Comment by ShevaShen** [comment] 2019-04-24 03:58
This might help. From Netlify CMS official site.
https://www.netlifycms.org/docs/collection-types/#filtered-folder-collections

**Comment by austincondiff** [comment] 2019-08-16 18:19
Any update here. This piece of functionality seems crucial to any CMS. I don't think language-based collections are going to cut it. If you have 10 collections and five supported languages, not you have 50 collections to manage! Not too maintainable. This doesn't work.

**Comment by tremby** [comment] 2019-08-16 19:02
I've been following this ticket for probably 18 months. This was, and still is, the one thing holding me back from trying netlify-cms out on a new project. I still really want to, but every project which would otherwise be suitable has been multilingual! So I'm still eagerly awaiting this feature.

**Comment by austincondiff** [comment] 2019-08-16 19:54
My question is, why isn't this a bigger priority? I am super excited for the JAMstack but this product really needs some love and attention to become a viable replacement in some of these prominent use cases. Does the team need help? Why has this been on the back burner for so long? In general I feel like development with this project is really slow going. Anyone else get this vibe?

**Comment by whmountains** [comment] 2019-08-16 21:11
Indeed, I really want to use Netlify CMS but it’s not quite there yet.  Proper translation support is the biggest blocker for me.

**Comment by yvele** [comment] 2019-09-04 14:54
Yes we also want to use Netlify but lack of multilingual support is a no go for us 😞

**Comment by whmountains** [comment] 2019-09-04 15:09
I'm in the same boat.  I think Netlify CMS could be hugely popular but it needs a bit more love.


On September 4, 2019 at 11:54 AM, "Yves M." <notifications@github.com> wrote:



Yes we also want to use Netlify but lack of multilingual support is a no go for us 😞

**Comment by sangeet** [comment] 2019-10-01 15:40
I wish there was a solution available for this problem. This is one thing holding a significant amount of potential clients from non-english speaking nation from moving to JAMStack. 

Almost all clients need a preview feature from their CMS because Wordpress has spoiled them for a good decade, hence NetlifyCMS is the only viable choice of CMS for Gatsby and the likes because let's be honest nobody is willing to pay $600/year for Gatsby Preview feature that they sell. So NetlifyCMS it is and it works great.

Now, it all falls apart when the potential client is from a non-english speaking nation. Then they at the very least absolutely need at least support for two languages. There are currently only two headless CMS which offer reasonably good locale features, **Contentful** and **DatoCMS**, but then these two lack the preview feature and as usual clients are not willing to spend $600/year for adding preview support to them.

So essentially, for most of the potential clients from non-English speaking nations willing to move to JamStack, this is one thing significantly holding them back. They need a combination of preview feature + content localization and at the moment nothing offers this essential combination and I feel that it is seriously hurting the adoption of JAMStack in general for a lot of potential clients.

I can understand that it is not easy to build up such a feature on an already very active project, but Netlify has significant resources behind it and hence it shouldn't be impossible to prioritize this feature because as it currently stands, lack of localization is a deal breaker for a lot of clients and at the moment there's no real way around it unless they are willing to sacrifice on preview feature which a majority of clients are not.

Sorry if this went slightly off topic, just expressing my views on the significantly important need of this essential feature for a CMS.

**Comment by chriskirknielsen** [comment] 2019-10-22 19:28
I have started a tiny bit of work on this idea but I will warn you;
- code is not very clean
- creating, editing, deleting do not work **at all**
- I think this would not work at all outside of this test environment, given I have made edits to `netlify-cms-backend-test` files — I would love some pointers
- I am… quite lost as to what I'm supposed to be doing

If anyone wants to join in on the fun, I have created a branch:
https://github.com/chriskirknielsen/netlify-cms/tree/feature/path-options

If you run this locally you will see both the English and French test posts listed in the Posts collection. A first step!

The `config.yml` file has new/edited settings:
``` yml
# ...
    pathOptions:
      languages:
        - en
        - fr
    folder: '_posts/{{ languages }}' # any {{ template }} must match one of the `pathOptions`
    internal_routing: 'posts/{{ languages }}' # Override the route URL, ie.: /admin/collections/:internal_routing/edit
# ...
```

Right now I've hit a roadblock since I don't know how NetlifyCMS generates its links to the editor nor how routing is handled. I have added an option in the collection named `internal_routing` which will allow NetlifyCMS to read the extra path options in the right sequence (so that if the post is in `/en/non-code/, it'll know to look for `{{ language }}`, and for `{{ tag }}` — you don't want tags in your slug but just an example).

I'd love to get some insight from people who are more involved in this (type of) project and that might be able to provide better insight as to how this all works. Any help at all would be awesome. :)

Thanks!

**Comment by erquhart** [comment] 2019-10-24 05:13
I’ll at least note that this issue is very much top of mind for the maintainers. It’s the 4th highest issue in our list sorted by reactions (thumbs up really do matter): https://github.com/netlify/netlify-cms/issues?q=is%3Aopen+sort%3Areactions-%2B1-desc

Big thanks to everyone that is working toward intermediate solutions, you’re helping to bridge a critical gap.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by phil-lgr** [comment] 2019-11-14 17:30
> I just created a workaround for this. If you are interested, please take a look at https://github.com/P233/gatsby-netlify-i18n-workaround, and feel free to improve it.

this is great! I'm wondering if this is a direction considered by the maintainers?

**Comment by hajaalin** [comment] 2019-11-24 16:46
A related point about Hugo, currently the only way to translate section names seems to be this workaround: https://github.com/gohugoio/hugo/issues/3354#issuecomment-475975122.

It would be great to have support for this use case, i.e. ability to specify content directory per language, and to add a shared translation key (e.g. slug of default language).

**Comment by barthc** [comment] 2019-12-20 18:51
So we have a PR #2988  that attempts to solve this issue. The approach is based on comments https://github.com/netlify/netlify-cms/issues/716#issuecomment-373549215 and https://github.com/netlify/netlify-cms/issues/716#issuecomment-459513051 . Any feedback is highly appreciated, thanks.

**Comment by bencao** [comment] 2020-01-13 15:55
To provide a different perspective, my current approach for the issue is to setup separate netlify sites (and cms admin) for different locales.

the repo directory structure looks like this:

```
.
├── app
│   ├── gatsby-browser.js
│   ├── gatsby-config.js
│   ├── gatsby-node.js
│   ├── gatsby-ssr.js
│   ├── package.json
│   ├── src
│   ├── static
│   └── yarn.lock
├── cn
│   ├── assets
│   ├── cms-config.yml
│   ├── data
│   └── netlify.toml
└── en
    ├── assets
    ├── cms-config.yml
    ├── data
    └── netlify.toml
```

for different locale, I created netlify site with base directory to each locale, such as en.
`netlify.toml` file in the locale folder contains instructions for deployment:

```
[build]
  ignore = "git diff --quiet HEAD^ HEAD ../app/ ./"
  publish = "app/public/"
  command = "cp -r ../app . && cp -r data ./app/ && cp -r assets ./app/static/ && cp cms-config.yml ./app/static/admin/config.yml && cd ./app && npm install -g yarn && yarn install && yarn build"
```

`cms-config.yml` will be copied as app/static/admin/config.yml:

```
backend:
  name: git-gateway
  branch: master

public_folder: assets
media_folder: en/assets            # media folder should point to the assets directory in locale folder
```

and lastly, the development support is implemented as a script in `package.json`:

```
"scripts": {
    "bootstrap": "cp ../en/cms-config.yml static/admin/config.yml && rm -rf static/assets && cp -r ../en/assets static/ && rm -rf data && cp -r ../en/data .",
    "bootstrap-cn": "cp ../cn/cms-config.yml static/admin/config.yml && rm -rf static/assets && cp -r ../cn/assets static/ && rm -rf data && cp -r ../cn/data .",
    ...
  },
```

hope the above solution offer help to someone facing the similar situation.

**Comment by joallard** [comment] 2020-01-26 06:12
So I can see from #2988 that we're still looking for UI/UX solutions on this. Thanks @barthc for the initiative by the way!

To explain my background, I'm a francophone who's been scouring the English internets for a long time; translating Wordpress posts has been my job a long time ago; I've worked on Middleman's I18n features; and am a total UI-UX geek. So I've been thinking about localization interfaces for a long time.

Here's what I'd like to see in an L10n interface. Explanations after the image.

<img width="702" alt="PNG image" src="https://user-images.githubusercontent.com/949482/73131241-8890db00-3fd5-11ea-9144-714cb131ddf6.png">

---

* **Side by side view**: This is a life saver for any kind of localization. I have on my left the content already populated in one language, and on the other, the one to fill in. I can quickly look side to side what to translate.

* **Quick language switcher**: I can select what is the language I see on each side. Selecting a language will not make me lose my changes, all data is in local memory. This allows me to translate between more than 2 languages, with the one I want for reference. If I'm not sure of what to write in a third language, I can consult both the first and second.

* **Save button**: The Save button saves all languages. (Linkedin's interface is really clunky about this) It should be part of the contract that switching a language does not throw your work away!

As a matter of implementation, those are enough for me and a huge leap forward. This could be PR One.

Now, the nice to haves:

* **Dirty indicator**: An indicator tells me about what I don't see. It could either be: (1) I've made changes to fields in language A but not in language B, so indicator tells me maybe I should; or (2) simply that this language contains changes. (A tooltip would probably be helpful here)(See Linkedin Profile About Us localization, which is an interesting though imperfect example.)

* **Synced scroll on rich text**: If you're translating content that spans more than the textarea height, you'll run into an issue quickly: what you're seeing on the left isn't scrolled the same as what you're seeing on the right. As a poor man solution, you could scroll manually. Ideally, an algorithm would guess what is the semantic position of paragraphs on both sides and synchronize that. 

   *Sidenote:*
This doesn't seem trivial, and the use cases are probably different on text creation vs text edition. I would neither assume that both versions contain the same amount of paragraphs. - I do wonder whether translation software has a solution/algorithms for this. A poor man's solution I've used in the past with Vimdiff was to label places with Markdown/HTML comments on both sides to force it to sync. (eg. `<!-- 5 -->`)

* I could also conceivably just collapse language B in the case I don't need it. I wonder about the usefulness of this feature.

**Comment by joallard** [comment] 2020-01-26 06:33
Now on to the index view and filtering:

(Keep in mind, I don't really know what the index view looks like, sorry about that)

---
<img width="694" alt="PNG image 2" src="https://user-images.githubusercontent.com/949482/73131505-1b337900-3fda-11ea-826c-cacb9c8214e2.png">
---

#### Index/Collection view
On the index view, I want to get a gist of which version is present or needs work ("done-ness"). A faded bubble could indicate absence, a warning color could indicate need to update.

  This suggests two things:

  * The indicator talked about previously would probably be useful to indicate "need to update"
  * Changes in one language don't necessarily mean Need to update in all others. The UI could conceivably ask that question when a change is saved. (You just corrected something, do other languages need to be corrected too? Or did you correct a typo? - this, but unobstrusively, maybe a checkbox next to the Save button)

  Also, this could probably support max 6-8 languages/bubbles in sight, optionally on two rows.

#### Filtering
If I'm a translator, I probably need to know which records need work on. 

> - Show me records where es, fr are empty
> - Show me records where es, fr are either empty or need update

If I'm an editor, I probably need to know what's there and that I can publish

> - Show me records where all languages are up to date
> - Show me records where en, fr are up to date

Those are the filtering use cases I can come up with for now. I'm mainly thinking about Airtable's filtering interface as a matter of inspiration.

To divide it into PRs:

1. Side-by-side I18n and data model
1. Dumb-ish sync'ed scroll
1. Filtering
1. Dirty indicator
1. Collection doneness bubbles
1. Good-ish sync'ed scroll

**Comment by erquhart** [comment] 2020-02-19 00:29
@joallard I could have sworn I responded to your comments long ago, sorry about that.

I'm **really** loving the approach you've laid out. It brings the best of what we've discussed so far, rounds out the editor experience with sensible functionality, and matches really well to our current editor model (two big panes side by side).

This issue is very close to hitting active development, I'm in strong agreement with the order of implementation and prioritization you proposed as well. Thank you!

**Comment by joallard** [comment] 2020-02-19 04:33
@erquhart I'm really glad it's appreciated! I've been wanting to see a good I18n interface in a CMS for a *long* time. I'm open to be reached if there's any question or if I can help.

Since then I've taken a look at what Ghost does for blog articles (turns out their "multi-language" feature is not really one after all) and more precisely that fact that textareas don't scroll, they just expand/fill the page. That could be a simple way to work around the scroll problem: no scroll! The box just resizes according to its content. That would more or less do it for a variety of cases. We just have to ensure the next cells in the columns are at the same height, and off we go.

**Comment by erezrokah** [comment] 2020-02-27 18:37
Update:
@barthc and @jmdrawneek both offered to help with this issue, which is highly appreciated.

Copying my comment from https://github.com/netlify/netlify-cms/pull/2988#issuecomment-591911768:

> I can see two main efforts here:
> 
> 1. Having the backends support persisting multiple content files (e.g. saving both `post.en.md` and `post.fr.md` under the same entry). This should actually be configured - multiple files vs multiple fields in a single file, and defaults to the most common approach of static site generators.
> 2. Adding a side by side translation editor UI per [#716 (comment)](https://github.com/netlify/netlify-cms/issues/716#issuecomment-578472055).

Unless @barthc or @jmdrawneek have already made significant progress in implementing this feature, we might be able to split up the work.

As @barthc is more familiar with the backends code I'm thinking he can do 1, and as doing the UI part doesn't require that much pre-knowledge of the code base @jmdrawneek can do 2.

I might be completely off here as well, thoughts?

**Comment by inwardmovement** [comment] 2020-02-27 18:51
As a side note, it would be great to have flexibility around how translations are handled: by file name (`post.en.md` / `post.fr.md`) or by folder (`en/post.md` / `fr/post.md`), as Hugo for example allows both.

**Comment by joallard** [comment] 2020-02-27 19:20
As you folks are implementing this, feel free to reach out to me on Keybase or by email if you need a sounding board on this! I'm really glad to see the enthusiasm!

**Comment by barthc** [comment] 2020-03-04 12:44
Another PR #3366 based on @joallard solution.

**Comment by chriskirknielsen** [comment] 2020-03-04 14:35
> Another PR #3366 based on @joallard solution.

@barthc Will the `diff_folder` allow for a fully customisable path? Like `{locale}/posts/post.md`? It's how I have my current setup, and while I could certainly rework it, it would be amazing to be able to keep it as is while using this new feature. :)

**Comment by barthc** [comment] 2020-03-04 15:15
> @barthc Will the diff_folder allow for a fully customizable path? Like {locale}/posts/post.md? It's how I have my current setup, and while I could certainly rework it, it would be amazing to be able to keep it as is while using this new feature. :)

The collection `path` config will allow you to do that.

**Comment by tbille** [comment] 2020-03-31 08:29
hey after showing my example [on discourse](https://community.netlify.com/t/multilingual-implementation-of-jekyll-netlify-cms/11427), I got suggested to come and link my project here.

I just want to share the way I implemented to add multilingual support on my site. 
As mentioned in the topic there is still some manual process that can be automated (Github Actions or similar?) and some parts might need polishing but the idea is there.

**Project:** https://github.com/tbille/multilingual-jekyll-netlify/

**Comment by joallard** [comment] 2020-03-31 20:20
Excellent link @tbille, Durand is spot on about the goals.

I can't help but highlight one of them, that was discussed in the PR:

> ## Flexibility
> Our website can be translated in as many languages as wanted. Each page may be translated or not in the various languagesregardless of the version, they may be pages which are not translated in each language. All pages and posts can be placed as desired.

---

The only *low*light? I can never endorse plain wrong date formats such as `01/09/2014`, or even `2014/09/01` ;). (Friendly reminder that `YYYY-MM-DD` is the only acceptable date format – except when the month has letters)

**Closed** 2020-09-20 17:30 UTC
Labels: area: i18n, hot, kind: discussion, kind: feature, status: needs architecture, status: needs design
