### ISSUE TITLE
Possible to have a "list" in the root of a file collection?

### ISSUE THREAD

**Issue by snirp** [netlify/netlify-cms#1282] opened 2018-04-18 14:03 UTC
Gatsby can make relationships between nodes through ["mappings"](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types). You need to refer to a file - `yaml` or `json` - which contains a list in the root.
 
This would be an example of a file that can be consumed by the Gatsby mapping:
 
```
- id: Kyle Mathews
  twitter: "@kylemathews"
- id: Mathew Kyles
  twitter: "@mathewkyles"
```

I have not found a way to have a _root-level_ list in Netlify CMS. Am I correct that a list can only exist under an object? How can we achieve these mappings then?

**Comment by tech4him1** [comment] 2018-04-18 14:50
I've just been needing the same thing myself, so I'd definitely approve this.

**Comment by erquhart** [comment] 2018-04-18 19:36
Same here, wondering if maybe a boolean on the collection should signify whether the base value is a list or object.

**Comment by davepwsmith** [comment] 2018-06-16 16:21
I have been absolutely banging my head against a wall with this, so would appreciate a solution also! I'm by no means a pro at React/JS but happy to help where I can.

**Comment by tech4him1** [comment] 2018-07-22 21:07
Closed as a duplicate of https://github.com/netlify/netlify-cms/issues/531.

**Closed** 2018-08-23 19:08 UTC
Labels: area: configuration, area: formats, duplicate, kind: feature
