### ISSUE TITLE
Can we add a Modal confirmation box instead of default windows confirmation on clicking the 'Back Arrow' in New Post page?

### ISSUE THREAD

**Issue by Mack241** [netlify/netlify-cms#6194] opened 2022-02-07 05:50 UTC
**Feature:**
Adding a **Modal Confirmation Box** on clicking the "Back Arrow" button on the **New Post** page.

**Description:**
Currently on clicking the "Back Arrow" we see that a windows alert pops up for confirmation. I was thinking of replacing it with a Modal confirmation box instead with an **OK** and a **Close** button.

**Image:**
![netlify-cms](https://user-images.githubusercontent.com/34231653/152731657-e7e7e8fe-8d02-4812-aba7-53334cf911f2.png)

Can this feature be implemented? Let me know! 
Thanks

**Comment by erezrokah** [comment] 2022-02-07 10:22
Hi @Mack241, thanks for opening the issue.

Closing is as duplicate of https://github.com/netlify/netlify-cms/issues/3057

**Closed by erezrokah** 2022-02-07 10:22 UTC
Labels: type: feature
