### ISSUE TITLE
{{permalink}} with / is rewritten to - in preview_path for preview links

### ISSUE THREAD

**Issue by lsolesen** [netlify/netlify-cms#5199] opened 2021-04-01 21:30 UTC
**Describe the bug**

The {{permalink}} has / rewritten to - in preview_path for preview links

**To Reproduce**

I have the following config.yml -- https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

In my backend I have this permalink:

![Screenshot - 2021-04-01T232745 144](https://user-images.githubusercontent.com/148026/113356027-f3f4dc00-9341-11eb-8876-1c3e4d58c627.png)

However, the link generated for View live is the following:

https://www.motionsplan.dk/artikel-unilateral-traening

**Expected behavior**

Expected to have the link using the permalink as is.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

**Comment by erezrokah** [comment] 2021-04-04 14:14
Closing this as duplicate of https://github.com/netlify/netlify-cms/issues/4963.
I'll comment #4963

**Closed by erezrokah** 2021-04-04 14:14 UTC
Labels: type: bug
