### ISSUE TITLE
gatsby develop throws error There was an error compiling the html.js component

### ISSUE THREAD

**Issue by imcodingideas** [netlify/netlify-cms#1751] opened 2018-09-16 20:13 UTC
**Describe the bug**
When following the exact instructions https://next.gatsbyjs.org/docs/sourcing-from-netlify-cms/  when it's time to run: `gatsby develop` I get thrown an error: error There was an error compiling the html.js component for the development server.

**Screenshots**
![screenshot 2018-09-16 13 06 39](https://user-images.githubusercontent.com/5374985/45600425-62a30180-b9b1-11e8-8efb-4acec3e3412b.png)

**Applicable Versions:**
 - Netlify CMS version: 2.1.1
 - Git provider: GitHub
 - OS: macOS High Sierra 10.13.6
 - Browser version: 69.0.3497.92
 - Node.JS version: v8.11.2

**CMS configuration**

backend:
  name: imcodingideas/detroitjs-com

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

**Additional context**
This is the repo I'm doing a Pull Request for.

https://github.com/DetroitJS/detroitjs-com

**Comment by AntCas** [comment] 2018-09-25 20:48
I'm encountering a similar issue when I run `gatsby develop` locally on an existing project that I haven't touched in about a month.

![captura de pantalla 2018-09-25 a la s 3 43 26 p m](https://user-images.githubusercontent.com/6935841/46041982-d348cd00-c0d9-11e8-8f4c-d9f3c21d0db1.png)

- gatsby 2.4.1 (recently upgraded)
- node v9.8.0

So far I've tried deleting `.cache` files in root and in `node_modules`, but that had no effect.

I think it's a gatsby issue not specifically a netflify issue.

**Comment by AntCas** [comment] 2018-09-25 20:51
I'm encountering a similar issue when I run `gatsby develop` locally on an existing project that I haven't touched in about a month.

![captura de pantalla 2018-09-25 a la s 3 49 57 p m](https://user-images.githubusercontent.com/6935841/46042331-ba8ce700-c0da-11e8-8a25-227a904ceac6.png)

- gatsby 2.4.1 (recently upgraded)
- node v9.8.0

So far I've tried deleting `.cache` files in root and in `node_modules`, but that had no effect.

I think it's a gatsby issue not specifically a netflify issue.

**Comment by AntCas** [comment] 2018-09-25 21:29
Probably relevant: [https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/)

(at least for my issue)

[Other similar issues to this one](https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=There+was+an+error+compiling+the+html.js+component+for+the+development+server.+)

**Comment by erquhart** [comment] 2018-10-24 02:14
I ran through the steps and couldn't reproduce the error. Make sure your global version of `gatsby` is up to date (v2). Otherwise if you have a repo that can be forked to reproduce the issue, that would help.

**Comment by AntCas** [comment] 2018-10-27 20:49
My issue was running the `develop` command for gatsby v2 on a v1 project. Two fixes worked, the first was to run v1 of `gatsby develop`, the second solution was to migrate the project to v2.

**Comment by erquhart** [comment] 2018-11-02 13:49
Closing this, but please comment if the issue persists.

**Closed by erquhart** 2018-11-02 13:49 UTC

**Comment by hiten2112** [comment] 2019-07-16 14:03
> I ran through the steps and couldn't reproduce the error. Make sure your global version of `gatsby` is up to date (v2). Otherwise if you have a repo that can be forked to reproduce the issue, that would help.

its is still error

**Comment by ZhuningS** [comment] 2019-10-28 08:34
+1

**Comment by erquhart** [comment] 2019-11-05 23:40
Need steps to reproduce - I'll reopen if you can provide them. The ones given did not reproduce this issue for me.
