### ISSUE TITLE
Documentation on running Netlify CMS sans Netlify

### ISSUE THREAD

**Issue by alfiepates** [netlify/netlify-cms#1168] opened 2018-03-11 18:45 UTC
I'm attempting to deploy Netlify CMS for my Hugo-driven site which lives on my own servers. 

The impression I get from the docs is that I need to tie into Netlify's authentication _somehow_ or run a bunch of my own infrastruture to handle the authentication, but the extent to which isn't particularly well documented. 

Is there any more information on self-hosted Netlify CMS authentication than is covered in the docs? Once I'm comfortable with the process, I'd be glad to submit a PR for a documentation page covering running Netlify CMS without depending on Netlify.

**Comment by jmo808** [comment] 2018-03-12 16:03
This has been asked about before. The problem is GitHub requires a server-side component in order to be able to do Oauth authentication. There are other implementations talked about in the Netlify CMS docs other than the git-gateway service. I used the "GitHub" backend with the node.js based GitHub auth microservice. It's ridiculously easy to deploy. I deployed a free Azure Web App then linked the GitHub repo of the node.js based auth service to the web app and then setup the environment variables with my GitHub Oath application settings. Worked the first time.

**Comment by erquhart** [comment] 2018-03-14 19:05
Yep, @jmo808 is right, that's the documented approach. Closing, but comment and I'll reopen if there's anything missing here.

**Closed by erquhart** 2018-03-14 19:05 UTC
Labels: area: auth, area: docs, kind: question

**Comment by sachin10101998** [comment] 2020-03-15 14:36
@erquhart, Could you provide me with the link for documentation on how to add Netlify-CMS sans Netlify?

**Comment by erquhart** [comment] 2020-03-15 17:02
@sachin10101998 looks like there’s a gap in the GitHub backend docs, for now I’d recommend picking an external oauth library and following their instructions, which will cover steps for authentication. Everything else works the same no matter where you deploy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erezrokah** [comment] 2020-03-16 09:16
Some more information available here:
https://github.com/netlify/netlify-cms/issues/2695#issuecomment-544863103
https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway
