### ISSUE TITLE
Slugs do not preserve capitalization

### ISSUE THREAD

**Issue by bmackinney** [netlify/netlify-cms#5491] opened 2021-06-10 15:40 UTC
**Description**
Creating entries, there are situations where I want the filename to be camelCased. I cannot achieve this without manually creating the files.

**To Reproduce**
1. Create a folder collection entry with a title or other identifier_field that is written in camelCase.

**Expected behavior**
The filename to be camelCase/preserve capitalization

**Screenshots**
![image](https://user-images.githubusercontent.com/646061/121551342-c88b0f00-c9cc-11eb-83b1-754a590646d3.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.10.138]
 - Git provider: Local
 - OS: OSX
 - Browser version [e.g. chrome 91]

**Comment by erezrokah** [comment] 2021-06-10 16:47
Hi @bmackinney, this is actually the intended behavior:
https://github.com/netlify/netlify-cms/blob/2d4cb37d639088fe948f939bc232839786caa41a/packages/netlify-cms-core/src/lib/formatters.ts#L92

I think this is covered by https://github.com/netlify/netlify-cms/issues/445, so I'm closing the issue.

I recommend adding your use case to that issue (please state the reason you require camelCased files).

**Closed by erezrokah** 2021-06-10 16:47 UTC
Labels: type: bug
