### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.This is likely a bug in Gatsby and i...

### ISSUE THREAD

**Issue by Anas-Aqeel** [netlify/netlify-cms#4810] opened 2021-01-06 20:44 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.27`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: git-gateway
media_folder: content/assets
public_folder: ../assets
collections:
  - name: social
    label: Social
    editor:
      preview: false
    files:
      - label: Social links
        name: social
        file: content/social/social.md
        fields:
          - label: Type
            name: type
            widget: hidden
            default: social
          - label: Twitter
            name: twitter
            widget: string
            default: ""
            required: false
            hint: Full link to your Twitter profile
            pattern:
              - ^http(s)?://.*..*(/)?
              - Must be a valid URL
          - label: Facebook
            name: facebook
            widget: string
            default: ""
            required: false
            hint: Full link to your Facebook page
            pattern:
              - ^http(s)?://.*..*(/)?
              - Must be a valid URL
          - label: LinkedIn
            name: linkedin
            widget: string
            default: ""
            required: false
            hint: Full link to LinkedIn profile
            pattern:
              - ^http(s)?://.*..*(/)?
              - Must be a valid URL
          - label: Email
            name: email
            widget: string
            default: ""
            required: false
            hint: Just your email address
    publish: true
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: posts
    slug: "{{slug}}"
    folder: content/posts
    publish: true
    label: Text post
    fields:
      - label: Type
        name: type
        widget: hidden
        default: text
      - label: Featured Image
        name: image
        widget: image
        required: false
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: DD MMM, YYYY
        date_format: DD MMM, YYYY
      - label: Post
        name: body
        widget: markdown
    create: true
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: videos
    slug: "{{slug}}"
    folder: content/videos
    publish: true
    label: Video post
    fields:
      - label: Type
        name: type
        widget: hidden
        default: video
      - label: Featured image
        name: image
        widget: image
        required: false
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Publish date
        name: date
        widget: datetime
        dateFormat: DD MMM, YYYY
        timeFormat: false
        date_format: DD MMM, YYYY
        time_format: false
      - label: Link to video
        name: link
        widget: string
        pattern:
          - ^http(s)?://.*..*(/)?
          - Must be a valid URL
    create: true
  - sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    meta: {}
    name: audio
    slug: "{{slug}}"
    folder: content/audio
    publish: true
    label: Audio post
    fields:
      - label: Type
        name: type
        widget: hidden
...

**Comment by erezrokah** [comment] 2021-01-07 10:43
Closing as duplicate of https://github.com/netlify/netlify-cms/issues/4004

**Closed by erezrokah** 2021-01-07 10:43 UTC
