### ISSUE TITLE
How to Limit No of Entries in a List Using Variable Types?

### ISSUE THREAD

**Issue by codeitlikemiley** [netlify/netlify-cms#4116] opened 2020-08-05 07:46 UTC
Hi The Concept of List Variable Types is Awesome,

Is there a way Where I can Specify The List Maximum Count 

Lets say i only want 1 Entry on my List , And Im Just Utiizing the The Widget for convenience of 

Giving Options to user to Either Upload an Image using image widget or use a simpe widget string for Url Link.

Is that possible?

**Comment by erezrokah** [comment] 2020-08-05 10:15
Thanks @codeitlikemiley, closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/1480

**Closed by erezrokah** 2020-08-05 10:15 UTC
