### ISSUE TITLE
Async loading issues with Relation widget

### ISSUE THREAD

**Issue by gewfy** [netlify/netlify-cms#5093] opened 2021-03-11 10:25 UTC
**Describe the bug**
When using the relation widget the async loading overwrites content when switching entry in the editor.

**To Reproduce**
1. Use an asynchronous back-end (we use GitLab)
2. Make sure the collection/entries use the relation widget
3. Open an entry in the editor
4. Afterloading quickly go back and open another
5. After the entry have loaded, wait and suddenly the content gets replaced/overwritten by the previously visited entry

**Expected behavior**
The entry content should not be overwritten

**Screenshots**
Notice the async change of content at the end

https://user-images.githubusercontent.com/474066/110772929-723af280-825c-11eb-93cd-e323a736c9ad.mp4

**Applicable Versions:**
 - Netlify CMS version: 2.14.25
 - Git provider: GitLab
 - OS: reproduced on Linux and MacOS
 - Browser version: reproduced in Firefox and Chrome
 - Node.JS version: 14

**CMS configuration**
Too big to paste here. Can add separately if needed?

**Additional context**
Might relate to #4891

**Comment by erezrokah** [comment] 2021-03-11 10:40
Hi @gewfy, I'm not sure I understand the bug. 
Can you share a repo reproducing the issue? Also the view doesn't provide the entire CMS screen so it's quite hard for me to follow what's going on.

**Comment by gewfy** [comment] 2021-03-11 10:45
👋  @erezrokah 
Sure! It will take some time to setup, but I'll get back asap.

**Comment by gewfy** [comment] 2021-03-11 13:33
@erezrokah Here's a test config fetching from a public github repo https://github.com/29ki/netlify-cms/blob/relation-async-issue/dev-test/config.yml

Jump quickly between the entries and the content from an earlier entry will popup in the "Sections" part

**Comment by delwin** [comment] 2021-09-12 07:50
We have the same issue, though this happens when switching back to the same record, too, the relationship values being asynchronously duplicated in the record. This happens in one of our collections, and it also makes use of several relationships, which link to a collection that has 135 records.

We are also currently using GitLab. This may be where the issue lies, because we didn't see this prior to moving to GitLab from GitHub, an operation we did because we were having too many issues on GitHub (429 Too Many Requests errors, and Media Library issues).

**Closed** 2021-09-13 12:57 UTC
Labels: area: extensions/backends, area: ui/editor, type: bug, area: extensions/widgets/relation, area: extensions/backends/gitlab

**Comment by erezrokah** [comment] 2021-09-13 13:15
A fix for this bug has been released in [`netlify-cms@2.10.163`](https://github.com/netlify/netlify-cms/releases/tag/netlify-cms%402.10.163)
