### ISSUE TITLE
Custom navbar button like media or workflow

### ISSUE THREAD

**Issue by Respuit** [netlify/netlify-cms#5973] opened 2021-11-10 12:08 UTC
Hello, I don't know if it's possible but for my use case I would love to be able to add a new button like the media one with custom behavior. For example, in the same way that you could link Cloudinary so it opens the Cloudinary app in a "container" I would like to do the same thing but for other apps like commerce layer for example. I'm sorry in advance if it has been answered before but I could not find a clear answer for it.

Thanks again!

**Comment by erezrokah** [comment] 2021-11-10 12:50
Hi @Respuit. Thank you for this suggestion, closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/4424.
I'll add a comment on that issue.

**Closed by erezrokah** 2021-11-10 12:50 UTC
Labels: duplicate
