### ISSUE TITLE
Cursor jumps at the end in image text boxes

### ISSUE THREAD

**Issue by stevemarksd** [netlify/netlify-cms#4539] opened 2020-11-08 05:27 UTC
**Describe the bug**

Cursor jumps in images text boxes.

**To Reproduce**

When I type in the image boxes:

![image](https://user-images.githubusercontent.com/58653359/98457873-eb9ad980-21c5-11eb-9e32-3f102d9cc99b.png)

I put cursort at the beginning and I type ABC:

![image](https://user-images.githubusercontent.com/58653359/98457876-f81f3200-21c5-11eb-849b-bae0dcad28f2.png)

This is what happens. A is at the beginning. then cursor jumps at the end and types BC. 

**Expected behavior**

Dont jump cursor.

**Applicable Versions:**

 - Netlify CMS version: `"netlify-cms-app": "2.13.1",`
 - Git provider: gitlab (AWS lightsail bitnami)

**CMS configuration**

    # https://www.netlifycms.org/docs/gitlab-backend/
    backend:
      name: gitlab
      repo: root/site.com
      branch: master
      api_root: https://mygitlab.com/api/v4
      base_url: https://mygitlab.com/
      auth_type: implicit
      app_id: 222
      auth_endpoint: oauth/authorize
    # Where to save image
    media_folder: src/content/images/cms
    # Prefix image url (gatsby-remark-relative-images staticFolderName + media_folder = image)
    public_folder: /images/cms
    publish_mode: editorial_workflow
    collections:
      - name: default
        label: Default
        folder: src/content/pages
        create: true
        media_folder: ''
        public_folder: ''
        path: '{{path}}/{{path}}'
        preview_path: '{{path}}'
        fields:
          - { name: path, label: Path, widget: 'string' }
          - { name: createdAt, label: Created Date, widget: 'datetime' }
          - { name: updatedAt, label: Last Updated Date, widget: 'datetime' }
          - { name: title, label: Title, widget: 'string' }
          - { name: description, label: Description, widget: 'string' }
          - { name: keywords, label: Keywords, widget: 'string' }
          - { name: tags, label: Tags, widget: 'list' }
          - { name: featuredImage, label: Featured Image, widget: 'image' }
          - { name: content, label: Show on home page, widget: 'boolean', default: true }
          - { name: body, label: Body, widget: 'markdown' }

Note the `path: '{{path}}/{{path}}'`. This will create pr with the name `/slug1/slug1/`, maybe having that slash breaks? but sometimes works... so should be something else.

**Additional context**

**Comment by erezrokah** [comment] 2020-11-26 15:06
Closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/3578

**Closed by erezrokah** 2020-11-26 15:06 UTC
Labels: area: extensions/widgets/markdown, good first issue, type: bug
