### ISSUE TITLE
Why appears "Unsaved changes" where is used the relation widget?

### ISSUE THREAD

**Issue by MrEfrem** [netlify/netlify-cms#1550] opened 2018-07-30 08:57 UTC
- Do you want to request a feature or report a bug?
bug

- What is the current behavior?
Shown "Unsaved changes" on entering in collection item which contains "relation" widget.

- If the current behavior is a bug, please provide the steps to reproduce.
https://cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things

- What is the expected behavior?
Must appears "Saved changes".

**Comment by tech4him1** [comment] 2018-07-30 14:39
Duplicate of https://github.com/netlify/netlify-cms/issues/725, thank you for reporting!

**Closed by tech4him1** 2018-07-30 14:39 UTC

**Comment by MrEfrem** [comment] 2018-07-30 14:42
@tech4him1 but there isn't changes for a long time. It's a bad.

**Comment by tech4him1** [comment] 2018-07-30 15:11
@MrEfrem Feel free to help work on the issue, or make a comment with any new information. We just don't want more than one issue open for a specific thing because then there is no single place for discussion.
