### ISSUE TITLE
Documentation states to use value_field and search_fields but latest version of NetlifyCMS reports missing valueFields and searchFields

### ISSUE THREAD

**Issue by kylekirkby** [netlify/netlify-cms#4283] opened 2020-09-09 15:11 UTC
**Describe the bug**
Documentation is not consistent with schema errors being reported by NetlifyCMS. 

**To Reproduce**
1. See the documentation here for the relation widget here: https://www.netlifycms.org/docs/widgets/relation/
2. Use `value_field` or `search_fields` in a relation widget and see the schema error reported.

```
Error loading the CMS configuration
Config Errors:
config should have required property 'valueField'
config should have required property 'searchFields'
Check your config.yml file.
```

**Expected behavior**
Documentation to be consistent with schema errors that are being reported. Which of the above should I use?

**Applicable Versions:**
 - Netlify CMS version: 2.10.56
 - OS: Ubuntu 20.04
 - Browser version: Chromium

**Comment by erezrokah** [comment] 2020-09-09 15:12
Thanks @kylekirkby, closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/4248

**Closed by erezrokah** 2020-09-09 15:12 UTC
Labels: type: bug
