### ISSUE TITLE
CDN URL for uploadcare needs to allow for custom URLs

### ISSUE THREAD

**Issue by panbanda** [netlify/netlify-cms#6195] opened 2022-02-07 22:23 UTC
**Is your feature request related to a problem? Please describe.**

Uploading an image with `uploadcare` doesn't allow me to set a cdnBase or cdnURL or something similar for custom URLs.  When I upload an image it is forcing the company's cdn instead.

**Describe the solution you'd like**

The settings in config.json should be something like:

```
  media_library: {
    name: 'uploadcare',
    settings: {
      autoFilename: true,
      cdnUrl: 'https://cdn.domain.com'
    }
  },
```

**Additional context**

https://uploadcare.com/docs/delivery/cdn/#custom-cdn-cname

**Comment by devnamrits** [comment] 2022-02-27 08:51
Hi, @panbanda @erezrokah It's going to be my first open-source contribution. Can you assign it to me? It would be great if a piece of detailed information can be provided on this issue.

**Comment by erezrokah** [comment] 2022-02-28 10:40
Thanks @devnamrits ❤️  From the code's perspective https://github.com/netlify/netlify-cms/blob/ded95dbea5cf9c4002d26c62dcb70676e87c5194/packages/netlify-cms-media-library-cloudinary/src/index.js#L53 is where we pass the configuration to the Cloudinary widget

**Comment by devnamrits** [comment] 2022-03-01 19:56
Hi
Can you please tell me exactly in the correct context as to what is being implemented within this issue?
I have set up the project in my local. Please provide me with the steps to reproduce the missing requirement.
Talking about issue, what I've understood till now is following:
As of now we're able to upload image in the Insert from URL but only from uploadcare URL but not from a custom CDN or URL.Right?
<img width="692" alt="Screenshot 2022-03-02 at 1 25 12 AM" src="https://user-images.githubusercontent.com/54183698/156239170-0d34848c-db64-44b1-bb39-1abb4ba56324.png">
Since CDN URLs are not free? Can you suggest any way to test it??
It would be great if you can tell me about what exactly should happen within the app in frontend after developing this feature.
cc: @erezrokah @panbanda

**Comment by erezrokah** [comment] 2022-03-02 14:09
Hi @devnamrits, you'll need to follow the steps in https://www.netlifycms.org/docs/cloudinary/ to configure the CMS with Cloudinary. Once you've done that, you should see how to pass `cdnUrl` to the Cloudinary widget.

Please let me know if that helps.

**Comment by devnamrits** [comment] 2022-03-03 03:18
Hi @erezrokah , Thanks for your kind reply. As you're saying I've to figure out how to pass CDN URL for the cloudinary widget but here the request is for uploadcare-media-library. So I need to develop it within uploadcare-media-library that allows passing custom CDN URL in uploadcare-media-library rather than cloudinary-media-library. Right?

**Comment by devnamrits** [comment] 2022-03-05 03:00
Hi @erezrokah, I went through the code and changed my config.yml to set uploadcare with netlify cms.

Now coming to the issue: To set custom CDN name in uploadcare is a premium feature as shown in attached image.

<img width="1395" alt="Screenshot 2022-03-05 at 7 55 20 AM" src="https://user-images.githubusercontent.com/54183698/156864351-efec1880-75ef-497e-961a-94ab1654cee8.png">

So, I'm unable to test.

```
media_library:
  name: uploadcare
  config:
    publicKey: 044891012b775d10af4c
    cdnBase: https://example.basecdn.com
```
But I think just setting an extra param in config.yml, as shown above, will  work because of the following reason:

1.  In the widget options, as the docs say we can set value with key. For example, `cdnBase: https://example.basecdn.com`.
2. I had tried to do so and got the following result:
<img width="1427" alt="Screenshot 2022-03-05 at 8 20 30 AM" src="https://user-images.githubusercontent.com/54183698/156865030-b702a3a6-58b3-4b52-897f-4ae016e3eaf7.png">

As you can see when, here uploadcare widget tries to upload to the `cdnBase: https://example.basecdn.com`, but it gets an 404 error which is quite obvious because there is no such cdn that exists in my account. And to test, premium account features will be needed, which I don't have.

Also, if you also think it will work, I would love to add this `cdnBase: https://example.basecdn.com` in the uploadcare plugin docs.

Please confirm!

cc: @panbanda

**Comment by devnamrits** [comment] 2022-03-05 03:09
Hi @erezrokah, I went through the code and changed my config.yml to set uploadcare with netlify cms.

Now coming to the issue: To set custom CDN name in uploadcare is a premium feature as shown in attached image.

<img width="1395" alt="Screenshot 2022-03-05 at 7 55 20 AM" src="https://user-images.githubusercontent.com/54183698/156864351-efec1880-75ef-497e-961a-94ab1654cee8.png">

So, I'm unable to test.

```
media_library:
  name: uploadcare
  config:
    publicKey: XXXXXXXXXXXXXXXXX
    cdnBase: https://example.basecdn.com
```
But I think just setting an extra param in config.yml, as shown above, will  work because of the following reason:

1.  In the widget options, as the docs say we can set value with key. For example, `cdnBase: https://example.basecdn.com`. The doc link: `https://uploadcare.com/docs/uploads/file-uploader-options/#option-cdn-base`
2. I had tried to do so and got the following result:
<img width="1427" alt="Screenshot 2022-03-05 at 8 20 30 AM" src="https://user-images.githubusercontent.com/54183698/156865030-b702a3a6-58b3-4b52-897f-4ae016e3eaf7.png">

As you can see when, here uploadcare widget tries to upload to the `cdnBase: https://example.basecdn.com`, but it gets an 404 error which is quite obvious because there is no such cdn that exists in my account. And to test, premium account features will be needed, which I don't have.

Also, if you think that it will work as well then I would love to add `cdnBase: https://example.basecdn.com` thing in the uploadcare widget docs.

Please confirm!

cc:  @panbanda

**Comment by devnamrits** [comment] 2022-03-07 03:45
Hi @erezrokah, Any updates??

**Comment by erezrokah** [comment] 2022-03-07 10:10
Hi @devnamrits, this looks great. How about opening a PR for it?
It would make it easier to @panbanda to test it.

**Comment by devnamrits** [comment] 2022-03-07 10:29
Hi @erezrokah , I haven't made any changes, Just added the following

```
media_library:
  name: uploadcare
  config:
    publicKey: XXXXXXXXXXXXXXXXX
    cdnBase: https://example.basecdn.com
```

in the following place within code

https://github.com/netlify/netlify-cms/blob/1e23247b068c70dbca949c712dabdf6f9288b5f9/dev-test/config.yml#L8

So, should I raise a PR for it as it depends upon the user how he/she wants to configure netlify-cms either with cloudinary or upload care.

**Comment by erezrokah** [comment] 2022-03-07 10:37
Ah, cool so it should "just work"? @panbanda, can you try ⬆️

**Comment by devnamrits** [comment] 2022-03-07 10:40
@erezrokah Meanwhile can you assign me some other issue? I would love to work on as other good first issues are being already assigned to someone or some has already open PRs.

**Comment by erezrokah** [comment] 2022-03-07 10:45
Thanks @devnamrits, you can use this filter https://github.com/netlify/netlify-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee to look at unassigned good first issues, and chose whatever you find interesting.

**Comment by devnamrits** [comment] 2022-03-07 10:48
Okay great! Picking things up then.

**Closed** 2022-03-07 11:01 UTC
Labels: good first issue, area: extensions/media-libraries, type: feature
