### ISSUE TITLE
Markdown Editor, RichText on, remove an added component?

### ISSUE THREAD

**Issue by apolopena** [netlify/netlify-cms#3532] opened 2020-04-02 20:25 UTC
Is there anyway to remove a component added to the markdown editor via the 'add component' button without changing the state of the editor back to "markdown" mode and then manually removing the string that was created by adding the component in the first place?

I have a feeling the answer is 'no' but I thought I would ask just in case.

**Comment by tomrutgers** [comment] 2020-04-02 21:25
Closing as a duplicate of #3531

**Closed by tomrutgers** 2020-04-02 21:25 UTC
