### ISSUE TITLE
TypeError: r.toJS is not a function

### ISSUE THREAD

**Issue by melat0nin** [netlify/netlify-cms#3806] opened 2020-05-25 12:53 UTC
**Describe the bug**
Trying to add a new post to a collection, the form appears for a second before `TypeError: r.toJS is not a function` is shown.

**Expected behavior**
I see the form for the new post

**Screenshots**
![image](https://user-images.githubusercontent.com/912688/82814380-f8817600-9e8e-11ea-8409-9a2416583f1d.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.49`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0`

**CMS configuration**
```
public_folder: /assets/images/uploads
media_folder: assets/images/uploads
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
display_url: https://www.url.com
publish_mode: simple
backend:
  name: git-gateway
  branch: master
  identity_url: https://www.url.com/.netlify/identity
  gateway_url: https://www.cohubicol.com/.netlify/git
  squash_merges: true
collections:
  - name: pages
    label: Pages
    folder: _pages
    create: false
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Address
        name: permalink
        widget: string
      - label: Header image
        name: header
        widget: object
        fields:
          - label: Header image
            name: overlay_image
            widget: image
            required: false
          - label: Header image caption
            name: caption
            widget: string
            required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Page layout
        name: classes
        widget: string
        required: false
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
  - name: about
    label: About section pages
    folder: _pages/about
    create: false
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Address
        name: permalink
        widget: string
      - label: Header image
        name: header
        widget: object
        fields:
          - label: Header image
            name: overlay_image
            widget: image
            required: false
          - label: Header image caption
            name: caption
            widget: string
            required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Page layout
        name: classes
        widget: string
        required: false
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
  - name: news
    label: News
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: relation
        collection: research-team
        displayFields: name
        valueField: name
        searchFields: name
        required: false
      - label: Publish Date
        name: date
        widget: datetime
        timeFormat: false
      - label: Tags
        name: tags
        widget: select
        multiple: true
        options:
          - Publications
          - Presentations
          - Events
          - Related projects
          - Recruitment
          - Teaching
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Categories
        name: categories
        widget: hidden
        default:
          - news
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
  - name: blog
    slug: "{{slug}}"
    folder: _blog
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
    label: Blog
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: blog_post
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: re
...

**Comment by erezrokah** [comment] 2020-05-25 13:03
Hi @melat0nin, closing as duplicate of https://github.com/netlify/netlify-cms/issues/3787
See comment https://github.com/netlify/netlify-cms/issues/3787#issuecomment-631323687

**Closed by erezrokah** 2020-05-25 13:03 UTC

**Comment by melat0nin** [comment] 2020-05-25 13:09
Thank you!
