### ISSUE TITLE
Guide to implement own authentication system.

### ISSUE THREAD

**Issue by sumanthyedoti** [netlify/netlify-cms#4455] opened 2020-10-12 03:54 UTC
If I don't want to use Netlify's Identity(*as I am not hosting the website on Netlify*) or Github/GitLab's oAuth, and I want to implement a simple Auth system for Netlify CMS just to authorize content editors, how to do that? 

Please suggest any alternatives to achieve this. Thanks.

**Comment by erezrokah** [comment] 2020-10-12 10:56
Hi @sumanthyedoti, please see https://www.netlifycms.org/docs/external-oauth-clients/ and the Pulumi blog post here https://www.netlifycms.org/docs/examples/

Closing as I believe we have sufficient content in our docs. Please comment if those examples do not solve your use case.

**Closed by erezrokah** 2020-10-12 10:56 UTC
Labels: type: feature

**Comment by mmm8955405** [comment] 2021-12-13 19:00
I don't think there is enough information to achieve simple certification,

**Comment by mmm8955405** [comment] 2021-12-13 19:04
> Hi @sumanthyedoti, please see https://www.netlifycms.org/docs/external-oauth-clients/ and the Pulumi blog post here https://www.netlifycms.org/docs/examples/
> 
> Closing as I believe we have sufficient content in our docs. Please comment if those examples do not solve your use case.

These links you send are useless. I don't need GitHub, and I have my own server. I just want to edit my static website through a simple password. It hurts me to see your information

**Comment by mmm8955405** [comment] 2021-12-13 19:08
I don't know how many problems should be caused by identity authentication. Obviously, your identity authentication design is rubbish

**Comment by erezrokah** [comment] 2021-12-13 19:30
Hi @mmm8955405, I've hidden your comments as they don't follow our [code of conduct](https://github.com/netlify/netlify-cms/blob/a9e5488a489acd4805533c6ead2a46922cea7f99/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct).

I recommend opening a new issue to outline the problem you're experiencing.
