### ISSUE TITLE
Cannot edit markdown from mobile device

### ISSUE THREAD

**Issue by RoseannaM** [netlify/netlify-cms#2742] opened 2019-10-11 21:30 UTC
**Describe the bug**
Cannot edit markdown from mobile device

**To Reproduce**
Open cms admin and add text in a component's markdown it immediately errors. 

**Expected behavior**
Editing of markdown does not throw and error.

**Screenshots**
![Screenshot_20191011-141044~2](https://user-images.githubusercontent.com/13283020/66686153-5aa8a600-ec33-11e9-8d64-4961d858fed2.png)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms@^2.9.6
 - Git provider: Git
 - OS: Pixel2 Android 9
 - Browser version: Chrome

**CMS configuration**
https://github.com/RoseannaM/jam/blob/master/static/admin/config.yml

**Additional context**
Not a huge issue. I'm pushing my limits by trying to edit stuff on my phone tbh...😅

**Comment by tomrutgers** [comment] 2019-10-20 13:56
The CMS isn't optimized for mobile usage yet. Closing this as duplicate of https://github.com/netlify/netlify-cms/issues/441

**Closed by tomrutgers** 2019-10-20 13:56 UTC
