### ISSUE TITLE
Open authoring beta later than beta.0 giving error on login

### ISSUE THREAD

**Issue by alexearnshaw2019** [netlify/netlify-cms#2755] opened 2019-10-16 13:12 UTC
**Describe the bug**
When I try to login with GitHub using an account that has no write access to the repo I am getting an error "Your GitHub user account does not have access to this repo."

**To Reproduce**
Set the Netlify CMS version to any beta version other than 0 (I've tried 2.9.8-beta.4, 2.9.8-beta.3, 2.9.8-beta.2, 2.9.8-beta.1) and try to login to admin page with a Github account that doesn't have write access. 

**Expected behavior**
The behavior should be the same as for beta.0 version - I am asked if I want to fork the repo.

**Screenshots**
beta.0
![image](https://user-images.githubusercontent.com/50668249/66921612-7e962e00-f01d-11e9-8275-fe26990cfd06.png)
beta.4
![image](https://user-images.githubusercontent.com/50668249/66921641-8950c300-f01d-11e9-8c9d-b06ed566def5.png)

**Applicable Versions:**
 - Netlify CMS version: 2.9.8-beta.4 (also tested on beta.3,  beta.2, beta.1)
 - Git provider: GitHub
 - OS: Windows 10 18.03
 - Browser version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**CMS configuration**
(master config)
https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.yml
https://github.com/Axway/axway-open-docs/blob/master/static/admin/index.html

(branch config where I've updated version to beta.4)
 https://github.com/Axway/axway-open-docs/blob/cmsversion_editbutton/static/admin/config.yml
https://github.com/Axway/axway-open-docs/blob/cmsversion_editbutton/static/admin/index.html

**Additional context**
This deploy preview uses beta.4 and does not work https://deploy-preview-143--axway-open-docs.netlify.com/admin
This production deploy uses beta.0 and does work https://axway-open-docs.netlify.com/admin/

**Comment by alexearnshaw** [comment] 2019-10-21 11:14
Closing this issue as it turned out to be a config issue and not a bug.

For anyone who encounters similar problem, here's the cause:

For beta.0 the field for open authoring in config.yml file was
`fork_workflow: true`

For all subsequent betas the field is called:
`open_authoring: true`

So I had a mismatch when I was trying to use beta.4 as I was still using `fork_workflow: true`

**Closed** 2019-10-21 11:15 UTC

**Comment by erquhart** [comment] 2019-11-05 21:34
Ah, good catch, thanks for sharing the solution 👍
