### ISSUE TITLE
Able to set path to upload folders directly on widgets

### ISSUE THREAD

**Issue by delanyodevio** [netlify/netlify-cms#4706] opened 2020-12-11 02:59 UTC
In my NetlifyCMS config file, I have the following:

Globally:
`media_folder: "src/images/upload"`
`public_folder: "images/upload"`

Then in the my **collections** under **fields**, I can do something like this:

`{label: "Upload Image", name: "image", widget: "image" }`

`{label: "Upload PDF", name: "pdf", widget: "file" }`

Per this configuration, when I published a content, both the PDF file and the image file would be uploaded to **src/images/upload**. Which is fine.

---

But I believe this feature can be made better by specifying **path to upload folders** directly on widgets.

For instance:

After specifying **media_folder** and **public_folder** globally, we can also do this:

1. `{label: "Upload Image", name: "image", widget: "image" }`

1. `{label: "Upload PDF", name: "image", widget: "file", path: "/path/to/upload" }`

The first one will default to the global setting, which is the path to the **public_folder** (or **media_folder**).

The second one will now take the new path being specified on its widget, which is now its own **path**.

This is because, on most occasions, we do separate images from other assets. Even most developers would love separating some images from others.

**Comment by erezrokah** [comment] 2020-12-13 08:39
Hi @delanyodevio thank you for opening this issue. I believe this is a duplicate of https://github.com/netlify/netlify-cms/issues/3201 and is already implemented, just not documented https://github.com/netlify/netlify-cms/issues/3671

There is a PR that tries to improve that https://github.com/netlify/netlify-cms/pull/4705

**Closed by erezrokah** 2020-12-13 08:39 UTC
Labels: duplicate, type: feature
