### ISSUE TITLE
Blog post example doesn't work without meta charset utf-8 

### ISSUE THREAD

**Issue by hanoii** [netlify/netlify-cms#844] opened 2017-11-26 21:54 UTC
I stumbled upon your blog post on HN and after going over your first steps It didn't work, I was getting:

```
Uncaught SyntaxError: Invalid regular expression: /[Ã€-ÃŸ][Â€-Â¿]|[Ã -Ã¯][Â€-Â¿]{2}|[Ã°-Ã·][Â€-Â¿]{3}/: Range out of order in character class
    at new RegExp (<anonymous>)
    at base64.js:89
    at Object.<anonymous> (base64.js:194)
    at t (bootstrap 4f21d447dcc951a32fbe:19)
    at Object.<anonymous> (_hasUnicode.js:23)
    at t (bootstrap 4f21d447dcc951a32fbe:19)
    at Object.<anonymous> (netlify_logo.svg:1)
    at t (bootstrap 4f21d447dcc951a32fbe:19)
    at Object.<anonymous> (_has.js:3)
    at t (bootstrap 4f21d447dcc951a32fbe:19)
```

on the console.

I then went here and added your quickstart steps and I got it running, but I think the blog post needs fixing.

**Comment by erquhart** [comment] 2017-11-28 16:35
Hmm interesting - how can I reproduce?

**Comment by tech4him1** [comment] 2017-11-28 17:09
@erquhart I've ran into this issue before as well. If you just copy the `index.html` code from [A Complete CMS with No Server and 18 Lines of Code](https://www.netlify.com/blog/2017/08/17/a-complete-cms-with-no-server-and-18-lines-of-code/), it doesn't work until you add a `<meta charset="utf-8">` line to the head.

**Comment by erquhart** [comment] 2017-11-29 02:39
Very interesting, I ran that code at the time (originally written in like June), maybe I added the meta and didn't think about it.

**Comment by erquhart** [comment] 2017-11-29 03:17
Still can't reproduce, used the exact code from the blog post.

**Comment by tech4him1** [comment] 2017-11-29 03:22
So I just took this code:
```html
<head>
  <link href="https://unpkg.com/netlify-cms/dist/cms.css" rel="stylesheet"/>
</head>
<body>
  <script src="https://unpkg.com/netlify-cms/dist/cms.js"></script>
</body>
```
put it in an HTML file, opened the file in Chrome, and I get the error.

**Comment by tech4him1** [comment] 2017-11-29 03:24
@erquhart I wasn't using the node server either, just opening the file in chrome.

**Comment by tech4him1** [comment] 2017-11-29 04:00
@erquhart I think I found the issue: If a server is used (like the `http-server` in your blog post) that sets the header `content-type:text/html; charset=UTF-8`. If the file is just opened directly in the browser, no charset is set, unless the file defines it via a `<meta>` tag.

**Comment by erquhart** [comment] 2017-11-29 04:09
Oh okay. The post specifies that a server must be used, I'd say won't fix.

**Closed by erquhart** 2017-11-29 04:09 UTC
Labels: unconfirmed

**Comment by tech4him1** [comment] 2017-11-30 15:44
@erquhart I'm guessing this could happen on some servers as well -- not all may set UTF-8 by default. I don't know if it would be worth adding a note under the "other servers" section to the effect that it must serve as UTF-8. Most people are going to figure this out, though, so it's probably not a big deal.

**Comment by erquhart** [comment] 2017-11-30 16:05
Good point, I'll update the post.

**Comment by hanoii** [comment] 2017-11-30 16:48
If you are going to modify, rather than a note, I would change the initial snippet to a full index.html including the meta charset. It's much quicker entry point for anyone quickly scanning through it.
