### ISSUE TITLE
Not working on IE 11

### ISSUE THREAD

**Issue by pungggi** [netlify/netlify-cms#972] opened 2017-12-29 06:51 UTC
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
Not working on IE 11
**- What is the expected behavior?**
IE 11 still has ove 3% in market share. would be nice to have it on board.
**- Please mention your CMS, node.js, and operating system version.**
1.0.3

**Comment by tech4him1** [comment] 2017-12-29 14:47
@pungggi Our reasoning for not trying to support IE11 can be found here: https://github.com/netlify/netlify-cms/issues/695#issuecomment-336918050. We didn't feel it was worth adding a large amount of special polyfills and other code in order just to support IE11, since it's  market share seems to be decreasing. It would have required reworking some major parts of the CMS that work in other main browsers.

Duplicate of #695

**Closed by tech4him1** 2017-12-29 14:47 UTC
