### ISSUE TITLE
Config templates/partials

### ISSUE THREAD

**Issue by pmpinto** [netlify/netlify-cms#4519] opened 2020-10-30 16:47 UTC
**Is your feature request related to a problem? Please describe.**
Kind of… Let's say you have multiple collections in your config file. And 2 of them share the exact same structure. Currently, we have to duplicate all the `fields` from one to another. Ideally, we would create a `_config-partial.yml` which could then be referred to multiple times across `config.yml`.

Why:
* Reusability — Prevents repetition of fields configs that are exactly the same for multiple collections.
* Maintainability — Huge config files are never pretty to maintain. Smaller chunks would make for easier maintenance. 

**Describe the solution you'd like**
Some way to refer to a file structure, for instance:
```yml
# config.yml
collections:
  - name: 'my_collection'
    label: 'My collection'
    folder: '_things'
    fields_partial: './configs/_title_url.yml'
```

```yml
# _title_url.yml
fields:
  - name: 'title'
    # …
  - name: 'url'
    # …
```

**Describe alternatives you've considered**
Alternatively, and for ultimate maintainability, but perhaps harder to implement would be to allow for something like this _anywhere_ in `config.yml`:
```yml
# config.yml
collections:
  config_partial: './configs/_my_collection.yml'
```

```yml
# _my_collection.yml
- name: 'my_collection'
  label: 'My collection'
  folder: '_things'
  config_partial: '_title_url.yml' # same file as above
```

**Comment by ChrisLasar** [comment] 2020-10-31 05:19
In the meantime YAMLs alias nodes might d the job (https://yaml.org/spec/1.2/spec.html#id2786196)

**Comment by tomrutgers** [comment] 2020-10-31 09:56
Related to (and quite possibly a duplicate of) #1342

**Comment by erezrokah** [comment] 2020-11-01 09:38
This is covered an #1342 and there are possible solutions in that issue

**Closed by erezrokah** 2020-11-01 09:38 UTC
Labels: type: feature

**Comment by pmpinto** [comment] 2020-11-02 18:55
@ChrisLasar That was not exactly what I wanted, but that's what I needed now.
At least until we have #1342 merged in, this is going to be _really_ helpful!

Thanks! Have some 🍰
