### ISSUE TITLE
UI glitch for Relation Widget in Firefox

### ISSUE THREAD

**Issue by ouarez** [netlify/netlify-cms#824] opened 2017-11-17 07:34 UTC
![netlify-cms-relationship-widget-ui-bug-2](https://user-images.githubusercontent.com/25655587/32935736-60a1c882-cb3f-11e7-96dd-1e88467354ad.png)

![netlify-cms-relation-widget-ui-bug](https://user-images.githubusercontent.com/25655587/32935667-2444803c-cb3f-11e7-8c58-4ec83b33d58c.png)
**- Do you want to request a *feature* or report a *bug*?**

I am reporting a bug.

**- What is the current behavior?**

The Relation Widget's input field, inside the CMS, is strangely garbled. It works fine in Chrome, but in Firefox it's impossible to read the text inside the field (see screenshot)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Add a relationship widget to a Field inside config.yml. Open up the Admin UI in Firefox.

**- What is the expected behavior?**

Should be able to read the text inside the relationship widget field.

**- Please mention your CMS, node.js, and operating system version.**

My Firefox version is 56.0 (64-bit)
My Desktop is Fedora 26. I'll try testing this on different OS and browser versions ASAP.
The CMS is deployed using Netlify, and the bug persists, so it's not a local-specific problem.
Netlify CMS version is 0.7.0

And here is the ruby and node version from the deploy log:

2:19:27 AM: Using version v6.12.0 of node
2:19:28 AM: Using /opt/buildhome/.rvm/gems/ruby-2.1.2

--

I couldn't find this issue reported anywhere else.
.. Maybe it's just my version of Firefox?
 If so, accept my apologies and feel free to close this issue.

Other than that, I love this project and please, keep up the good work!

You're building the future of web development :+1:

**Comment by tech4him1** [comment] 2017-11-17 21:22
Reproduced in Firefox 56.0.2 on Windows 10 Fall Creators Update.

**Comment by Benaiah** [comment] 2017-11-17 21:48
I've also seen this show up in FF.

**Comment by erquhart** [comment] 2017-11-17 22:10
This will be addressed in the 1.0 RC.

Bug: https://cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things
Fixed: https://global-ui--cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things

Leaving open until fixed in a release.

**Comment by tech4him1** [comment] 2017-11-17 22:24
Looks like the only reason is that the height is manually set to `30px` instead of just leaving the default.

**Comment by ouarez** [comment] 2017-11-19 08:11
Thanks for the feedback.

I'll try to tweak height using CSS in the meantime.

Cheers

**Comment by erquhart** [comment] 2017-12-09 06:53
Fixed in 1.0.

**Closed by erquhart** 2017-12-09 06:53 UTC
Labels: bug, in progress
