### ISSUE TITLE
CMS Search & Relation Widget – fails – with large projects

### ISSUE THREAD

**Issue by neilkinnish** [netlify/netlify-cms#2961] opened 2019-12-12 10:45 UTC
Description: 

I have a large project with 3 collections, two of the collections have over 2k items each. The backend is Github and I am using the `use_graphql: true` – which has helped to some extent as these issues were worse before.

But I'm noticing the site search can not find some items within the collections and the relation widget has the same issue which I am assuming is connected. 

The site search is not a massive issue, but the relation widget is a problem, if you can't find the item you can't save a relationship.

CMS version is `2.9.7`

Has anyone experienced this issue? any workarounds or ideally fixes?

**Comment by neilkinnish** [comment] 2019-12-12 10:54
**UPDATE** (additional info):

Regarding relationships, if you manually add the relationship to the MD file via GitHub, the CMS still does not list the relationship in the relation field even though it exists.

**Comment by tomrutgers** [comment] 2019-12-12 10:57
Can you share your `config.yml`?

**Comment by neilkinnish** [comment] 2019-12-12 11:33
@tomrutgers sure (removed some info)

``` 
backend:
  name: github
  repo: github/repo/address
  branch: master
  base_url: custom/auth/url
  auth_endpoint: /auth
  use_graphql: true

site_id: sitename
logo_url: /cms-logo.png
show_preview_links: false
display_url: https://sitename.com
site_url: https://sitename.com

public_folder: /img
media_library:
  name: uploadcare
  effectsTab: true
  config:
    publicKey: public-key

publish_mode: editorial_workflow

collections:

  - name: home-headers
    label: Home Headers
    folder: content/home-headers
    create: true
    summary: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: Headline, name: title, widget: string }
      - { label: Description, name: body, widget: markdown, buttons: [link] }
      - { label: Image, name: background_image, widget: image }

- name: issues
    label: Issues
    folder: content/issues
    create: true
    editor:
      preview: false
    summary: '{{title}} - {{content_title}} - {{month}}.{{day}}.{{year}}'
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Content Title,
          name: content_title,
          widget: string,
          required: false,
        }
      - { label: Description, name: body, widget: markdown }
      - {
          label: Featured Media,
          name: featured_media,
          widget: object,
          required: true,
          fields:
            [
              {
                label: Hero Image,
                name: hero_image,
                widget: image,
                hint: 'Upload / Select Image',
                required: true,
                allow_multiple: false,
              },
              {
                label: Header Image,
                name: header_image,
                widget: image,
                hint: 'Upload / Select Image',
                required: true,
                allow_multiple: false,
              },
            ],
        }
      - {
          label: Publish Date,
          name: date,
          widget: datetime,
          dateFormat: YYYY-MM-DD,
          timeFormat: false, # HH:mm,
          format: YYYY-MM-DD HH:mm,
        }
      - {
          label: Regions,
          name: regions,
          widget: select,
          options: ['Southern CA', 'Northern CA'],
          multiple: true,
        }
      - {
          label: Display Region,
          name: display_region,
          widget: string,
          required: false,
          hint: 'Just for display purposes on an issue page',
        }
      - {
          label: Selected Stories,
          name: selected_stories,
          widget: relation,
          collection: stories,
          searchFields: ['title', 'content_title', 'id'],
          valueField: id,
          displayFields: ['title'],
          multiple: true,
          required: false,
          hint: 'Search with the title or content title (displayed by title)',
        }
      - {
          label: Issue Type,
          name: issue_type,
          widget: select,
          options: ['standard', 'listicle', 'listicle_editor'],
          required: true,
          hint: 'Standard & Listicle uses selected stories, editor is freetext',
        }

  - name: stories
    label: Stories
    folder: content/stories
    create: true
    summary: '{{title}} - {{content_title}} - {{month}}.{{day}}.{{year}}'
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Content Title,
          name: content_title,
          widget: string,
          required: false,
        }
      - {
          label: Unique Identifier,
          name: id,
          widget: ncw-id,
          hint: Automatically generated unique read-only id,
        }
      - {
          label: Publish Date,
          name: date,
          widget: datetime,
          dateFormat: YYYY-MM-DD,
          timeFormat: false, # HH:mm,
          format: YYYY-MM-DD HH:mm,
        }
      - {
          label: Summary,
          name: excerpt,
          widget: string,
          required: false,
          hint: 'Please limit to 300 characters max',
        }
      - { label: Story, name: body, widget: markdown }
      - {
          label: Featured Media,
          name: featured_media,
          widget: object,
          required: true,
          fields:
            [
              {
                label: Hero Image,
                name: hero_image,
                widget: image,
                hint: 'Upload / Select Image',
                required: true,
                allow_multiple: false,
              },
              {
                label: Summary Image,
                name: summary_image,
                widget: image,
                hint: 'Upload / Select Image',
                required: true,
                allow_multiple: false,
              },
              {
                label: Video,
                name: video,
                widget: file,
                hint: 'Upload / Select Video',
                required: false,
                allow_multiple: false,
              },
            ],
        }
      - {
          label: Regions,
          name: regions,
          widget: select,
          default: 'Northern CA',
          options: ['Northern CA', 'Southern CA'],
          multiple: true,
        }
      - {
          label: Location,
          name: location,
          widget: select,
          required: false,
          options:
            [
              'Los Angeles County',
              'Orange County',
              'San Diego County',
              'Ventura County',
              'Inland Empire',
              'Deserts',
              'Greater California',
              'Points Beyond',
              'San Francisco',
              'East Bay',
              'North Bay',
              'Peninsula & South Bay',
            ],
        }
      - {
          label: Categories,
          name: categories,
          widget: relation,
          collection: categories,
          searchFields: ['name'],
          valueField: name,
          displayFields: ['name'],
          multiple: true,
          required: false,
        }
      - {
          label: Sponsorship,
          name: sponsorship,
          widget: object,
          required: false,
          hint: 'Adding sponsorship details will flag this story as a sponsored story',
          fields:
            [
              { label: Active, name: active, widget: boolean, default: false },
              { label: Name, name: name, widget: string, required: false },
              {
                label: Freetext,
                name: freetext,
                widget: string,
                required: false,
              },
              {
                label: Link / URL,
                name: link,
                widget: string,
                required: false,
              },
            ],
        }

  - name: categories
    label: Categories
    folder: content/categories
    create: false
    editor:
      preview: false
    summary: '{{name}}'
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Description, name: description, widget: markdown }
      - { label: Image, name: image, widget: image }

  ```

**Comment by tomrutgers** [comment] 2019-12-12 12:05
Are you experiencing this issue with all of your relation widgets?

**Comment by neilkinnish** [comment] 2019-12-12 12:08
Just the relation widget which uses the stories collection (1.2k+ items in this collection), I only have one other relation widget, but this is for categories and its a much smaller collection.

The site search is also failing to find exactly the same items – so I'm assuming it's related.

**Comment by barthc** [comment] 2019-12-12 12:17
@neilkinnish  what's your CMS version. I think your issue is related to #2406, which has been fixed.

**Comment by neilkinnish** [comment] 2019-12-12 12:23
@barthc version is 2.9.7

I was in the other issue and it did definitely help adding the `use_graphql: true` as the issue was worse before, but now I am seeing this again. Unless you think one of the beta versions has a fix?

**Comment by neilkinnish** [comment] 2019-12-13 12:09
@barthc @tomrutgers did you have any ideas, not sure how best to proceed?

**Comment by barthc** [comment] 2019-12-13 12:25
Forgot to ask, when you visit the entries collection page do you see all 1.2k + items?

**Comment by neilkinnish** [comment] 2019-12-13 12:29
@barthc I can see from the console it's doing a lot of work to load in all the items, but no I think it's missing some. Checking the XHR requests it also seems to be missing some.

**Comment by barthc** [comment] 2019-12-13 12:36
I would need you to test with the most recent beta version without using the `use_graphql: true` which also have a fix for the post limit.

**Comment by neilkinnish** [comment] 2019-12-13 19:56
@barthc beta appears to solve the issue – thanks.

**Comment by neilkinnish** [comment] 2019-12-13 19:57
@barthc should I definitely not use `use_graphql: true` though?

**Comment by barthc** [comment] 2019-12-13 22:13
> should I definitely not use use_graphql: true though?

I think there is an issue with `graphql` post limit, but @erezrokah  ran some test [here](https://github.com/netlify/netlify-cms/issues/2406#issuecomment-551178387)  and confirmed that over 1k + items were returned.  I guess we need to test the `graphql` query post limit again to confirm.

**Comment by erezrokah** [comment] 2020-01-13 14:12
I created a repo to simulate the issue:
https://github.com/erezrokah/netlify-cms-relation-widget/tree/master/content/stories
It has 3000 stories (tried 5000 at first but got hit by GitHub API limit).

I was able to search with `use_graphql: true` and `use_graphql: false`:

![image](https://user-images.githubusercontent.com/26760571/72262070-d3e2db00-361e-11ea-89db-8a864038211b.png)

But I had to wait for all the stories to load first into the local cache before I could do anything.
I think the next step to improve on this is to add pagination support for GitHub but that's for another issue.

**Comment by erezrokah** [comment] 2020-01-13 17:32
Closing this, please re-open if necessary

**Closed by erezrokah** 2020-01-13 17:32 UTC

**Comment by neilkinnish** [comment] 2020-01-13 18:17
@erezrokah Is 5k a hard limit for collections due to the github limits?

If so, having the ability to sort collections or list by date would be useful.

**Comment by erezrokah** [comment] 2020-01-13 19:08
GitHub API has a [limit](https://developer.github.com/v3/#rate-limiting) of requests per hour of 5000.
I reached the limit since I didn't have any of the files cached locally so on initial load the CMS had to download all of them. We might be able to use the GraphQL API to batch file downloads, but regardless we should look into pagination like the other backends.

As for sorting, I completely agree and we have an issue for that https://github.com/netlify/netlify-cms/issues/54

**Comment by neilkinnish** [comment] 2020-01-13 21:21
Thanks for the update 👍
