### ISSUE TITLE
Image widget broken src

### ISSUE THREAD

**Issue by alexandernanberg** [netlify/netlify-cms#2295] opened 2019-04-18 08:24 UTC
**Describe the bug**

The ImageWidget preview src is broken eg `/media/uploads/filename.jpg`. But the images in the media archive works and they use the full github url`https://raw.githubusercontent.com/user/repo/master/content/media/uploads/filename.jpg`

**To Reproduce**

Use configuration below and upload images

**Expected behavior**

To use the full URL like the media library does

**Screenshots**

N/A

**Applicable Versions:**

 - Netlify CMS version: 2.7.0
 - Git provider: GitHub

**CMS configuration**

```
media_folder: content/media/uploads
```

**Additional context**

N/A

**Comment by davejm** [comment] 2019-04-27 18:40
Adding to this. It would be very useful if the image widget preview used the full git URL like the media library. This would remove the requirement of putting your raw images in the static folder - something that many people would probably like to avoid seen as something like gatsby-sharp can remove metadata for published images. Sorry if there is another issue open relating to this. I couldn't find an exact one and this is closest.

**Comment by erquhart** [comment] 2019-05-09 18:02
The image widget expects the CMS to be deployed in production alongside production assets, but I agree that's not an assumption we should be making. Pulling through the API is ideal.

**Comment by erquhart** [comment] 2019-11-16 20:24
Related to #990.

**Comment by erezrokah** [comment] 2019-11-17 08:06
@erquhart can we mark this as a duplicate of https://github.com/netlify/netlify-cms/issues/1750

**Comment by erquhart** [comment] 2019-11-17 15:11
Yeah that works

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2019-11-17 15:11 UTC
Labels: area: extensions/widgets, duplicate, kind: enhancement
