### ISSUE TITLE
Netlify CMS Media uploader API error on large(ish) filesPlease replace with a clear and descriptive title

### ISSUE THREAD

**Issue by alexknowshtml** [netlify/netlify-cms#6157] opened 2022-01-24 19:38 UTC
**Describe the bug**
I have a site that’s working great with Netlify CMS, except one of the upload fields includes video files. They aren’t very big, under 20megs so also under Github’s “large media” threshold, but either way (with large media or not) we are getting this error:

![c85da1987680354fb2cd1ae6000c579f9daf0db1](https://user-images.githubusercontent.com/3707/150851758-40d7cd55-aa89-47d6-ba4c-c868d334f229.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: Github
 - OS: Mac OS 12.1
 - Browser version: Chrome Version 97.0.4692.99 (Official Build) (x86_64)

**CMS configuration**
backend: 
  name: github
  repo: [repo redacted]
  branch: main

media_folder: "assets/uploads"

collections: 
  - name: "comics"
    label: "Comics"
    folder: "_comics"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['date', 'title', 'author', 'commit_date']
    editor:
      preview: false
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Gumroad Slug"
        name: "gumroad"
        widget: "string"
        required: true        
      - label: "Artist Name"
        name: "artist"
        widget: "relation"
        collection: "artists"
        search_fields: ["artist"]
        value_field: "artist"
        display_fields: ["artist"]  
        required: true
      - label: "Preview Image (square)"
        name: "preview_image"
        widget: "file"
        required: true
      - label: "Cover Art"
        name: "cover_art"
        widget: "file"
        required: false
      - label: "layout"
        name: "layout"
        widget: "hidden"
        default: "product"
      - label: "Price"
        name: "price"
        default: 15
        widget: "number"
        value_type: "float"
        required: true
      - label: "Length"
        name: "length"
        widget: "number"
        default: 8
        required: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        required: true
        date_format: "YYYY-MM-DD" 
        time_format: false
      - label: "Visible"
        name: "visible"
        widget: "boolean"
        default: false
      - label: "Show in Google"
        name: "sitemap"
        widget: "boolean"
        default: false
      - label: "Preview Text"
        name: "preview"
        required: false
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
      - { label: "Teaser Video", name: "preview_video", widget: "file", required: false }
      - { label: "Teaser Video Thumbnail", name: "preview_video_thumb", widget: "file", required: false }
      - { label: "Release Video", name: "live_video", widget: "file", required: false }
      - { label: "Release Video Thumbnail", name: "live_video_thumb", widget: "file", required: false }
      - { label: "Runtime", name: "runtime", widget: "string", required: false }
      - { label: "Show Teaser on site", name: "avc", widget: "boolean", default: false, required: false }

**Comment by erezrokah** [comment] 2022-01-25 10:19
Hi @alexknowshtml, thanks for the issue. Going to close it as a duplicate of https://github.com/netlify/netlify-cms/issues/4538.

I'll post a comment on that issue

**Closed by erezrokah** 2022-01-25 10:19 UTC
Labels: type: bug
