### ISSUE TITLE
Indication on what changed in the editorial workflow

### ISSUE THREAD

**Issue by lsolesen** [netlify/netlify-cms#4362] opened 2020-09-24 21:24 UTC
**Is your feature request related to a problem? Please describe.**

It would be great if there were some sort of indication on what changed, when reviewing a file in the editorial workflow. You can right now just see a file has changed.

**Describe the solution you'd like**

It would be great if there was some sort of colors like when reviewing a pull request, so it is possible to see what changed in the text.

**Describe alternatives you've considered**

**Additional context**

**Comment by erezrokah** [comment] 2020-09-28 06:57
Closing as duplicate of https://github.com/netlify/netlify-cms/issues/2735

**Closed by erezrokah** 2020-09-28 06:57 UTC
Labels: type: feature
