### ISSUE TITLE
Cloudinary stuck at Log in

### ISSUE THREAD

**Issue by casperleerink** [netlify/netlify-cms#3387] opened 2020-03-08 17:15 UTC
Bug described in the latest comments of issue #1999 

**Describe the bug**
Using cloudinary as the media_library in netlify CMS. Everything works in local environment, I can upload images and select them from within the /admin/ section of my local site. However when I publish my site on netlify and go to the /admin/ panel, I get stuck at this the following text: Please click here to log in using your username & password. where click here lead to: https://cloudinary.com/console/media_library/cms_login?cms=true
which opens and closes shortly after, nothing happens after that.

**Applicable Versions:**
 - Netlify CMS version: 2.11.20
 - Git provider: Github
 - OS: MacOS Catalina
 - Browser version: tested on both firefox 73 and safari.

**CMS configuration**
`backend:
  name: git-gateway
  repo: casperleerink/breathingbass
public_folder: /assets
media_library:
  name: cloudinary
  config:
    cloud_name: "casperleerink"
    api_key: "173738255589443"
    folder:
      path: "breathingbass"`

**Comment by casperleerink** [comment] 2020-03-09 20:01
It might be important to state that my cloudinary account is used on two other websites running on servers as well.

**Comment by erezrokah** [comment] 2020-05-07 08:04
Closing as duplicate of https://github.com/netlify/netlify-cms/issues/1999.
See my comment https://github.com/netlify/netlify-cms/issues/1999#issuecomment-602527178

**Closed by erezrokah** 2020-05-07 08:04 UTC
