### ISSUE TITLE
Invariant Violation: Minified React error

### ISSUE THREAD

**Issue by Samamoah** [netlify/netlify-cms#2442] opened 2019-07-13 17:44 UTC
**Error**
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=t%3A%20invalid_grant%3A%20Invalid%20Password&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by talves** [comment] 2019-07-13 19:11
@Samamoah I changed the title and brought the error into the body. 

Please fill out the rest of the form as best as possible, so we know how to recreate or figure out what is causing this error. Thanks

**Comment by molove-gyq** [comment] 2019-07-19 07:17
@Samamoah Did you resolve this problem? I have the same problem, How to resolve?

**Comment by talves** [comment] 2019-07-19 13:15
@molove-gyq can you open a new issue with details and an example repo that produced the error. Thanks

I am closing this issue due to non-response.

**Closed by talves** 2019-07-19 13:15 UTC

**Comment by molove-gyq** [comment] 2019-07-23 02:07
> @molove-gyq can you open a new issue with details and an example repo that produced the error. Thanks
> 
> I am closing this issue due to non-response.

@Samamoah Thanks for your reply. Through to find these days , I found the solution. this 
 is a link for the issure (facebook/react#8379). Thank again for your reply.

**Comment by Samamoah** [comment] 2019-07-29 13:01
@molove-gyq What was the solution. My issue was when i tried opening my netlify cms admin panel

**Comment by thelovesmith** [comment] 2020-02-07 19:45
Hello I am also looking for a solution, the link @molove-gyq shared doesn't work for me.

**Comment by erezrokah** [comment] 2020-02-09 06:35
@thelovesmith can you open a new issue with a reproduction scenario? This issue is a bit stale and lacking in details.
