### ISSUE TITLE
With gitlab if I go to direct editor it will load all pages. (Lightsail with 4GB ram very very slow)

### ISSUE THREAD

**Issue by stevemarksd** [netlify/netlify-cms#4913] opened 2021-02-02 10:59 UTC
**Describe the bug**

When I got to .../admin/#/collections/default/entries/test

It loads all articles as well and it takes very very long to load. (same as you would arrive on /admin page)

**To Reproduce**

just go to an entry: .../admin/#/collections/default/entries/test

**Expected behavior**

Should not load all articles as in the /admin view. SHould only load the article im opening.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: `"netlify-cms-app": "2.13.1",`
 - Git provider: gitlab (AWS lightsail bitnami)

**CMS configuration**

    # https://www.netlifycms.org/docs/gitlab-backend/
    backend:
      name: gitlab
      repo: root/site.com
      branch: master
      api_root: https://mygitlab.com/api/v4
      base_url: https://mygitlab.com/
      auth_type: implicit
      app_id: 222
      auth_endpoint: oauth/authorize
    # Where to save image
    media_folder: src/content/images/cms
    # Prefix image url (gatsby-remark-relative-images staticFolderName + media_folder = image)
    public_folder: /images/cms
    publish_mode: editorial_workflow
    collections:
      - name: default
        label: Default
        folder: src/content/pages
        create: true
        media_folder: ''
        public_folder: ''
        path: '{{path}}/{{path}}'
        preview_path: '{{path}}'
        fields:
          - { name: path, label: Path, widget: 'string' }
          - { name: createdAt, label: Created Date, widget: 'datetime' }
          - { name: updatedAt, label: Last Updated Date, widget: 'datetime' }
          - { name: title, label: Title, widget: 'string' }
          - { name: description, label: Description, widget: 'string' }
          - { name: keywords, label: Keywords, widget: 'string' }
          - { name: tags, label: Tags, widget: 'list' }
          - { name: featuredImage, label: Featured Image, widget: 'image' }
          - { name: content, label: Show on home page, widget: 'boolean', default: true }
          - { name: body, label: Body, widget: 'markdown' }

**Additional context**

**Comment by erezrokah** [comment] 2021-02-02 11:35
Hi @stevemarksd, doest this happen with entries that have a draft? 
If so this is probably related to https://github.com/netlify/netlify-cms/issues/3468

**Comment by stevemarksd** [comment] 2021-02-02 12:51
Correct.. seems to load those ones.. I only have 20 and my editors need to wait ages for every change :/ I think we can close as duplicate

**Comment by erezrokah** [comment] 2021-02-02 12:56
Thank you for following up. Closing as duplicate of https://github.com/netlify/netlify-cms/issues/3468

**Closed by erezrokah** 2021-02-02 12:56 UTC
Labels: type: bug
