### ISSUE TITLE
TypeError on Admin interface, when clicking on Pages > Homepage

### ISSUE THREAD

**Issue by wohfab** [netlify/netlify-cms#4966] opened 2021-02-17 20:48 UTC
Hi there, I have a weird error, when trying to edit a collection item through the Admin interface. Clicking on `Pages > Homepage`, I do get the following error:

`TypeError: n.split("\n\n")[0].trimEnd is not a function. [...] is undefined.`

Repo: https://github.com/wohfab/fwdc-ald

The error does occur on one single user. Things I tried already:

- using different browsers
- resetting the password
- resetting the Git Token

**Expected behavior**

Click on the collection item `Pages > Homepage` to edit.

**Screenshots**

![image](https://user-images.githubusercontent.com/4539234/108265449-12738f00-7169-11eb-87d4-3d35667c6193.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.93
 - Using `git-gateway` netlify identity
 - OS: macOS
 - Browser: Safari (tested Chrome and Firefox, too)

**CMS configuration**

https://github.com/wohfab/fwdc-ald/blob/master/src/admin/config.yml

**Comment by erezrokah** [comment] 2021-02-18 12:47
Hi @wohfab is this still an issue? I couldn't reproduce using your repo (also tried reverting https://github.com/wohfab/fwdc-ald/commit/39b657f8832becae0ec6f163deeffd5c53aefbb5 and c8e56667f2d7e81c389b9444a2ba1969eff271f2)

**Comment by wohfab** [comment] 2021-02-18 13:14
Hey @erezrokah, thanks for trying and the quick reply. 

Unfortunately, it is still an issue. I couldn't reproduce it with my account either, but with my friend's account, it does not work. I don't know if you have the possibility to "imitate" an existing user account to see, what's happening there. If not, I will ask her to reset the password, so I can share the login info.

**Comment by erezrokah** [comment] 2021-02-18 13:23
Hi @wohfab we can't really imitate another user account.
I recommend sharing a step by step reproduction we can both follow.

**Comment by erezrokah** [comment] 2021-03-02 14:25
Closing - please comment with a reproduction if still relevant

**Closed by erezrokah** 2021-03-02 14:25 UTC
Labels: status: more info needed, type: bug
