### ISSUE TITLE
UI bugs in Firefox (Quantum)

### ISSUE THREAD

**Issue by DirtyF** [netlify/netlify-cms#907] opened 2017-12-09 10:00 UTC
Congrats for shipping 1.0, here are some first sight issues that jump to my eyes in Firefox Quantum:

- [ ] search icon position on inputs (collections, medias) 🦊 🍏 

![medias-search](https://user-images.githubusercontent.com/103008/33794615-5f978926-dccf-11e7-9a58-f711a2610198.png)
![collections-search](https://user-images.githubusercontent.com/103008/33794616-5fc5e6d6-dccf-11e7-8382-05ca9db5b7b0.png)

- [ ] Editor toolbar switch button

![editor-switch](https://user-images.githubusercontent.com/103008/33794632-cc9d0956-dccf-11e7-823d-0c1971e3bae2.png)

**Comment by tech4him1** [comment] 2017-12-09 14:42
@DirtyF What browser are you using, the first two show up fine for me?

**Comment by DirtyF** [comment] 2017-12-09 15:08
✅ Google Chrome, Safari
🐛 in Firefox 🦊 (MacOS High Sierra)

**Comment by tech4him1** [comment] 2017-12-09 16:14
Weird, I can reproduce that bug, but it almost seems like a Firefox bug -- if I try to change the positioning at all in the dev tools it starts showing up correctly with the setting the same.

**Comment by erquhart** [comment] 2017-12-09 18:00
It's due to changes in the way Quantum handles certain styling defaults.

**Comment by tech4him1** [comment] 2017-12-09 18:08
The third bug in your list is a duplicate of https://github.com/netlify/netlify-cms/issues/684, right?

**Comment by tech4him1** [comment] 2017-12-09 18:39
And I think the fourth issue could be split off since it isn't really 1.0 specific.

**Comment by DirtyF** [comment] 2017-12-10 02:13
@tech4him1 splitted ✂️

**Comment by erquhart** [comment] 2017-12-19 22:45
Note: these are all issues where Firefox is not applying default top/left for absolute positioned items appropriately. If you toggle absolute positioning off and on for these items, they correctly apply default positioning. A quick scan of recent entries in bugzilla shows a few issues that could match, so we should determine which is the cause, or open one.

For our immediate purposes, I'm okay with accepting a workaround PR.

**Comment by tech4him1** [comment] 2017-12-19 22:49
Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1386654 or https://bugzilla.mozilla.org/show_bug.cgi?id=1417025?

**Comment by erquhart** [comment] 2017-12-24 16:07
Yeah those were the two I saw, and they're both so closely related, I'm betting it's all the same underlying issue.

**Closed** 2018-01-03 21:08 UTC
Labels: area: browser-compatibility, exp: beginner, good first issue, kind: bug, status: accepted
