### ISSUE TITLE
Disable Editorial Workflow for Specific Collections

### ISSUE THREAD

**Issue by kwyoung11** [netlify/netlify-cms#3656] opened 2020-04-24 23:22 UTC
**Is your feature request related to a problem? Please describe.**

For simple collections like Tags that usually contain just a single string field, it can be cumbersome and time-consuming to have go through the editorial workflow to publish a single tag. 

**Describe the solution you'd like**

Allow the user to switch off the editorial workflow for specific collections. For e.g. the collection-level field could be called `use_editorial_workflow`. If `publish_mode: editorial_workflow` is set, then it would default to true. if `use_editorial_workflow: false` is set, then it would be disabled just for that collection.

**Describe alternatives you've considered**

An alternative is manually creating the markdown files, but it's also cumbersome.

**Additional context**

**Comment by erezrokah** [comment] 2020-04-26 08:54
Thanks @kwyoung11, closing as a duplicate of https://github.com/netlify/netlify-cms/issues/1571. You can up vote that feature request.

**Closed by erezrokah** 2020-04-26 08:54 UTC
