### ISSUE TITLE
Are we able to customize the dashboard UI? 

### ISSUE THREAD

**Issue by pfftdammitchris** [netlify/netlify-cms#1498] opened 2018-07-13 19:43 UTC
Are we able to customize the dashboard UI to add some chart SVG's, controls, etc? 
(Searched everywhere for this simple question although I can't find an answer to such a simple question. Forgive me for my ignorance)

**Comment by tech4him1** [comment] 2018-07-13 22:16
@pfftdammitchris Can you give an example (screenshot, link, etc.)? What do you actually want the charts and controls to show or do?

**Comment by pfftdammitchris** [comment] 2018-07-14 00:35
@tech4him1 for example if we are able to customize the dashboard to have widgets like everything on this page:
http://wrapbootstrap.com/preview/WB0573SK0

Are we only limited to working with the default dashboard, or the default UI?

How would we change the sorting of items in each collection by date, and also list the date on each item? Currently only the title is shown on each item. In the screenshot below the blue dates would be an example of customizing the UI:

![image](https://user-images.githubusercontent.com/20717348/42718923-2783d618-86c3-11e8-89df-0e9a142308d2.png)

**Comment by erquhart** [comment] 2018-08-22 19:35
Yeah it's not that kind of admin interface, it's purpose built for Netlify CMS collection display.

That said, you _should_ be able to swap in your own components to replace interfaces like this one, we're just [not there yet](https://github.com/netlify/netlify-cms/issues/1193#issuecomment-376692788).

**Comment by calpa** [comment] 2019-01-27 13:12
Will this feature be included in the schedule?

**Comment by tech4him1** [comment] 2019-01-29 18:32
@calpa I don't think this issue is really well-defined enough to start working on or add to a schedule. If you could specify your use case and some details of how you think it should work and look, that might help us move forward.

**Comment by kre1z0** [comment] 2019-02-18 18:32
It would be nice to add the ability to output any field from the collection. I have a list of news and I would like to see which of them are displayed on the main.

**Comment by leonardodino** [comment] 2019-02-18 23:24
I think this turned out to be a duplicate of #2019.

I get that there are many customizations besides the `EntryCard`, but it's by far the most requested one. (besides some filtering and ordering of the list).

I do have some code done, with examples below, but I'm too short on time right now to contribute it back. If anyone is interested, please don't hesitate to copy (: and contribute it upstream here.


> the language is pt-BR, but I guess you can figure it out.the article can link to a editorial (the colored tag on top) and many 

|<img width="945" src="https://user-images.githubusercontent.com/8649362/52980790-a9f74900-33ba-11e9-84f4-6daa71d2636f.png">|
<img width="945" src="https://user-images.githubusercontent.com/8649362/52980799-b24f8400-33ba-11e9-82fc-96876b6cdfc5.png">|
<img width="945" src="https://user-images.githubusercontent.com/8649362/52980801-b5e30b00-33ba-11e9-8877-29dc2fe04daf.png">|
|:--:|:--:|:--:|
|`articles`|`editorials`|`authors`|

**Comment by Arenal94** [comment] 2019-02-19 12:00
@leonardodino Amazing stuff ! Just what I was looking for ! I can't wait to see it on live 💃

**Comment by erquhart** [comment] 2019-02-19 20:44
@leonardodino agreed, this became about entry card customization. The original issue is about dashboard customization, eg. creating an actual data driven dashboard, but Netlify CMS doesn't have a dashboard at all, so I'm thinking this should be closed. Would you mind porting your last comment to #2019 so we can close this?

**Comment by leonardodino** [comment] 2019-02-19 21:16
done! @erquhart

**Comment by calpa** [comment] 2019-02-20 01:30
Can we have a pull request on this? I think this update helps a lot...

**Comment by tech4him1** [comment] 2019-02-20 18:27
@calpa See https://github.com/netlify/netlify-cms/issues/1498#issuecomment-465302384.

**Closed** 2019-02-25 16:14 UTC
Labels: kind: discussion, kind: feature, status: more info needed

**Comment by adamtaylor13** [comment] 2019-04-23 02:23
@leonardodino Where is this registerEntryCard method registered? I tried using it, but I'm getting a WEBPACK_IMPORTED_MODULE error that it's not a function. I then thought you had added it custom to the campus-online codebase, but I can't find it anywhere there either. What am I missing? :(

**Comment by leonardodino** [comment] 2019-04-23 03:02
@adamtaylor13, `registerEntryCard` only exists in my fork.
Unfortunately I haven't had the time to make a PR upstream. 😕

You probably didn't find it because [`github` search doesn't work on forks](https://github.com/isaacs/github/issues/498).
<sup>(unless they have more stars than the upstream repo)</sup>

you can find it on the master branch in the following files:
- [`netlify-cms-core/src/components/Collection/Entries/EntryListing.js`](https://github.com/campus-online/cms/blob/master/packages/netlify-cms-core/src/lib/registry.js)
- [`netlify-cms-core/src/components/Collection/Entries/EntryListing.js`](https://github.com/campus-online/cms/blob/master/packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js)

**or**: just follow the [`diff`](https://patch-diff.githubusercontent.com/raw/campus-online/cms/pull/9.diff)/[`patch`](https://patch-diff.githubusercontent.com/raw/campus-online/cms/pull/9.patch) in the [**PR**](https://github.com/campus-online/cms/pull/9/files).
It also includes some basic docs that will help on getting your PR merged.

---

You, and anyone interested in contributing this code to the upstream `netlify-cms` have my permission and rights to use the code, no attribution needed (:

**Comment by numoonchld** [comment] 2019-09-16 09:29
I'd also like to request ability for a solarized mode of the CMS UI. 

UseCase: The stark white computer screen hurts my eyes while composing blogs. It'd be great to have solarized light and solarized dark theme.

**Comment by erquhart** [comment] 2019-09-25 21:24
@numoonchld https://github.com/netlify/netlify-cms/issues/1727

**Comment by oskery** [comment] 2020-01-20 17:12
I'm sorry to disturb this resolved matter but I am new here and don't understand. Is the possibility of adding an additional field to each entry (e.g. a date) in the admin dashboard something that is coming or something that we can implement ourselves? I looked at the EntryCard implementation but I am not experienced enough to understand the code. To me it seems like such a trivial thing from a usability standpoint and maybe it is possible but not talked about that much, I just haven't found a simple enough solution for it. OR is this never to be implemented as "Netlify CMS doesn't have a dashboard", I didn't really get that part? @erquhart

**Comment by erezrokah** [comment] 2020-01-21 07:58
@oskery We've started a new effort under https://github.com/netlify/netlify-cms/issues/2557. Feel free to comment on that issue.
