### ISSUE TITLE
gatsby-plugin-netlify-cms - registerPreviewStyle

### ISSUE THREAD

**Issue by pungggi** [netlify/netlify-cms#1408] opened 2018-06-05 16:03 UTC
Is there any possibility to use a css in js solution like styled components with the preview?

At the moment there is no style applied and registerPreviewStyle does just link to a css file..

**Comment by robertkarlsson** [comment] 2018-06-05 20:03
See this issue: 

https://github.com/netlify/netlify-cms/issues/793

I made a solution for styled components based on the answer in there (not the prettiest), see below.

This is in my cms.js where i register the previews:

```javascript
//Components used to Enable netlify CMS to apply the styles added through styled-components
class CSSInjector extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      iframeRef: ''
    }
  }

  componentDidMount() {
    const iframe = document.querySelector(".nc-previewPane-frame")
    const iframeHeadElem = iframe.contentDocument.head;
    this.setState({ iframeRef: iframeHeadElem })
  }

  render() {
    return (
      <div>
        { this.state.iframeRef && (
          <StyleSheetManager target={this.state.iframeRef}>
            { this.props.children }
          </StyleSheetManager>
        )}
      </div>
    )
  }
}

CMS.registerPreviewTemplate('index', props => (
  <CSSInjector>
    <IndexPagePreview {...props} />
  </CSSInjector>
))
```

**Comment by tech4him1** [comment] 2018-06-05 20:19
Duplicate of #793.

**Comment by tech4him1** [comment] 2018-06-05 20:20
Also note you can now pass strings into `registerPreviewStyle`: https://www.netlifycms.org/docs/beta-features/#raw-css-in-registerpreviewstyle.

**Closed** 2018-06-05 20:19 UTC
Labels: duplicate

**Comment by pungggi** [comment] 2018-09-27 05:39
this solution does not work with v2: 
![grafik](https://user-images.githubusercontent.com/5635709/46125190-511aee80-c228-11e8-8046-6513f2ef6ce0.png)


this might be the problem: ` const iframe = document.querySelector(".nc-previewPane-frame");`

**Comment by joserocha3** [comment] 2018-09-27 11:27
Replace the first line with
```javaacript
const iframe = document.getElementsByTagName('iframe')[0]
```

**Comment by a8t** [comment] 2019-08-31 17:36
Here, implemented as hooks!

`import React from 'react';
import { StyleSheetManager } from 'styled-components';

export default function({ children }) {
  const [iframeRef, setIframeRef] = useState(null);

  useEffect(() => {
    const iframe = document.getElementsByTagName('iframe')[0];
    const iframeHeadElem = iframe.contentDocument.head;
    setIframeRef(iframeHeadElem);
  }, []);

  return (
    <div>
      {iframeRef && (
        <StyleSheetManager target={iframeRef}>{children}</StyleSheetManager>
      )}
    </div>
  );
}
`

**Comment by dmitriyaa** [comment] 2020-03-03 18:12
@a8t, have you thought of putting this in a separate package, would be pretty nice? 🙂
