### ISSUE TITLE
pasting a large formatted document can break prosemirror, silently preventing further CMS functionality completely

### ISSUE THREAD

**Issue by fool** [netlify/netlify-cms#225] opened 2017-01-26 21:51 UTC
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

When pasting a large, formatted document in richtext mode, article may become un-saveable due to prosemirror breakage.  Document is markdown-created, but wysiwig view when cutting/pasting.  It arrived formatted in the CMS but apparently also broke the CMS silently

There are some errors in the dev console, but nothing user-visible, and the CMS then stops working in terms of being able to save that article.

**- If the current behavior is a bug, please provide the steps to reproduce.**

paste the entire text from this document: https://paper.dropbox.com/doc/Best-Practices-Getting-started-with-Netlify-7bbR2obbMG6ee0nEOZndF into a fresh blog after filling in the title/author/other frontmatter correctly.  Observe nonfunctionality of save button and errors in dev console from prosemirror.

**- What is the expected behavior?**

I could paste and save the article

**- Please mention your node.js, and operating system version.**

this is on the netlify-installed CMS @ app.netlify.com/admin, trying to post a blog post

**Comment by cassiozen** [comment] 2017-01-27 05:26
After further investigation, the CMS functionality bug was not caused by or related to the prosemirror bug. 

I will close this for now, please feel free to reopen if you have more information.

**Closed by cassiozen** 2017-01-27 05:26 UTC
Labels: bug
