### ISSUE TITLE
Problem with entering the admin panel

### ISSUE THREAD

**Issue by SegunWeb** [netlify/netlify-cms#4875] opened 2021-01-25 09:28 UTC
Hey.

Faced the problem of entering the admin panel. Upon authorization, I receive a message about a successful login, but it does not take me to the editor page and gives an error:

Failed to execute json in response: main stream has already been read

https://kingspan-dev.netlify.app/   -- project 

I contacted the netlify community support, but they could not help me.

**Comment by erezrokah** [comment] 2021-01-25 11:50
Hi @SegunWeb I'm closing this issue a duplicate of https://github.com/netlify/netlify-cms/issues/4521.
Can you share the browser traffic as I requested in https://github.com/netlify/netlify-cms/issues/4521#issuecomment-766755536?

**Closed by erezrokah** 2021-01-25 11:50 UTC
Labels: duplicate, type: bug
