### ISSUE TITLE
Netlify CMS Dashboard sluggish when there are many objects in a list

### ISSUE THREAD

**Issue by vai0** [netlify/netlify-cms#2293] opened 2019-04-16 18:59 UTC
**Describe the bug**
Not really a bug per say - but my current implementation has a list field that contains 25 objects. When typing in any of the other fields on the page, or adding a new object to the list, there's a noticeable delay.

**To Reproduce**
This can be reproduced in the [kitchen sink demo](https://cms-demo.netlify.com/#/collections/kitchenSink/new). Add up to around 20'ish objects into the List field. Try filling in one of those objects, or typing in another field on the page. There's a half a second delay for every character typed or dropdown opened, toggle switched, etc....

**Expected behavior**
Expect there to be a much more minimal delay.

**Comment by stevenpeniche** [comment] 2020-07-30 19:00
Hey team! Has there been any progress on a resolution to this issue?

**Comment by erezrokah** [comment] 2020-08-02 10:29
This is actually a duplicate of https://github.com/netlify/netlify-cms/issues/3415.
Closing in favour of that one

**Closed by erezrokah** 2020-08-02 10:29 UTC
Labels: duplicate, kind: performance, pinned, type: bug
