### ISSUE TITLE
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&a...

### ISSUE THREAD

**Issue by lewnelson** [netlify/netlify-cms#3651] opened 2020-04-24 09:43 UTC
**Describe the bug**

Error on Netlify CMS when scrolling through large collection. Page completely breaks.

In our case 144 articles, each article with around 200 - 300 lines of content.

**To Reproduce**

Load Netlify CMS collection of articles with more than ~144 articles, with each article containing >200 lines of content.

**Expected behavior**

* To load the CMS articles correctly

**Screenshots**

<img width="1680" alt="Screenshot 2020-04-24 at 10 35 28" src="https://user-images.githubusercontent.com/11139198/80198593-308b6400-8618-11ea-8d52-b3cb5cae2eb5.png">

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.47`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36`

**CMS configuration**
```
load_config_file: false
show_preview_links: true
public_folder: /images/uploads
media_folder: static/images/uploads
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: staging
  accept_roles:
    - admin
    - editor
collections:
  - identifier_field: date
    delete: true
    name: status_updates
    folder: resources/content/status-updates
    publish: true
    sortableFields:
      - commit_date
      - date
      - date
      - commit_author
    label: Status updates
    fields:
      - name: date
        label: Date
        widget: datetime
        format: YYYY-MM-DD
      - name: localized_content
        label: Localised content
        widget: list
        fields:
          - label: Language
            name: lang
            required: null
            widget: select
            options:
              - label: English 🇺🇸
                value: en
              - label: 日本語 🇯🇵
                value: ja
              - label: 한국어 🇰🇷
                value: ko
              - label: 中文 🇨🇳
                value: zh-cn
            default: en
          - name: body_text
            label: Body
            widget: markdown
            required: false
          - name: video_id
            label: YouTube video id
            widget: string
            required: false
    create: true
  - name: footer
    label: Footer
    folder: resources/content/footer
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - name: product_info
        label: Product info heading
        widget: string
      - name: community_info
        label: Community info heading
        widget: string
      - label: Cardano informational links
        label_singular: Cardano informational link
        name: product_links
        widget: list
        fields:
          - label: URL
            name: href
            widget: string
          - label: Label
            name: label
            widget: string
      - label: Cardano community links
        label_singular: Cardano community link
        name: community_links
        widget: list
        fields:
          - label: URL
            name: href
            widget: string
          - label: Label
            name: label
            widget: string
      - label: Footer text
        name: content_body
        description: Text blob in footer, parsed as markdown
        widget: markdown
    publish: true
    sortableFields:
      - commit_date
      - title
      - commit_author
  - name: header
    label: Header
    folder: resources/content/header
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Select language
        name: select_language
        widget: string
      - name: content
        label: Content
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: navigation
            label: Navigation
            widget: object
            fields:
              - name: home
                label: Home
                widget: string
              - name: status_updates
                label: Status
                widget: string
              - name: phases
                label: Phases
                widget: string
          - name: phase_navigation
            label: Phase navigation
            widget: object
            fields:
              - name: byron
                label: Byron
                widget: object
                fields:
  
...

**Comment by erezrokah** [comment] 2020-04-24 16:48
Hi @lewnelson do you mind copy pasting the full link to the error? following usually provides helpful information on the cause of the error.

**Comment by teamcrisis** [comment] 2020-04-27 23:34
For me, I'm able to easily reproduce this issue using one of the example Gatsby themes listed in the docs.

```Objects are not valid as a React child (found: Mon Apr 27 2020 19:21:45 GMT-0400 (Eastern Daylight Time)).```

**Comment by erezrokah** [comment] 2020-04-28 07:34
Hi @teamcrisis can you share which example is that? This is usually an issue with the preview template passing a date object as a react child without converting it to a string first.

**Comment by teamcrisis** [comment] 2020-04-28 09:17
@erezrokah I'm testing with https://github.com/thriveweb/yellowcake/

**Comment by erezrokah** [comment] 2020-04-28 10:18
Hi @teamcrisis closing this as the issue is with that project - I opened a PR for them to fix it https://github.com/thriveweb/yellowcake/pull/46

**Closed by erezrokah** 2020-04-28 10:18 UTC

**Comment by lewnelson** [comment] 2020-04-28 15:46
For anyone else picking up similar issues in our case we had to change the config for the date field from:
```
      - name: date
        label: Date
        widget: datetime
        format: YYYY-MM-DD
```
to:
```
      - name: date
        label: Date
        widget: date
        format: YYYY-MM-DD
```

This is something that was working and only recently broke - within the last week. Presumably it's meant to work as we had it before?

**Comment by erezrokah** [comment] 2020-04-28 16:00
I think the main thing is to keep the format of the date consistent between entries - using a format would serialise the date as a string and read it as a string, thus safe to use as a react node.
If you don't have a format it is serialized to an object and read as an object thus requiring a conversion.
