### ISSUE TITLE
Admin Login Screen Errors

### ISSUE THREAD

**Issue by nebrelbug** [netlify/netlify-cms#3658] opened 2020-04-25 23:16 UTC
**Describe the bug**
I created a new Hugo repository with [Academic's one-click install](https://sourcethemes.com/academic/docs/install). I followed the instructions on the page to set up Netlify CMS, enabled Git Gateway, invited myself as a user, etc.

When I clicked on the invitation email, it correctly brought me to the site and prompted me for a password. I entered it, it said I was logged in, and all was good. Then I tried to go to `/admin`. No matter what I did, when I clicked on the "Login with Netlify Identity" button, nothing at all happened -- no console errors, no error pop-ups, no anything.

Eventually, at least 5 minutes later, I saw this error:
![Screenshot from 2020-04-25 17-05-17](https://user-images.githubusercontent.com/25597854/80292852-1edcb600-8717-11ea-94cf-1b9e04394495.png)

```
TypeError: Failed to fetch
...
net::ERR_HTTP2_PROTOCOL_ERROR
```

After (as recommended in a previous issue) I **pushed an inconsequential update to GitHub**, the page began throwing ""Git Gateway Error [object Object]" yellow pop-up notifications.

Finally, I was able to get the page to work by **sending a password reset email**.

**To Reproduce**
Follow instructions at https://sourcethemes.com/academic/docs/install/#install-with-web-browser without locally cloning the site and editing it first.

**Expected behavior**

Login would work nicely and without having to first make an inconsequential edit, then send a password reset email.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: *netlify-cms-app*: 2.12.11, *netlify-cms-core*: 2.25.0, *netlify-cms* 2.10.47
 - Git provider: [e.g. GitHub, BitBucket]
 - Ubuntu (Pop!_OS)
 - Chrome 81, Firefox

**CMS configuration**

https://github.com/sourcethemes/academic-kickstart/blob/master/static/admin/config.yml

**Additional context**

See #3408, #3621 for relevant issues that eventually helped me find a workaround

**Comment by erezrokah** [comment] 2020-04-28 09:28
Hi @nebrelbug is this still an issue? I've seen other cases recently where it takes some time for `git-gateway` to start working after initial deploy

**Comment by samtalki** [comment] 2020-05-04 06:26
Same exact issues here. Haven't been able to solve it.

**Comment by greenlightjohnny** [comment] 2020-07-24 00:09
I'm having this issue currently with a Gatsby site using GitHub as the identity provider. It was working great and I had made several blog posts over two weeks through the admin panel. Just went to log on and am getting the `API_ERROR: Git Gateway Error: [object Object]` message. 
I tried enabling and re-enabling identity external providers, and  re-generating the GitHub API access token under services Git Gateway. Tried a fresh deploy and am still getting nothing. Hopefully resolves soon, would really like to know the cause of it.

**Comment by erezrokah** [comment] 2020-07-26 08:36
I'm closing this issue, as we don't seem to have a reproducible workaround.
If someone encounters this issue, please open a new issue and please provide the browser network traffic (requests and responses) for the `settings` requests, especially the one that errors out.

**Closed by erezrokah** 2020-07-26 08:36 UTC
Labels: status: unconfirmed, type: bug

**Comment by martinkean** [comment] 2022-04-04 02:29
Note: also commented in #3408
Git Gateway Error: [object Object]
Also experiencing this issue - and I am connecting using Github authentication.
Was working fine yesterday, but today -bluh-. Hopefully someone is keeping their eyes on this : )
