### ISSUE TITLE
Relation widget should produce a slug in the output

### ISSUE THREAD

**Issue by tankadesign** [netlify/netlify-cms#3067] opened 2020-01-10 23:07 UTC
The relation widget requires that you define the valueField, but you can't access the slug of a collection. For instance I have a collection of Pages. I created a Relation widget in a list that lets me create a menu of pages, but I would need the slug of the page collection item to be outputted so I can create a properly linked list of pages. Currently I can only get the title, which I need to slugify manually after consuming the JSON data. Ideally the slug would come along for the ride automatically.

Requested solutions:
- automatically output `slug` value alongside the valueField
- allow the user to output the valueField as an object that contains {value, slug}

**Comment by jeremyfrank** [comment] 2020-04-21 13:22
Including an `excerpt` would be great too! The use case would be selecting a "featured" post from a relation field, and just needing to display a few pieces of data. The output could be:

```
{
  title: "The Post Title",
  slug: "the-post-slug",
  excerpt: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit molestias amet eligendi ullam voluptatem in veniam doloremque impedit. Odio…"
}
```

**Comment by erezrokah** [comment] 2020-04-23 08:14
Closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/1063.
As for the `excerpt` and storing multiple fields - the approach with the relation widget is just to store the link between entries. That link could be used later during the build process to fetch any additional information.

**Closed by erezrokah** 2020-04-23 08:14 UTC
