### ISSUE TITLE
Editing a page in Netlify CMS delete or mess up with the content of the page

### ISSUE THREAD

**Issue by andreamussap** [netlify/netlify-cms#3332] opened 2020-02-27 14:56 UTC
**Describe the bug**
Editing a page in Netlify CMS delete or mess up with the content of the page.  cc @erquhart 

> Please prioritize this as it prevent us from making edits using the CMS

**To Reproduce**
1. Go to https://axway-open-docs.netlify.com/docs/contribution_guidelines/
2. Click on Edit on Netlify CMS
3. Log in with your GitHub account
4. Make some change using the WYSIWYG editor
5. Click Save
6. Wait for entry to be saved

**Error**
- in my case it replaced all content with **@import "main2;**

![CMS_error2_2020-02-27](https://user-images.githubusercontent.com/10401080/75454285-1a8d5a00-596d-11ea-9cb2-e7a63414d9e4.png)

- With another user, it completely messed up the content:

![CMS_error3_2020-02-27](https://user-images.githubusercontent.com/10401080/75454317-2711b280-596d-11ea-99ee-dc31ed10b162.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: GitHub
 - OS: Windows 10 Enterprise
 - Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**CMS configuration**

My project doesn't have a config.yml file anymore. It was deleted by https://github.com/Axway/axway-open-docs/pull/203 

See https://github.com/Axway/axway-open-docs/tree/master/static/admin

cc @erquhart

**Comment by alexearnshaw** [comment] 2020-03-02 12:54
@erezrokah @erquhart Here's a little more context on this one...

I suspect the `@import "main";` line that is appearing in the CMS editor/preview after saving is perhaps coming from the change made to `assets/scss/cms.scss` in @erquhart's PR to improve our Netlify CMS integration https://github.com/Axway/axway-open-docs/pull/203/files:

![image](https://user-images.githubusercontent.com/29064556/75677812-32722000-5c84-11ea-945f-8971552d7c6f.png)

So perhaps this is not an issue with CMS itself but an incompatibility with the latest CMS version and the changes in that PR? Is there something we can change on our project to make this work again? We'd really appreciate any help to fix the issue as quickly as possible, as our users can't use Netlify CMS at all to edit while this issue exists.

**Comment by erezrokah** [comment] 2020-03-02 13:08
Thanks @alexearnshaw, looking into it and will update on my progrees

**Comment by erezrokah** [comment] 2020-03-02 14:43
Can't seem to reproduce this with the open authoring flow:
![image](https://user-images.githubusercontent.com/26760571/75686385-7a9d3c80-5c9c-11ea-85ea-44eb464a56a9.png)

See the commit on my test account repo https://github.com/erezrokah-test/axway-open-docs/commit/b8b8c203eccb85c3360495cd0818a2f5693ece94

**Comment by erezrokah** [comment] 2020-03-02 14:48
Non open authoring flow:
https://github.com/erezrokah/axway-open-docs/pull/4/files

![axway](https://user-images.githubusercontent.com/26760571/75686852-30688b00-5c9d-11ea-941d-c65c192ecb93.gif)

**Comment by erezrokah** [comment] 2020-03-02 15:02
One thing I can think of is that this issue was opened somewhat during a GitHub downtime:
https://www.githubstatus.com/incidents/q07bfjh7jf1t

Not sure that this is fully related though. I couldn't find a PR referencing the screenshot in the issue as well.

**Comment by andreamussap** [comment] 2020-03-02 15:05
@erezrokah I've noticed that my contributor's fork was outdated: 

https://github.com/amussapvordel/axway-open-docs - **This branch is 150 commits behind Axway:master.**

So I've deleted this fork, and now the edition on CMS is working for me again.

I think it's safe to say then that the issue is related to outdated forks. We were expecting thought that the fixes on https://github.com/Axway/axway-open-docs/pull/203 would address this. We even advertise on our blog that the issue with outdated forks were solved: [Usability improvements for Axway-Open-Docs](https://axway-open-docs.netlify.com/blog/2020/02/17/usability-improvements-for-axway-open-docs/)

**Comment by erezrokah** [comment] 2020-03-02 15:16
Thanks for the additional info @andreamussap, that is very helpful. I'll try to reproduce again.

Each contributor PR is rebased with the upstream default branch on save, but forks are not synced as a whole, so that might explain it.

Let me dig into this.

**Comment by alexearnshaw** [comment] 2020-03-03 07:54
Hi @erezrokah, yes just to clarify further - the issue only occurs if the contributors fork does not contain the PR that @erquhart contributed to our project (i.e. if the fork is from before that PR was merged on 13 Feb).

However it's also important to note that this problem did not occur (even on outdated forks) until last week (a [contribution](https://github.com/Axway/axway-open-docs/pull/427) made from an outdated fork worked fine on 20 Feb) so I'm wondering was there a change in the CMS since 20 Feb that might have somehow caused this problem to suddenly appear?

Our project is currently set to auto update to the latest CMS release, but I'm thinking if we can identify which CMS release triggered the issue, then we could roll back the CMS version manually to a previous release that doesn't have this issue?

**Comment by erezrokah** [comment] 2020-03-03 09:29
@alexearnshaw you’re right. This is indeed a regression with the latest version of the CMS.
I already submitted a fix here:
https://github.com/netlify/netlify-cms/pull/3363 and it should be approved and published soon.
The underlying issue is that we changed the way the CMS stores entries metadata from using an orphan ref to pull requests labels and inference based on changes to entries branches.
That required using GitHub compare API, which we had a bug when doing cross repo comparisons that is more evident in out of synced forks.
Using an older version of the CMS might cause issues for entries created after the upgrade.
I’ll open new issues to add tests with out of synced forks on our end (we do have tests for open authoring, but only with new forks) and we should also consider promoting the user to sync the fork via the CMS if it’s too out of date.

**Comment by alexearnshaw** [comment] 2020-03-03 09:52
> Using an older version of the CMS might cause issues for entries created after the upgrade.

Ok, we're happy to await the fix in that case. 

> I’ll open new issues to add tests with out of synced forks on our end (we do have tests for open authoring, but only with new forks) and we should also consider promoting the user to sync the fork via the CMS if it’s too out of date.

This would be really helpful. I think almost all of the issues our users have encountered in the past were as a result of out of sync forks.

Re promoting the user to sync the fork via the CMS - Not sure if I understand what you're proposing here but if there's some way the CMS can prompt the user for permission and then sync the fork for them (rather than sending them to Github or CLI to do it manually) then I think this would be a great idea.

Thanks a lot for the quick response and help on this issue!

**Comment by erezrokah** [comment] 2020-03-03 15:39
Sorry for not being clear enough.
The CMS should sync the fork for the user, but display a prompt for the user before doing so as the syncing operation can take a few minutes and also fail sometimes in case of conflicts.

**Closed** 2020-03-03 18:12 UTC

**Comment by erezrokah** [comment] 2020-03-04 08:30
Update: a fix for this is now released in `netlify-cms@2.10.30`.

Relevant derived issues:
https://github.com/netlify/netlify-cms/issues/3372
https://github.com/netlify/netlify-cms/issues/3373
