### ISSUE TITLE
Add setting to Date widget so it doesn't display date in American format

### ISSUE THREAD

**Issue by jazoom** [netlify/netlify-cms#1736] opened 2018-09-10 03:00 UTC
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
The date shows in American format, which was very confusing until I worked out what it was doing. It's still annoying since every time I look at it I have to make sure to remember to read it in the mixed-up way of MM/DD/YYYY.

**Describe alternatives you've considered**
Setting the `format` setting to `YYYY-MM-DD` does not affect how the date is displayed in Netlify CMS's widget.

**Additional context**
Most people in this world aren't American.

**Comment by bjrn** [comment] 2018-09-10 13:49
Hi @jazoom! - looks like we want the same thing … Duplicate of https://github.com/netlify/netlify-cms/issues/1648

**Closed** 2018-09-10 18:01 UTC

**Comment by jazoom** [comment] 2018-09-10 20:59
Thanks. I did search but I guess none of the keywords I used feature in your issue.
