### ISSUE TITLE
Netlify CMS previews not working for Eleventy sites.

### ISSUE THREAD

**Issue by kylesloper** [netlify/netlify-cms#4649] opened 2020-11-28 14:49 UTC
#### Just the other day the Previews were working like normal -- see screenshots below:

![image](https://user-images.githubusercontent.com/45979758/100517690-6a12e780-3184-11eb-917b-3daeb54716af.png)

#### And then out of nowhere they stopped -- see screenshots below:

![image](https://user-images.githubusercontent.com/45979758/100517701-8adb3d00-3184-11eb-8cce-4b3a3a9922e0.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Tested in chrome 22, safari, android
 - Node.JS version:

**CMS configuration**

```yaml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: false

media_folder: "static/img" # Media files will be stored in the repo under images/uploads
logo_url: /static\img\moonface-logo.png


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Link", name: "permalink", widget: "string", default: "(page-title)/index.html" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Hide on navbar", name: "parent", widget: "boolean", default: false }
          - { label: "Title on navbar", name: "key", widget: "string", required: false }
          - { label: "Order on navbar", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown", required: false }
```

**Comment by erezrokah** [comment] 2020-11-30 10:58
Hi @kylesloper, I recommend sharing a repo reproducing the issue. This is most likely related to build configuration, specifically how you are injecting site styles into the CMS. Without looking at some code it would be very hard to identify the root cause.

**Comment by kylesloper** [comment] 2020-11-30 20:06
Here is the repo to the site.
[](https://github.com/kylesloper/moonface)

**Comment by kylesloper** [comment] 2020-12-15 23:00
> Hi @kylesloper, I recommend sharing a repo reproducing the issue. This is most likely related to build configuration, specifically how you are injecting site styles into the CMS. Without looking at some code it would be very hard to identify the root cause.

Do we have an update on this at all?

**Comment by davidhund** [comment] 2020-12-16 16:33
👍 I'm quite new to Netlify CMS and wondered why I currently do not see a preview of my markdown post at all — the preview is both unstyled, but also the 11ty `njk` templates are not processed. It seems to be showing the 'raw' markdown instead… 

I might be completly misunderstanding what Netlify CMS provides out of the box however, since I did read about some `Custom Preview Templates` or something 😸

**Comment by kylesloper** [comment] 2020-12-16 16:36
> 👍 I'm quite new to Netlify CMS and wondered why I currently do not see a preview of my markdown post at all — the preview is both unstyled, but also the 11ty `njk` templates are not processed. It seems to be showing the 'raw' markdown instead…
> 
> I might be completly misunderstanding what Netlify CMS provides out of the box however, since I did read about some `Custom Preview Templates` or something 😸

Do your previews work locally and then not after site build. If they don't even work locally this isn't the right issue for you.

**Comment by davidhund** [comment] 2020-12-16 16:39
Not even locally…
Are you aware of any good discussions re: 'em working at all?

**Comment by erezrokah** [comment] 2020-12-20 11:31
Hi @kylesloper, I forked your repo and deployed to Netlify.
The styles are displayed correctly on my live site:
![image](https://user-images.githubusercontent.com/26760571/102712149-6c6dea80-42c7-11eb-8d75-7cb000944d0e.png)

Could this be a caching/browser issue?
Do you mind trying building with clearing cache on Netlify then with a different browser/private mode with no extensions.

**Comment by kylesloper** [comment] 2021-01-01 19:33
Hi sorry for the late response. I ended up re-building the site entirely and creating a new site with Netlify. Unfortunately this meant I could not identify what the source of the issue was but its working now.

**Comment by erezrokah** [comment] 2021-01-04 11:20
Thank your @kylesloper for the follow up. Closing this issue

**Closed by erezrokah** 2021-01-04 11:20 UTC
Labels: ssg: 11ty, type: bug
